"""Lengthen every stem toward the 50-55 word median the official samples show, fix two
name-detector false positives, and re-frame Q52 (caught by the gate as a reskin of
Exam 12 Q50 -- same section, same 'two definitions drift apart' shape)."""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))

STEMS = {
1: "A brief on non-pharmacological management of chronic pain comes back covering physiotherapy in depth and nothing else. The panel expected psychological, procedural and device-based approaches as well. The run logs show four subagents dispatched, fourteen searches executed, and every result accurate and well-sourced for the query it was given. Where does the failure sit?",
2: "The coordinator's prompt reads: \"Step 1, search the trial registry. Step 2, open the first eight results. Step 3, summarise each in 120 words.\" The briefs come back uniformly shallow, and when a registry search surfaces nothing useful the run still produces eight summaries of marginal trials rather than widening its search. What should change?",
3: "Two tools are available to the search subagent: `search_trial_registry` (\"Finds studies\") and `search_publication_index` (\"Finds published research\"). Both accept a free-text query string and both return title-and-abstract records. Logs from the past fortnight show registry lookups being routed to the publication index on roughly 40% of calls. What is the first thing to fix?",
4: "A panel request covers three independent questions: current first-line therapy, adverse-event rates, and cost-effectiveness. The coordinator issues one `Task` call, waits for it to return, then issues the next, and a full brief now takes about eleven minutes. All three questions need the same baseline patient-population context. Which approach uses the architecture correctly?",
5: "The brief's conflict section reports: \"One source states prevalence at 8%, another at 13% — contradiction.\" On inspection the two figures come from national surveys five years apart, and both are correct for their own period. Three such false conflicts appeared last month, and the panel has begun distrusting every conflict the system flags. What is the underlying problem?",
6: "The full-text subagent times out on a publisher endpoint after retrying twice, having already parsed nine of the fourteen papers assigned to it. It returns `{\"status\": \"failed\"}` to the coordinator, which logs that string and abandons the entire run, discarding the nine parsed papers with it. Which two changes follow the structured error-propagation pattern? Select two.",
7: "The synthesis subagent returns a draft covering adult populations thoroughly and saying nothing about the paediatric subgroup the request named. Reviewing the run shows the searches that executed never targeted that subgroup, and the registry does hold paediatric trials for this indication. The coordinator now holds the draft. What should the architecture do at this point?",
8: "The search subagent has accumulated nineteen tools as new evidence sources were integrated over two years. It now selects the wrong source tool on roughly one call in four. The document subagent, holding five tools, almost never misroutes. Both run the same model on similarly structured prompts. What should change first?",
9: "The synthesis subagent's draft ignores three high-quality trials the search subagent surfaced earlier in the same run. The coordinator's own conversation history contains all three, complete with abstracts and effect sizes. The synthesis subagent's prompt instructs it to \"synthesise all findings gathered so far\" and says nothing further. What explains the omission?",
10: "Combined subagent output reaching the synthesis step runs to roughly 80,000 tokens per brief. Sampling of recent drafts shows they reliably reflect the opening sections and the closing conclusions, while findings positioned in the middle of that input are omitted or garbled. Which change addresses the cause?",
11: "While drafting, the synthesis subagent needs to confirm single facts — a dosage figure, a sample size — dozens of times per brief. Routing each check through the coordinator adds a full round-trip and is now the slowest part of the run, so the team proposes giving it broad search access. Which three statements are correct? Select three.",
12: "A registry query for trials in a rare indication legitimately returns no matches, which is itself a useful finding for the brief. The tool reports that outcome as `isError: true`. The coordinator responds by retrying the identical query twice and then escalating the whole run as blocked. What is the correct signal for this outcome?",
13: "Of the five evidence categories the brief requires, two came back empty because their sources were unreachable for the whole run and the retry budget is exhausted. The synthesis subagent holds usable material for the other three categories, and the review panel sits in an hour. What should it produce?",
14: "A six-hour brief run crashes with the search and document subagents complete and synthesis half-finished. Restarting re-executes everything from the beginning, including the ninety searches that already succeeded, and the team has now lost two afternoons this way. Which two changes let the coordinator resume from where it stopped? Select two.",
15: "Your evidence sources are exposed to the agent as an MCP resource listing every available registry, its coverage window and its field schema. A teammate reviewing the design argues this should have been a `list_sources` tool instead, since the agent could then request only the registries it needs. Which statement correctly distinguishes the two?",
16: "You ask the agent to add test coverage to the discharge-scheduling module, which currently has none and which nobody remaining fully understands. Two decomposition strategies are on the table: a predetermined sequence of steps fixed before any code is read, or subtasks generated from what each step uncovers. Which is appropriate here?",
17: "A deprecated `assignBedByPriority` helper is being removed, and you need every location that calls it across a repository whose naming conventions drifted years ago. An engineer proposes running Glob over `**/assignBedByPriority*` and reports that it returned two files, both of them tests. What is wrong with that, and what should run instead?",
18: "The agent applies your transfer-request audit-logging convention in some sessions and ignores it in others, on the same repository and the same files. The instruction is definitely written down somewhere, and a colleague working on the same codebase sees it applied every single time. What is the first diagnostic step?",
19: "Yesterday's named session mapped the bed-allocation call graph in depth, and that analysis is still largely valid. Overnight another team refactored three of the roughly forty files it examined. You need to continue the same investigation today without paying for the whole mapping again. What is the right way to resume?",
20: "The agent attempts to Edit a status constant in a 900-line scheduling file. The anchor text it selected appears in four places, and the edit fails with a non-unique-match error. The agent proposes retrying with a shorter anchor that it expects will be easier to locate. What should happen instead?",
21: "The agent generates a bed-reassignment routine, reasons at length about edge cases in its own output, and concludes the approach is correct. Asked in the same conversation to check its work again, it confirms the result. Two subtle defects surface in human review a week later. Which two changes address the cause? Select two.",
22: "A `/trace-dependencies` skill walks the scheduling module's imports and returns several thousand lines of output into the conversation. After it runs, the agent has lost track of the refactor it was carrying out beforehand and begins proposing unrelated changes. Which frontmatter change fixes this?",
23: "A colleague's in-house harness wraps the API and keeps calling until the response text no longer contains the word \"next\". It sometimes halts mid-task with tool calls still unexecuted, and sometimes keeps looping long after the work is finished. What should drive the loop instead?",
24: "Two tasks are queued: replacing the scheduling engine's persistence layer across roughly fifty files, where several designs are viable and the choice affects every caller, and fixing a null-dereference crash with a clear stack trace in a single file. Which pairing of modes is correct?",
25: "An expensive analysis of the transfer-request state machine has just completed, having taken most of an afternoon. The team wants to evaluate two migration strategies against that analysis, and wants neither evaluation coloured by the other's reasoning or conclusions. What should they do?",
26: "Six months ago the team replaced two frequently co-called tools with a composite `get_patient_with_transfers`, and it has worked well since. A new requirement needs patient records without any transfer history; another needs transfers for a whole ward rather than for a single patient. Which three statements are sound? Select three.",
27: "Adding audit hooks across the platform's 140 service files requires a discovery pass that enumerates every call site. On the last attempt the discovery output alone filled the context window before any implementation began, and the session had to be abandoned partway. What structure avoids this?",
28: "Conventions differ by area: scheduling services use a repository pattern, the interoperability adapters use async pipelines, and test files follow a fixture naming scheme. Files from all three areas sit side by side in most directories rather than in separate trees. Where do these conventions belong?",
29: "Your onboarding agent is configured with `allowed_tools=[\"Read\", \"Grep\", \"Glob\"]` and a system prompt instructing it to delegate deep dives to specialist subagents. It never delegates — it attempts everything itself, and its sessions run long and stay shallow. Which two statements are correct? Select two.",
30: "The agent holds a general `run_query` tool for the reporting database so that it can answer schema questions during exploration. It has started using that tool to run ad-hoc aggregate queries against live patient tables, which the compliance team has now flagged twice. What is the durable fix?",
31: "The provisioning repository's review job was added last week, and every run hangs until the runner's 30-minute timeout kills it. No output is ever written to the job log. The command in the workflow file reads `claude \"Review this diff for regressions\"`. What is missing?",
32: "Six weeks of review data: style findings run at 54% false positive, documentation at 47%, security at 7%, performance at 16%. Engineers have begun dismissing every comment the job posts, security findings included, and two genuine vulnerabilities were closed unread last sprint. What should the team do?",
33: "Findings currently arrive as prose in the job log, and a script scrapes them with regular expressions to post inline pull-request comments. The scraper has broken three times this quarter whenever phrasing shifted. Each comment needs a file path, a line number, a severity and a suggested fix. What should replace the scraper?",
34: "Each time an author pushes a follow-up commit, the review job re-posts near-identical comments on code that has not changed, with slightly different wording every run. Some threads now run to dozens of comments and authors have started resolving them unread. What should the re-run prompt include?",
35: "A pull request touching eighteen files receives a detailed review on four of them, cursory notes on the rest, and one pattern flagged in one file yet explicitly approved in another. Re-running the job produces a different four files. Which two changes address the cause? Select two.",
36: "A weekly dependency-audit job runs on the Message Batches API, and its report must reach the platform lead 30 hours after submission. The schedule is being fixed now. The team is planning around batches that have so far always completed within about an hour. What submission window does the SLA actually permit?",
37: "The pipeline's remediation step can apply mechanical fixes automatically. Twice now it has rewritten more than 200 files in a single run after a shared formatting rule changed, and both runs reached the default branch. Policy states that any change touching over 50 files requires human approval. Where does that rule belong?",
38: "Generated tests for the circuit-activation service compile and pass, but they ignore the team's fixture conventions, assert on internals rather than on behaviour, and duplicate scenarios the existing suite already covers. Roughly half of each generated batch is discarded in review. What supplies the missing context to the CI-invoked run?",
39: "Review comments vary in shape from run to run: sometimes a bare observation, sometimes a fix, sometimes a paragraph of surrounding context. The prompt already specifies the required format across three sentences, and tightening that wording twice has changed nothing. What is the effective next move?",
40: "A review of the activation module raised three issues: a race in the retry path, a lock-ordering defect that the retry path depends on, and a misspelled log string. You are feeding these back for fixes and want to avoid a second round of rework. Which three statements are sound? Select three.",
41: "The prompt instructs the reviewer to \"check that comments are accurate.\" It now flags every comment that is merely terse or slightly out of date — around sixty per pull request — burying the handful that actively describe the wrong behaviour. How should the criterion be rewritten?",
42: "The pipeline generates a migration script and then, in the same session, asks for a review of that script. Reviews come back clean; defects surface later in staging, three times this quarter. A colleague suggests adding \"be more critical\" to the review step's prompt. What is the actual problem?",
43: "The triage step must always return a structured verdict, but roughly one run in twelve comes back as a paragraph of prose instead of a tool call, and the downstream parser fails on it. Three verdict tools are defined, one per severity band. Which two statements are correct? Select two.",
44: "Engineers dismiss roughly a third of all findings, but the team cannot tell which kinds are noise and which are being waved through unfairly. Dismissals are currently recorded as a timestamp and a username, with no reference to what was flagged. What change makes the pattern analysable?",
45: "A number-porting script mishandles rows where the donor-carrier field is null. Three rounds of describing the defect in prose have produced three partial fixes, each of which broke something that previously worked. The failure reproduces reliably on a local sample. Which two moves converge fastest? Select two.",
46: "The schema marks `fumigation_certificate_number` as required and non-nullable, because settlement needs it. Roughly one consignment in six ships without fumigation, and those documents genuinely carry no such number. Those records now hold plausible-looking numbers that match nothing in the fumigation registry. What is the correct schema change?",
47: "Overall extraction accuracy sits at 97%, and the team proposes auto-processing everything above the confidence threshold from next month. Phytosanitary declarations account for about 4% of volume, arrive in three languages, and nobody has measured their accuracy separately. What should happen before the change?",
48: "Weighbridge tickets list individual bag weights and a stated net total. Reconciliation discovers, weeks after release and after settlement has already run, that the two sometimes disagree by several tonnes. What should the extraction produce so that the disagreement surfaces at extraction time instead?",
49: "High-confidence extractions are now processed without human review, and they account for roughly 80% of volume. The team wants to keep measuring the true error rate of that automated path without re-reviewing everything it emits. Which two properties should the audit sample have? Select two.",
50: "Validation fails on `container_seal_number` for 60 consignments, and the loop retries each of them three times before giving up. Investigation shows all 60 moved as break-bulk cargo, which uses no containers and therefore carries no seals at all. What is the right response?",
51: "An inspection certificate records moisture content at 12.4%. The fumigation record for the same lot, issued the same day by a different inspector, records 13.1%. Both documents are authentic, neither is obviously superseded, and settlement tolerances turn on this figure. What should the pipeline emit?",
52: "The pipeline validates every extracted record in code after the model returns it, on top of the `tool_use` schema that already constrains the shape. An engineer proposes deleting that validation layer as duplicated effort, noting that the schema already enforces types, required fields and enum membership. Which response is correct?",
53: "A `release_to_settlement` tool rejects a consignment because its inspection certificate expired 40 days ago and policy permits 30. The tool returns `\"Operation failed\"`. The agent retries six times over four minutes, then escalates to a human who reads the policy and declines the release. How should the tool respond instead?",
54: "A `PostToolUse` hook trims the OCR tool's output to plain text plus a page-confidence score. Since it shipped, context pressure has eased markedly — but the review queue can no longer show reviewers where on a page a disputed value was read from, and dispute handling has slowed. Which three statements are sound? Select three.",
55: "A batch of 400 consignment documents returns 388 successes and 12 failures, all of them oversized multi-page scans that exceeded the context limit. Results arrived in a different order from submission, and the settlement deadline falls tomorrow. What is the correct recovery?",
56: "Settlement disputes require showing which document a figure came from. Records currently carry the extracted values plus a list of the source filenames processed in that run, often twenty or more of them. Brokers cannot tell which file produced which field. What is absent from the record?",
57: "The `commodity_grade` field is an enum of the six grades in the current standard. Inspectors on older certificates sometimes wrote regional grade names that map to none of the six, and the model currently picks whichever of the six is closest without comment. Downstream pricing then applies the wrong band. What should the schema do?",
58: "Document type must be classified before any commodity-specific extraction tool runs, since the extraction tools differ by type. A prompt instruction achieves this roughly 90% of the time; the other 10% extract against the wrong schema and fail validation further downstream. What configuration guarantees the ordering?",
59: "A broker's clarification thread about one consignment has run to 74 turns and 62,000 tokens. It contains an agreed moisture tolerance, two amended quantities, and a great deal of scheduling chatter about vessel timings. Which two moves preserve what matters? Select two.",
60: "Semantic errors — a grade recorded against the wrong lot, a tonnage contradicting the weighbridge line — still reach downstream systems at roughly last year's rate, though JSON parse failures have sat at zero all year. A team lead proposes abandoning `tool_use` schemas, arguing that they plainly did not help. What is wrong with that reasoning?",
}

# Q52 re-framed: the gate flagged the original at 0.431 Jaccard against Exam 12 Q50 --
# same section (D4 §4.8) and the same "two hand-maintained definitions drift" shape.
# This tests the section's other half: whether the code validation layer earns its place
# at all, which is the §4.8 misconception rather than the drift scenario.
Q52 = {
    "options": [
        "Keep it: no JSON schema can express that a stated net weight equals the sum of its bag weights.",
        "Delete it — the schema enforces the contract at generation time, so the second pass only adds latency.",
        "Keep it, but only for fields the schema marks optional, where the model has the most latitude.",
        "Replace both layers with a stricter schema encoding the cross-field rules as nested constraints.",
    ],
    "correct": 0,
    "whyRight": {
        "text": "Tool use enforces structure at generation time, but code should still validate semantic and business rules no JSON schema can express — a cross-field sum, a date ordering — plus defence in depth for whatever consumes the record downstream. The schema constrains shape; the validator checks meaning.",
        "cite": "CCA-Prep_Domain-4_v2.md §4.8",
    },
    "whyWrong": [
        {"option": 1, "text": "This is the named misconception. Structural enforcement at generation time says nothing about whether the values are right, and removing the layer removes the only check on business rules.", "cite": "CCA-Prep_Domain-4_v2.md §4.8"},
        {"option": 2, "text": "Optionality is unrelated to semantic risk. A required, well-typed tonnage field can still be wrong, and cross-field rules span required fields by definition.", "cite": "CCA-Prep_Domain-4_v2.md §4.8"},
        {"option": 3, "text": "No schema constraint can verify that numbers sum correctly or that one date precedes another. Tightening the schema cannot reach the class of rule the validator exists for.", "cite": "CCA-Prep_Domain-4_v2.md §4.7"},
    ],
}

changed = 0
for i in range(1, 5):
    p = os.path.join(HERE, f"block{i}.json")
    b = json.load(open(p, encoding="utf-8"))
    for q in b["questions"]:
        if q["g"] in STEMS:
            q["stem"] = STEMS[q["g"]]
            changed += 1
        if q["g"] == 52:
            q.update(Q52)
    json.dump(b, open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=2)

wc = sorted(len(re.sub(r"\s+", " ", s).split()) for s in STEMS.values())
print(f"stems rewritten: {changed}")
print(f"word counts -> min {wc[0]}  median {wc[len(wc)//2]}  max {wc[-1]}")
