# CCA-F Concept Atlas — concept inventory (Phase 1)
# Every card lists the official-guide bullet IDs it covers (see bullets.json, produced by extract_bullets.py).
# check_coverage.py asserts that every one of the 288 IDs maps to at least one card.
#
# Fields: id, title, ts (home task statement), gist (one flat sentence — the concept), bul (bullet IDs covered),
#         kd (Key-Distinction numbers woven in), xref (other domains' task statements this card also serves)
#
# Metaphor system (clean sheet — one civic building per domain, all on one town map):
#   D1 = the control tower (airport)   D2 = the library   D3 = the office (handbook, floors, binders)
#   D4 = the courthouse (clerk's office)   D5 = the hospital ward (chart & handover)

DOMAINS = {
    "D1": {"name": "Agentic Architecture & Orchestration", "weight": 27, "world": "tower",
           "world_name": "The control tower"},
    "D2": {"name": "Tool Design & MCP Integration", "weight": 18, "world": "library",
           "world_name": "The library"},
    "D3": {"name": "Claude Code Configuration & Workflows", "weight": 20, "world": "office",
           "world_name": "The office"},
    "D4": {"name": "Prompt Engineering & Structured Output", "weight": 20, "world": "court",
           "world_name": "The courthouse"},
    "D5": {"name": "Context Management & Reliability", "weight": 15, "world": "ward",
           "world_name": "The hospital ward"},
}

SHORT = {"D1": "Agentic architecture", "D2": "Tools & MCP", "D3": "Claude Code", "D4": "Prompts & output", "D5": "Context & reliability"}

# Authoring is split into half-domain parts so no single agent emits a very large file.
# merge_parts.py concatenates each domain's parts into items_dN.py in inventory order.
PARTS = {
    "d1a": ("D1", 1, 13), "d1b": ("D1", 14, 25),
    "d2a": ("D2", 1, 10), "d2b": ("D2", 11, 19),
    "d4a": ("D4", 1, 12), "d4b": ("D4", 13, 24),
    "d5a": ("D5", 1, 15), "d5b": ("D5", 16, 30),
}


def part_ids(part):
    dom, lo, hi = PARTS[part]
    return [f"{dom}-{n:02d}" for n in range(lo, hi + 1)]

# The decisive point of each Key Distinction, one flat line each (rendered on the Traps page; source: CCA-Prep_Key-Distinctions_v1.md, official framing wins).
KD_POINT = {
 1: "Project-scope `CLAUDE.md` is version-controlled and shared; `~/.claude/CLAUDE.md` is only that user's. A teammate not getting a convention means it lives in user scope.",
 2: "`.mcp.json` in the repo is the shared server config; `~/.claude.json` is personal. Shared server plus per-developer secret means `.mcp.json` with `${TOKEN}` expansion.",
 3: "`CLAUDE.md` loads every session; `.claude/rules/` files load when a path glob matches; skills load on demand when invoked.",
 4: "A personal variant of a team skill lives in `~/.claude/skills/` under its own name so teammates are unaffected. (The community guide adds: a same-name personal skill overrides the project one.)",
 5: "`tool_use` means run the tool, append the result and loop; `end_turn` means done. The text content is never the completion signal.",
 6: "All subagent communication passes through the coordinator; direct subagent-to-subagent links lose observability and uniform error handling.",
 7: "Every subagent succeeded and topics are still missing means the coordinator's decomposition was too narrow — fix the coordinator, not the subagents.",
 8: "Return failure type, attempted query, partial results and alternatives; a bare \"search unavailable\" leaves the coordinator only retry-or-abort.",
 9: "Transient errors are retryable; validation, business and permission errors are not. Zero results is a successful query; a timeout is an access failure.",
 10: "Misrouting between similar tools: rewrite the descriptions first. A routing classifier adds infrastructure without fixing the ambiguity.",
 11: "A sequence that must hold (verify identity before a refund) is enforced in code — a hook or prerequisite gate. Prompt instructions are probabilistic.",
 12: "A mandatory preview is guaranteed only when the execute tool needs a token issued by the preview tool; a `dry_run` boolean can be skipped.",
 13: "`context: fork` runs a skill in an isolated sub-agent, which keeps its verbose or exploratory working from polluting the main conversation; the result still returns.",
 14: "Batches: 50% cheaper, up to 24 hours, no SLA, no mid-request tool calling — for overnight and weekly work. Blocking checks stay synchronous.",
 15: "`-p` / `--print` is the non-interactive mode for CI. `CLAUDE_HEADLESS`, `--batch` and stdin tricks are not the documented mechanism.",
 16: "Inconsistent output format: add few-shot examples of the exact format. Longer instructions are the option that already failed.",
 17: "A large PR reviewed in one pass gives uneven, contradictory findings: per-file passes plus an integration pass. A bigger context window does not restore attention.",
 18: "Misrouting on ambiguous requests: a few examples aimed at exactly those cases, with the reasoning. Many clear-cut examples miss the point.",
 19: "Vague request: proceed on stated assumptions and invite correction. A wall of clarifying questions drives abandonment; hidden defaults confuse.",
 20: "Lost in the middle: key-findings summary first and explicit section headers. Rotating which output comes first, or compressing everything, does not fix it.",
 21: "Precise amounts and dates survive in a persistent case-facts block outside the summarised history. A better summarisation prompt still relies on perfect execution.",
 22: "Verbose discovery goes to an isolated subagent (Explore) that returns a summary, preventing the window from filling. The guide separately lists `/compact` for reducing usage once a session has filled, so it is a listed technique rather than a wrong answer in itself.",
 23: "System-prompt behaviour degrading after a few short turns is accumulated responses diluting the instructions — not context overflow, and not the system prompt \"applying only to turn one\".",
 24: "Specific recall over months of history needs retrieval of the actual exchange; progressive summarisation compresses the conclusion into an abstraction. The guide puts embedding and vector-database implementation details out of scope, so no question turns on how retrieval is built.",
 25: "The API is stateless: memory is the `messages` array you send. There is no `session_id`, and ordinary multi-turn memory needs no vector database.",
 26: "Grep searches inside files (callers, error strings, imports); Glob matches paths (`**/*.test.tsx`).",
 27: "Edit needs a unique text anchor; when it fails, fall back to Read then Write — not a shorter anchor, not `sed`.",
 28: "Understand a codebase with Grep to find entry points, then Read to trace — not by reading every file first.",
 29: "The agent keeps choosing built-in Grep over a capable MCP tool: enhance the MCP tool's description. Do not remove Grep or add a blanket \"prefer MCP\" rule.",
}

CARDS = [
# ============================================================ D1 ============================================================
{"id": "D1-01", "ts": "1.1", "title": "The agentic loop runs on stop_reason",
 "gist": "Send the request, read stop_reason: tool_use means run the tool and go round again; end_turn means the loop is finished.",
 "bul": ["1.1-K1", "1.1-S1", "APP-I1", "APP-T5", "APP-T1"], "kd": [5]},
{"id": "D1-02", "ts": "1.1", "title": "Tool results are appended to the conversation",
 "gist": "Each tool result goes back into the message history so the next iteration can reason over it.",
 "bul": ["1.1-K2", "1.1-S2", "APP-I1"], "kd": []},
{"id": "D1-03", "ts": "1.1", "title": "Model-driven decisions, not a hard-coded decision tree",
 "gist": "Claude decides which tool to call next from context; a pre-configured tool sequence is not an agent.",
 "bul": ["1.1-K3"], "kd": []},
{"id": "D1-04", "ts": "1.1", "title": "Loop-termination anti-patterns",
 "gist": "Do not end the loop on parsed text, an iteration cap, or the presence of assistant text — only on stop_reason.",
 "bul": ["1.1-S3", "APP-I1"], "kd": [5]},
{"id": "D1-05", "ts": "1.2", "title": "Hub-and-spoke: every message goes through the coordinator",
 "gist": "Subagents never talk to each other; the coordinator routes all communication, errors and information.",
 "bul": ["1.2-K1", "1.2-S4", "APP-I2"], "kd": [6]},
{"id": "D1-06", "ts": "1.2", "title": "Subagents start with an empty context",
 "gist": "A subagent inherits nothing; everything it needs must be written into its prompt.",
 "bul": ["1.2-K2", "1.3-K2", "1.3-S1", "APP-I3", "APP-T13"], "kd": []},
{"id": "D1-07", "ts": "1.2", "title": "The coordinator decomposes, delegates, aggregates — and chooses",
 "gist": "The coordinator breaks the task down, picks which subagents to invoke for this query, and merges results; it does not run the full pipeline every time.",
 "bul": ["1.2-K3", "1.2-S1", "APP-I2"], "kd": []},
{"id": "D1-08", "ts": "1.2", "title": "Narrow decomposition leaves coverage gaps",
 "gist": "When every subagent succeeds and the answer is still incomplete, the coordinator's decomposition was too narrow.",
 "bul": ["1.2-K4"], "kd": [7]},
{"id": "D1-09", "ts": "1.2", "title": "Partition scope so subagents do not duplicate work",
 "gist": "Give each subagent a distinct subtopic or source type.",
 "bul": ["1.2-S2"], "kd": []},
{"id": "D1-10", "ts": "1.2", "title": "Iterative refinement: evaluate, re-delegate, re-synthesise",
 "gist": "The coordinator checks the synthesis for gaps, sends targeted queries back to search/analysis, and re-runs synthesis until coverage is sufficient.",
 "bul": ["1.2-S3", "APP-I2"], "kd": []},
{"id": "D1-11", "ts": "1.3", "title": "Task tool + allowedTools includes \"Task\"",
 "gist": "Subagents are spawned with the Task tool; a coordinator whose allowedTools omits \"Task\" cannot delegate.",
 "bul": ["1.3-K1", "APP-T1"], "kd": []},
{"id": "D1-12", "ts": "1.3", "title": "AgentDefinition: description, system prompt, tool restrictions",
 "gist": "Each subagent type is configured with a description, its own system prompt and the tools it may use.",
 "bul": ["1.3-K3", "APP-T1"], "kd": []},
{"id": "D1-13", "ts": "1.3", "title": "Content and metadata travel in separate fields",
 "gist": "Pass findings between agents in structured form so source URLs, document names and page numbers survive.",
 "bul": ["1.3-S2"], "kd": [], "xref": ["5.6"]},
{"id": "D1-14", "ts": "1.3", "title": "Parallel subagents = multiple Task calls in ONE response",
 "gist": "Emit all Task calls in a single coordinator turn; one per turn is sequential.",
 "bul": ["1.3-S3", "APP-I2"], "kd": []},
{"id": "D1-15", "ts": "1.3", "title": "Coordinator prompts state goals and quality criteria, not procedures",
 "gist": "Give subagents the research goal and what good looks like; a step-by-step script removes their ability to adapt.",
 "bul": ["1.3-S4"], "kd": []},
{"id": "D1-16", "ts": "1.4", "title": "Programmatic enforcement vs prompt guidance",
 "gist": "When a sequence must hold (identity check before a refund), enforce it in code — hooks or prerequisite gates — because prompt compliance has a non-zero failure rate.",
 "bul": ["1.4-K1", "1.4-K2", "1.4-S1", "1.5-K3", "1.5-S3"], "kd": [11]},
{"id": "D1-17", "ts": "1.4", "title": "Structured handoff to a human",
 "gist": "An escalation carries customer ID, root cause, amount and recommended action, because the human cannot see the transcript.",
 "bul": ["1.4-K3", "1.4-S3"], "kd": []},
{"id": "D1-18", "ts": "1.4", "title": "Multi-concern requests: split, investigate in parallel, synthesise",
 "gist": "Decompose a message with several issues into items, work them in parallel with shared context, then answer once.",
 "bul": ["1.4-S2"], "kd": []},
{"id": "D1-19", "ts": "1.4", "title": "Two-tool token binding vs a dry_run flag",
 "gist": "A mandatory preview is guaranteed only when the execute tool needs a token that the preview tool issues; a boolean can be skipped.",
 "bul": [], "kd": [12], "note": "Practice-test distinction adjacent to TS 1.4/1.5 (enforcement in code)."},
{"id": "D1-20", "ts": "1.5", "title": "PostToolUse hooks normalise tool results",
 "gist": "A PostToolUse hook rewrites heterogeneous formats (Unix timestamps, ISO 8601, numeric codes) before the model sees them.",
 "bul": ["1.5-K1", "1.5-S1", "APP-T1"], "kd": []},
{"id": "D1-21", "ts": "1.5", "title": "Intercept outgoing tool calls to block and redirect",
 "gist": "A hook on the outgoing call blocks a policy violation (refund over $500) and redirects to escalation.",
 "bul": ["1.5-K2", "1.5-S2", "APP-T1"], "kd": []},
{"id": "D1-22", "ts": "1.6", "title": "Prompt chaining vs adaptive decomposition",
 "gist": "Fixed sequential chains suit predictable multi-aspect reviews; open-ended investigation needs subtasks generated from what each step finds.",
 "bul": ["1.6-K1", "1.6-K3", "1.6-S1", "1.6-S3", "APP-T11"], "kd": []},
{"id": "D1-23", "ts": "1.7", "title": "--resume <session-name> continues a named session",
 "gist": "Named sessions let you pick up a specific prior investigation across work sessions.",
 "bul": ["1.7-K1", "1.7-S1", "APP-T3", "APP-T13"], "kd": []},
{"id": "D1-24", "ts": "1.7", "title": "fork_session branches from a shared baseline",
 "gist": "Fork one analysed session into independent branches to compare approaches without re-analysing.",
 "bul": ["1.7-K2", "1.7-S2", "1.3-K4", "APP-T3", "APP-T13"], "kd": []},
{"id": "D1-25", "ts": "1.7", "title": "Resume, or start fresh with a summary — and say what changed",
 "gist": "Resume when prior context is still valid; start a new session with a structured summary when tool results are stale; on resume, name the files that changed.",
 "bul": ["1.7-K3", "1.7-K4", "1.7-S3", "1.7-S4", "APP-T13"], "kd": []},

# ============================================================ D2 ============================================================
{"id": "D2-01", "ts": "2.1", "title": "The description is the interface",
 "gist": "Tool selection runs on descriptions; include input formats, example queries, edge cases and when-to-use boundaries.",
 "bul": ["2.1-K1", "2.1-K2", "2.1-S1", "APP-I4", "APP-I5", "APP-T2"], "kd": [10]},
{"id": "D2-02", "ts": "2.1", "title": "Overlapping descriptions misroute — rename and differentiate",
 "gist": "Near-identical descriptions (analyze_content vs analyze_document) cause misrouting; fix by renaming and rewriting for a distinct purpose.",
 "bul": ["2.1-K3", "2.1-S2", "APP-I4"], "kd": [10]},
{"id": "D2-03", "ts": "2.1", "title": "Split generic tools into purpose-specific ones",
 "gist": "One vague analyze_document becomes extract_data_points, summarize_content, verify_claim_against_source, each with a defined contract.",
 "bul": ["2.1-S3", "APP-I4"], "kd": []},
{"id": "D2-04", "ts": "2.1", "title": "Keyword-sensitive system-prompt wording overrides good descriptions",
 "gist": "A phrase in the system prompt can bind a tool to a keyword; review the prompt when selection goes wrong despite good descriptions.",
 "bul": ["2.1-K4", "2.1-S4"], "kd": []},
{"id": "D2-05", "ts": "2.2", "title": "isError plus structured error metadata",
 "gist": "Return isError with errorCategory, isRetryable and a readable message; a generic \"Operation failed\" gives the agent nothing to decide on.",
 "bul": ["2.2-K1", "2.2-K3", "2.2-K4", "2.2-S1", "APP-I7", "APP-T2"], "kd": [8, 9]},
{"id": "D2-06", "ts": "2.2", "title": "Four error kinds: transient, validation, business, permission",
 "gist": "Each kind gets a different move — retry, fix the input, explain the policy (retriable: false), or ask for access.",
 "bul": ["2.2-K2", "2.2-S2", "APP-I7"], "kd": [9]},
{"id": "D2-07", "ts": "2.3", "title": "Fewer tools per agent",
 "gist": "Eighteen tools instead of four or five degrades selection; decision complexity is the cost.",
 "bul": ["2.3-K1"], "kd": []},
{"id": "D2-08", "ts": "2.3", "title": "Scoped tool sets per role, one cross-role tool for the common case",
 "gist": "Give each subagent only its role's tools; when one agent frequently needs another's capability, give it a scoped tool (verify_fact) and route the rare complex cases through the coordinator.",
 "bul": ["2.3-K2", "2.3-K3", "2.3-S1", "2.3-S3", "APP-T2"], "kd": []},
{"id": "D2-09", "ts": "2.3", "title": "Constrained alternatives to generic tools",
 "gist": "Replace fetch_url with load_document that validates document URLs.",
 "bul": ["2.3-S2"], "kd": []},
{"id": "D2-10", "ts": "2.4", "title": ".mcp.json (project, shared) vs ~/.claude.json (user, personal)",
 "gist": "Team servers live in the repo's .mcp.json; personal or experimental servers in ~/.claude.json.",
 "bul": ["2.4-K1", "2.4-S1", "2.4-S2", "APP-I6", "APP-T2"], "kd": [2]},
{"id": "D2-11", "ts": "2.4", "title": "${ENV_VAR} expansion keeps secrets out of the repo",
 "gist": ".mcp.json references ${GITHUB_TOKEN}; each developer supplies their own value.",
 "bul": ["2.4-K2", "2.4-S1", "APP-I6", "APP-T2"], "kd": [2]},
{"id": "D2-12", "ts": "2.4", "title": "All configured servers' tools are discovered at connection and available together",
 "gist": "Multiple MCP servers do not take turns; their tools are all on the table at once.",
 "bul": ["2.4-K3", "APP-I6"], "kd": []},
{"id": "D2-13", "ts": "2.4", "title": "MCP resources expose content catalogs",
 "gist": "Resources give the agent visibility into issue lists, doc hierarchies or schemas without exploratory tool calls; tools act, resources are read.",
 "bul": ["2.4-K4", "2.4-S5", "APP-I5", "APP-T2"], "kd": []},
{"id": "D2-14", "ts": "2.4", "title": "It keeps choosing Grep over your MCP tool — fix the description",
 "gist": "The agent prefers a familiar built-in unless the MCP tool's description spells out what it can do that Grep cannot.",
 "bul": ["2.4-S3", "APP-I5"], "kd": [29]},
{"id": "D2-15", "ts": "2.4", "title": "Community server for standard integrations, custom for your own workflows",
 "gist": "Use an existing Jira server; write your own only for team-specific behaviour.",
 "bul": ["2.4-S4"], "kd": []},
{"id": "D2-16", "ts": "2.5", "title": "Grep searches inside files; Glob matches paths",
 "gist": "Callers, error strings and imports are Grep; **/*.test.tsx is Glob.",
 "bul": ["2.5-K1", "2.5-K2", "2.5-S1", "2.5-S2", "APP-T9"], "kd": [26]},
{"id": "D2-17", "ts": "2.5", "title": "Edit needs a unique anchor; otherwise Read + Write",
 "gist": "Read/Write handle whole files; Edit replaces by unique text match and fails on duplicates, so fall back to Read then Write.",
 "bul": ["2.5-K3", "2.5-K4", "2.5-S3", "APP-T9"], "kd": [27]},
{"id": "D2-18", "ts": "2.5", "title": "Grep first, then Read to trace — never read everything up front",
 "gist": "Find entry points by content search, then follow imports with targeted reads.",
 "bul": ["2.5-S4", "APP-T9"], "kd": [28]},
{"id": "D2-19", "ts": "2.5", "title": "Tracing through wrappers: list the exports, then search each name",
 "gist": "Identify every exported name first, then Grep for each across the codebase.",
 "bul": ["2.5-S5"], "kd": []},

# ============================================================ D3 ============================================================
{"id": "D3-01", "ts": "3.1", "title": "CLAUDE.md hierarchy: user, project, directory",
 "gist": "~/.claude/CLAUDE.md, .claude/CLAUDE.md or root CLAUDE.md, and subdirectory files all load — they stack, they do not replace each other.",
 "bul": ["3.1-K1", "APP-I9", "APP-T3"], "kd": []},
{"id": "D3-02", "ts": "3.1", "title": "User-level is personal — it never reaches teammates",
 "gist": "Instructions in ~/.claude/CLAUDE.md are not version-controlled; a new teammate not receiving them is the diagnostic.",
 "bul": ["3.1-K2", "3.1-S1", "APP-I9"], "kd": [1]},
{"id": "D3-03", "ts": "3.1", "title": "@import keeps CLAUDE.md modular",
 "gist": "Reference external standards files so each package pulls in only what applies to it.",
 "bul": ["3.1-K3", "3.1-S2", "APP-I9"], "kd": []},
{"id": "D3-04", "ts": "3.1", "title": ".claude/rules/ splits a monolith into topic files",
 "gist": "testing.md, api-conventions.md, deployment.md instead of one long CLAUDE.md.",
 "bul": ["3.1-K4", "3.1-S3", "APP-I9", "APP-T3"], "kd": [3]},
{"id": "D3-05", "ts": "3.1", "title": "/memory shows what actually loaded",
 "gist": "When behaviour differs between sessions, /memory lists the memory files in force.",
 "bul": ["3.1-S4", "APP-T3"], "kd": []},
{"id": "D3-06", "ts": "3.2", "title": "Slash commands: .claude/commands/ ships with the repo, ~/.claude/commands/ is yours",
 "gist": "Project commands are version-controlled and available to everyone who clones; user commands are personal.",
 "bul": ["3.2-K1", "3.2-S1", "APP-I10", "APP-T3"], "kd": []},
{"id": "D3-07", "ts": "3.2", "title": "Skills live in .claude/skills/<name>/SKILL.md with frontmatter",
 "gist": "SKILL.md frontmatter supports context: fork, allowed-tools and argument-hint.",
 "bul": ["3.2-K2", "APP-I10", "APP-T3"], "kd": []},
{"id": "D3-08", "ts": "3.2", "title": "context: fork runs the skill in an isolated sub-agent",
 "gist": "Verbose or exploratory skill output stays out of the main conversation.",
 "bul": ["3.2-K3", "3.2-S2", "APP-I10"], "kd": [13]},
{"id": "D3-09", "ts": "3.2", "title": "allowed-tools restricts what a skill may do",
 "gist": "Frontmatter limits tool access during the skill, e.g. no destructive operations.",
 "bul": ["3.2-S3", "APP-I10"], "kd": []},
{"id": "D3-10", "ts": "3.2", "title": "argument-hint prompts for missing parameters",
 "gist": "When the skill is invoked without arguments, the hint tells the developer what to supply.",
 "bul": ["3.2-S4", "APP-I10"], "kd": []},
{"id": "D3-11", "ts": "3.2", "title": "Personal skill variants without touching the team's",
 "gist": "Create a personal variant in ~/.claude/skills/ under a different name so teammates are unaffected.",
 "bul": ["3.2-K4"], "kd": [4]},
{"id": "D3-12", "ts": "3.2", "title": "Skills are on-demand; CLAUDE.md is always loaded",
 "gist": "Universal standards go in CLAUDE.md; task-specific procedures go in skills invoked when needed.",
 "bul": ["3.2-S5"], "kd": [3]},
{"id": "D3-13", "ts": "3.3", "title": "Path-scoped rules: paths: globs in YAML frontmatter",
 "gist": "A rule with paths: [\"terraform/**/*\"] loads only while editing matching files, saving tokens.",
 "bul": ["3.3-K1", "3.3-K2", "3.3-S1", "3.3-S2", "APP-I9", "APP-T3"], "kd": [3]},
{"id": "D3-14", "ts": "3.3", "title": "Glob rules beat subdirectory CLAUDE.md for conventions spread across the tree",
 "gist": "Test files everywhere → **/*.test.tsx rule, not a CLAUDE.md in each folder.",
 "bul": ["3.3-K3", "3.3-S3"], "kd": [3]},
{"id": "D3-15", "ts": "3.4", "title": "Plan mode for large, ambiguous or architectural work; direct execution for well-scoped fixes",
 "gist": "Plan first for multi-file changes, migrations and design choices; go direct for a single-file fix with a clear stack trace; plan then execute for a migration.",
 "bul": ["3.4-K1", "3.4-K2", "3.4-K3", "3.4-S1", "3.4-S2", "3.4-S4", "APP-I11", "APP-T3"], "kd": []},
{"id": "D3-16", "ts": "3.4", "title": "The Explore subagent keeps discovery noise out of the main context",
 "gist": "Verbose discovery runs in Explore and returns a summary, preserving the main window for multi-phase work.",
 "bul": ["3.4-K4", "3.4-S3", "APP-T3"], "kd": [22]},
{"id": "D3-17", "ts": "3.5", "title": "Two or three concrete input/output examples beat more prose",
 "gist": "When descriptions are read inconsistently, show the transformation.",
 "bul": ["3.5-K1", "3.5-S1", "APP-I12"], "kd": []},
{"id": "D3-18", "ts": "3.5", "title": "Test-driven iteration: write the tests, share the failures",
 "gist": "Write the suite (behaviour, edge cases, performance) first, then iterate by feeding back failures; fix an edge case with a specific input/expected-output test.",
 "bul": ["3.5-K2", "3.5-S2", "3.5-S4", "APP-I12"], "kd": []},
{"id": "D3-19", "ts": "3.5", "title": "The interview pattern",
 "gist": "Have Claude ask questions first so it surfaces cache invalidation, failure modes and other considerations you had not anticipated.",
 "bul": ["3.5-K3", "3.5-S3", "APP-I12"], "kd": []},
{"id": "D3-20", "ts": "3.5", "title": "Interacting issues in one message; independent issues one at a time",
 "gist": "Batch fixes that affect each other; sequence the ones that do not.",
 "bul": ["3.5-K4", "3.5-S5", "APP-I12"], "kd": []},
{"id": "D3-21", "ts": "3.6", "title": "-p / --print runs Claude Code non-interactively",
 "gist": "In CI, -p processes the prompt, prints to stdout and exits; without it the job waits for input.",
 "bul": ["3.6-K1", "3.6-S1", "APP-T4"], "kd": [15]},
{"id": "D3-22", "ts": "3.6", "title": "--output-format json with --json-schema for machine-readable findings",
 "gist": "Structured CI output can be posted as inline PR comments.",
 "bul": ["3.6-K2", "3.6-S2", "APP-T4"], "kd": []},
{"id": "D3-23", "ts": "3.6", "title": "CLAUDE.md is how CI Claude learns your standards, fixtures and criteria",
 "gist": "Document testing standards, valuable-test criteria and available fixtures so generated tests are worth having.",
 "bul": ["3.6-K3", "3.6-S5"], "kd": []},
{"id": "D3-24", "ts": "3.6", "title": "Re-reviews see prior findings; test generation sees existing tests",
 "gist": "Include last run's findings and ask for new or unaddressed issues only; include existing test files to avoid duplicate scenarios.",
 "bul": ["3.6-S3", "3.6-S4"], "kd": []},

# ============================================================ D4 ============================================================
{"id": "D4-01", "ts": "4.1", "title": "Explicit categorical criteria beat vague instructions",
 "gist": "\"Flag a comment only when the claimed behaviour contradicts the code\" works; \"be conservative\" and \"only high-confidence findings\" do not.",
 "bul": ["4.1-K1", "4.1-K2", "4.1-S1"], "kd": []},
{"id": "D4-02", "ts": "4.1", "title": "False positives erode trust — switch off the noisy category while you fix it",
 "gist": "A high-false-positive category undermines confidence in the accurate ones; disable it temporarily.",
 "bul": ["4.1-K3", "4.1-S2", "APP-I14"], "kd": []},
{"id": "D4-03", "ts": "4.1", "title": "Severity levels defined by concrete code examples",
 "gist": "Each level gets example code, so classification is consistent.",
 "bul": ["4.1-S3"], "kd": []},
{"id": "D4-04", "ts": "4.2", "title": "Few-shot examples for consistent format when instructions fail",
 "gist": "Show the exact output shape (location, issue, severity, fix) instead of writing longer instructions.",
 "bul": ["4.2-K1", "4.2-S2", "APP-I14", "APP-T10"], "kd": [16]},
{"id": "D4-05", "ts": "4.2", "title": "Aim examples at the ambiguous cases, with the reasoning",
 "gist": "Two to four targeted examples that show why one action beat the plausible alternative let the model generalise to new patterns.",
 "bul": ["4.2-K2", "4.2-K3", "4.2-S1", "4.2-S3", "APP-I14", "APP-T10"], "kd": [18]},
{"id": "D4-06", "ts": "4.2", "title": "Few-shot for extraction across varied documents",
 "gist": "Examples of inline citations vs bibliographies, methodology sections vs embedded details, reduce hallucination and fix null required fields.",
 "bul": ["4.2-K4", "4.2-S4", "4.2-S5", "APP-T10"], "kd": []},
{"id": "D4-07", "ts": "4.3", "title": "tool_use with a JSON schema is the structured-output guarantee",
 "gist": "Define an extraction tool whose input schema is the output you want and read it from the tool_use block; syntax errors disappear.",
 "bul": ["4.3-K1", "4.3-S1", "APP-I13", "APP-T5", "APP-T7"], "kd": []},
{"id": "D4-08", "ts": "4.3", "title": "tool_choice: auto may answer in text, any must call some tool, forced must call this tool",
 "gist": "any guarantees a tool call when the document type is unknown; {\"type\": \"tool\", \"name\": ...} guarantees a specific extraction runs first.",
 "bul": ["4.3-K2", "4.3-S2", "4.3-S3", "2.3-K4", "2.3-S4", "2.3-S5", "APP-I13", "APP-T5"], "kd": [], "xref": ["2.3"]},
{"id": "D4-09", "ts": "4.3", "title": "Schema-valid is not the same as correct",
 "gist": "Strict schemas remove syntax errors; line items that do not sum and values in the wrong field are semantic errors that survive.",
 "bul": ["4.3-K3", "4.4-K4", "APP-T7", "APP-T8"], "kd": []},
{"id": "D4-10", "ts": "4.3", "title": "Nullable fields stop fabrication",
 "gist": "Mark fields optional when the source may lack them; a required field forces an invented value.",
 "bul": ["4.3-K4", "4.3-S4", "APP-I13", "APP-T7"], "kd": []},
{"id": "D4-11", "ts": "4.3", "title": "Enums with \"unclear\" and \"other\" + detail",
 "gist": "Ambiguous cases get an unclear value; extensible categories get other plus a free-text detail field.",
 "bul": ["4.3-K4", "4.3-S5", "APP-T7"], "kd": []},
{"id": "D4-12", "ts": "4.3", "title": "Normalisation rules travel with the schema",
 "gist": "Tell the prompt how to normalise inconsistent source formats alongside the strict output schema.",
 "bul": ["4.3-S6"], "kd": []},
{"id": "D4-13", "ts": "4.4", "title": "Retry with the specific validation error",
 "gist": "Send the original document, the failed extraction and the exact error; the model corrects format and structure faults.",
 "bul": ["4.4-K1", "4.4-S1", "APP-T8"], "kd": []},
{"id": "D4-14", "ts": "4.4", "title": "Retry cannot create information that is not in the source",
 "gist": "Format mismatches retry well; a value that exists only in a document you did not provide will fail every time.",
 "bul": ["4.4-K2", "4.4-S2"], "kd": []},
{"id": "D4-15", "ts": "4.4", "title": "detected_pattern turns dismissals into a feedback loop",
 "gist": "Record which code construct triggered each finding so dismissed findings can be analysed for false-positive patterns.",
 "bul": ["4.4-K3", "4.4-S3"], "kd": []},
{"id": "D4-16", "ts": "4.4", "title": "Self-checking schema: calculated_total beside stated_total, conflict_detected",
 "gist": "Extract both numbers so discrepancies flag themselves; add a boolean for inconsistent source data.",
 "bul": ["4.4-S4"], "kd": []},
{"id": "D4-17", "ts": "4.5", "title": "Message Batches API: 50% cheaper, up to 24 hours, no latency SLA",
 "gist": "Batch fits overnight reports and weekly audits; blocking pre-merge checks stay synchronous.",
 "bul": ["4.5-K1", "4.5-K2", "4.5-S1", "APP-I15", "APP-T6"], "kd": [14]},
{"id": "D4-18", "ts": "4.5", "title": "A batch request cannot run a tool loop mid-request",
 "gist": "Batches are fire-and-forget; anything that needs tool results returned mid-request stays synchronous.",
 "bul": ["4.5-K3", "APP-T6"], "kd": [14]},
{"id": "D4-19", "ts": "4.5", "title": "custom_id correlates results and lets you resubmit only the failures",
 "gist": "Identify failed documents by custom_id and resubmit them, chunking the ones that exceeded context.",
 "bul": ["4.5-K4", "4.5-S3", "APP-I15", "APP-T6"], "kd": []},
{"id": "D4-20", "ts": "4.5", "title": "Submission cadence from the SLA arithmetic",
 "gist": "A 30-hour SLA with a 24-hour batch window means submitting every 4 hours or so.",
 "bul": ["4.5-S2", "APP-I15"], "kd": []},
{"id": "D4-21", "ts": "4.5", "title": "Refine the prompt on a sample before the big batch",
 "gist": "Tune on a small set first so first-pass success is high and resubmission cost low.",
 "bul": ["4.5-S4"], "kd": []},
{"id": "D4-22", "ts": "4.6", "title": "An independent instance reviews; the author does not",
 "gist": "The session that wrote the code keeps its reasoning and will not question it; a second instance without that context catches more than self-review or extended thinking.",
 "bul": ["4.6-K1", "4.6-K2", "4.6-S1", "3.6-K4"], "kd": [], "xref": ["3.6"]},
{"id": "D4-23", "ts": "4.6", "title": "Per-file passes plus a cross-file integration pass",
 "gist": "A 14-file single pass dilutes attention and contradicts itself; split into local passes and one integration pass — a bigger context window does not fix it.",
 "bul": ["4.6-K3", "4.6-S2", "1.6-K2", "1.6-S2", "APP-T11"], "kd": [17], "xref": ["1.6"]},
{"id": "D4-24", "ts": "4.6", "title": "Confidence beside each finding routes the review",
 "gist": "Have the model self-report confidence per finding so low-confidence items get human attention.",
 "bul": ["4.6-S3"], "kd": []},

# ============================================================ D5 ============================================================
{"id": "D5-01", "ts": "5.1", "title": "Summaries blur numbers — keep a case-facts block outside the history",
 "gist": "Amounts, dates, order numbers and statuses go into a persistent structured block included in every prompt; summarised history loses them.",
 "bul": ["5.1-K1", "5.1-S1", "5.1-S2", "APP-I16", "APP-T12"], "kd": [21]},
{"id": "D5-02", "ts": "5.1", "title": "Lost in the middle — summary first, explicit section headers",
 "gist": "Models read the start and end of long input reliably; put key findings at the top and label the sections.",
 "bul": ["5.1-K2", "5.1-S4", "APP-I16", "APP-T12"], "kd": [20]},
{"id": "D5-03", "ts": "5.1", "title": "Trim tool output before it lands in context",
 "gist": "Forty fields per order lookup when five matter; keep only the relevant fields.",
 "bul": ["5.1-K3", "5.1-S3", "APP-I16", "APP-T12"], "kd": []},
{"id": "D5-04", "ts": "5.1", "title": "The API is stateless — send the full history every turn",
 "gist": "Claude remembers nothing between requests; coherence comes from the messages array you send.",
 "bul": ["5.1-K4"], "kd": [25]},
{"id": "D5-05", "ts": "5.1", "title": "Subagents return structured, metadata-rich output — not prose",
 "gist": "Key facts, citations, dates, relevance scores instead of verbose reasoning, so downstream agents with small budgets can synthesise accurately.",
 "bul": ["5.1-S5", "5.1-S6"], "kd": []},
{"id": "D5-06", "ts": "5.1", "title": "Behavioural drift is diluted instructions, not overflow",
 "gist": "At 2,500 tokens the window is not full; the system prompt's influence is being diluted by accumulated responses.",
 "bul": [], "kd": [23], "note": "Practice-test distinction adjacent to TS 5.1."},
{"id": "D5-07", "ts": "5.1", "title": "Months of history need retrieval, not summarisation",
 "gist": "Specific recall over 85K tokens of past conversation calls for semantic retrieval; progressive summarisation compresses conclusions into abstractions.",
 "bul": [], "kd": [24], "note": "Practice-test distinction adjacent to TS 5.1."},
{"id": "D5-08", "ts": "5.2", "title": "Escalation triggers: human requested, policy gap, no progress",
 "gist": "Escalate when the customer asks for a human, when policy is silent or ambiguous, or when the agent cannot progress — not merely when the case is complex.",
 "bul": ["5.2-K1", "5.2-S4", "APP-I8"], "kd": []},
{"id": "D5-09", "ts": "5.2", "title": "Explicit criteria plus few-shot; never sentiment or self-confidence",
 "gist": "Escalation calibration comes from written criteria with examples; sentiment scores and self-reported confidence do not track case complexity.",
 "bul": ["5.2-K3", "5.2-S1", "APP-I8"], "kd": []},
{"id": "D5-10", "ts": "5.2", "title": "Asked for a human: escalate now. Frustrated: acknowledge and offer",
 "gist": "An explicit request is honoured immediately without investigation; frustration on a solvable issue gets acknowledgement plus an offer, escalating only if the customer insists.",
 "bul": ["5.2-K2", "5.2-S2", "5.2-S3", "APP-I8"], "kd": []},
{"id": "D5-11", "ts": "5.2", "title": "Two customer matches — ask for one more identifier",
 "gist": "Never pick a match by heuristic; request an additional identifier.",
 "bul": ["5.2-K4", "5.2-S5"], "kd": []},
{"id": "D5-12", "ts": "5.2", "title": "State reasonable assumptions and proceed; do not fire off four questions",
 "gist": "For a vague request, proceed with stated assumptions and invite correction; a wall of clarifying questions drives abandonment, and silent defaults confuse.",
 "bul": [], "kd": [19], "note": "Practice-test distinction adjacent to TS 5.2 (ambiguity resolution)."},
{"id": "D5-13", "ts": "5.3", "title": "Structured error context lets the coordinator recover",
 "gist": "Failure type, attempted query, partial results and alternatives; a generic \"search unavailable\", a silent empty success, or killing the whole workflow are all anti-patterns.",
 "bul": ["5.3-K1", "5.3-K3", "5.3-K4", "5.3-S1", "APP-I7"], "kd": [8]},
{"id": "D5-14", "ts": "5.3", "title": "Access failure is not an empty result",
 "gist": "A timeout needs a retry decision; zero matches is a successful query — report them differently.",
 "bul": ["5.3-K2", "5.3-S2", "2.2-S4"], "kd": [9], "xref": ["2.2"]},
{"id": "D5-15", "ts": "5.3", "title": "Recover locally first; propagate only what you could not fix, with what you tried",
 "gist": "Subagents retry transient failures themselves and escalate the rest with partial results and the attempts made.",
 "bul": ["5.3-S3", "2.2-S3", "APP-I7"], "kd": [], "xref": ["2.2"]},
{"id": "D5-16", "ts": "5.3", "title": "Coverage annotations in the synthesis",
 "gist": "Mark which findings are well supported and which topic areas have gaps because a source was unavailable.",
 "bul": ["5.3-S4", "APP-I18"], "kd": []},
{"id": "D5-17", "ts": "5.4", "title": "Context degradation in long sessions",
 "gist": "The model starts giving inconsistent answers and citing \"typical patterns\" instead of the classes it found earlier.",
 "bul": ["5.4-K1"], "kd": []},
{"id": "D5-18", "ts": "5.4", "title": "Scratchpad files persist findings across context boundaries",
 "gist": "Agents write key findings to a file and read it back for later questions.",
 "bul": ["5.4-K2", "5.4-S2", "APP-T12"], "kd": []},
{"id": "D5-19", "ts": "5.4", "title": "Delegate verbose exploration; the main agent keeps the high-level picture",
 "gist": "Spawn subagents for \"find all test files\" or \"trace the refund flow\" while the main agent coordinates.",
 "bul": ["5.4-K3", "5.4-S1"], "kd": [22]},
{"id": "D5-20", "ts": "5.4", "title": "Summarise a phase before spawning the next",
 "gist": "Inject the previous phase's key findings into the next phase's initial context.",
 "bul": ["5.4-S3"], "kd": []},
{"id": "D5-21", "ts": "5.4", "title": "Crash recovery: state exports plus a manifest",
 "gist": "Each agent writes state to a known location; on resume the coordinator loads the manifest and injects it into prompts.",
 "bul": ["5.4-K4", "5.4-S4", "APP-I3"], "kd": []},
{"id": "D5-22", "ts": "5.4", "title": "/compact when discovery output fills the window",
 "gist": "Reduce context usage mid-session; note that compaction loses precision, so isolate discovery first where you can.",
 "bul": ["5.4-S5", "APP-T3"], "kd": [22]},
{"id": "D5-23", "ts": "5.5", "title": "97% overall can hide a bad segment — measure by document type and field",
 "gist": "Aggregate accuracy masks weak document types or fields; verify every segment before automating high-confidence extractions.",
 "bul": ["5.5-K1", "5.5-K4", "5.5-S2", "APP-I17"], "kd": []},
{"id": "D5-24", "ts": "5.5", "title": "Stratified random sampling of high-confidence output",
 "gist": "Keep sampling the confident extractions to measure error rate and catch novel patterns.",
 "bul": ["5.5-K2", "5.5-S1", "APP-I17", "APP-T14"], "kd": []},
{"id": "D5-25", "ts": "5.5", "title": "Field-level confidence, calibrated on labeled data, routes to human review",
 "gist": "Have the model output confidence per field, calibrate thresholds on a labeled set, and send low-confidence or contradictory cases to reviewers.",
 "bul": ["5.5-K3", "5.5-S3", "5.5-S4", "APP-I17", "APP-T14"], "kd": []},
{"id": "D5-26", "ts": "5.6", "title": "Claim-source mappings survive synthesis",
 "gist": "Subagents output claim, excerpt, source URL/document; the synthesis agent preserves and merges the mapping instead of compressing it away.",
 "bul": ["5.6-K1", "5.6-K2", "5.6-S1", "APP-I18"], "kd": []},
{"id": "D5-27", "ts": "5.6", "title": "Conflicting figures: keep both, attribute both, let the coordinator reconcile",
 "gist": "Do not pick a value; annotate the conflict with sources.",
 "bul": ["5.6-K3", "5.6-S3", "APP-I18"], "kd": []},
{"id": "D5-28", "ts": "5.6", "title": "Well-established vs contested findings in separate sections",
 "gist": "Keep the sources' own characterisations and methodological context.",
 "bul": ["5.6-S2"], "kd": []},
{"id": "D5-29", "ts": "5.6", "title": "Dates in every structured output",
 "gist": "Publication or collection dates stop temporal differences being read as contradictions.",
 "bul": ["5.6-K4", "5.6-S4", "APP-I18"], "kd": []},
{"id": "D5-30", "ts": "5.6", "title": "Render each content type in its natural form",
 "gist": "Financial data as tables, news as prose, technical findings as lists.",
 "bul": ["5.6-S5"], "kd": []},

# ============================================================ META ============================================================
{"id": "M-01", "ts": "meta", "title": "The exam at a glance",
 "gist": "60 questions, 120 minutes, single-answer multiple choice (1 correct + 3 distractors), 4 scenarios drawn from a bank of 6, scaled 100–1,000 with 720 to pass, every question must be answered.",
 "bul": [], "kd": []},
{"id": "M-02", "ts": "meta", "title": "Five domains and their weights",
 "gist": "D1 27%, D2 18%, D3 20%, D4 20%, D5 15%.",
 "bul": [], "kd": []},
{"id": "M-03", "ts": "meta", "title": "The six scenarios and their primary domains",
 "gist": "Customer Support (D1 D2 D5), Code Generation (D3 D5), Multi-Agent Research (D1 D2 D5), Developer Productivity (D2 D3 D1), CI (D3 D4), Structured Data Extraction (D4 D5).",
 "bul": [], "kd": []},
{"id": "M-04", "ts": "meta", "title": "The tie-breakers the sample answers reward",
 "gist": "Root cause over symptom; proportionate first response; code for guarantees, prompts for guidance; least privilege; structured over generic; match the API to the latency; independence for review.",
 "bul": [], "kd": []},
{"id": "M-05", "ts": "meta", "title": "Will not appear",
 "gist": "The sixteen out-of-scope topics.",
 "bul": ["APP-O%d" % i for i in range(1, 17)], "kd": []},
]
