# Domain 4 — Prompt Engineering & Structured Output · building: the courthouse
# Generated by merge_parts.py from the authoring halves — edit the halves, not this file.

ITEMS = [
{
 'id': 'D4-01',
 'title': 'Explicit categorical criteria beat vague instructions',
 'concept': 'Precision comes from explicit categorical criteria — which issues to report and which to skip — not from general instructions like "be conservative" or "only report high-confidence findings".',
 'tested': 'The review flags accurate comments as problems, and the question asks the most effective prompt change. The answer replaces the vague intent with a testable rule — flag a comment only when the behaviour it claims contradicts the code — and names which categories to report and which to skip. Distractors restate the same vague intent in stronger words, or filter by a self-reported confidence threshold, neither of which changes what the model counts as a finding.',
 'remember': 'Vague adjectives do not raise precision. Write the categorical rule: report bugs and security, skip minor style and local patterns. A confidence threshold is the distractor.',
 'alt': 'Statute sheet with three ticked criteria; a vague sheet crossed out',
 'analogy': 'A statute lists the elements of the offence, and the judge convicts only when every element is met. A direction to the bench to be reasonable, or to convict only when sure, decides no case differently, because it never says which facts count.',
 "svg": """<rect class="paper" x="16" y="18" width="72" height="84" rx="3"/>
<rect class="acc" x="26" y="32" width="10" height="10"/><line class="acc" x1="44" y1="37" x2="78" y2="37"/>
<rect class="acc" x="26" y="52" width="10" height="10"/><line class="acc" x1="44" y1="57" x2="78" y2="57"/>
<rect class="acc" x="26" y="72" width="10" height="10"/><line class="acc" x1="44" y1="77" x2="78" y2="77"/>
<text class="lbl" x="123" y="30" text-anchor="middle">vague</text>
<rect class="tint" x="102" y="38" width="42" height="44" rx="3"/>
<line class="dash thin" x1="110" y1="54" x2="136" y2="54"/>
<line class="dash thin" x1="110" y1="66" x2="128" y2="66"/>
<line class="no" x1="106" y1="42" x2="140" y2="78"/>
<line class="no" x1="140" y1="42" x2="106" y2="78"/>""",
},
{
 'id': 'D4-02',
 'title': 'False positives erode trust — disable the noisy category',
 'concept': 'A category with a high false-positive rate makes developers dismiss findings from the accurate categories too, so that category is switched off while its prompt is improved.',
 'tested': 'Per-category false-positive rates are given, style and documentation high against security and performance low, developers dismiss every finding, and the question asks how to restore trust. The answer temporarily disables the noisy categories and keeps the precise ones running while their prompts are rewritten. Distractors attach a confidence score to every finding and still show them all, cut strictness uniformly across categories, or work through examples for every category over several weeks.',
 'remember': 'A high false-positive category discredits the accurate ones. Turn it off now, fix its prompt, turn it back on. Confidence displays and uniform strictness cuts are the distractors.',
 'alt': 'Docket with the noisy category struck out; the precise one stamped',
 'analogy': 'One list of charges the court throws out week after week teaches the public that the whole docket is worthless, and the sound convictions on the next list are read as noise. The court suspends that list until it is drafted properly and keeps hearing the ones that stand up.',
 "svg": """<rect class="paper" x="20" y="14" width="76" height="92" rx="3"/>
<line class="thin" x1="30" y1="32" x2="86" y2="32"/>
<line class="thin" x1="30" y1="44" x2="86" y2="44"/>
<line class="no" x1="26" y1="26" x2="90" y2="50"/>
<line class="no" x1="90" y1="26" x2="26" y2="50"/>
<text class="lbl" x="122" y="44" text-anchor="middle">off</text>
<line class="acc" x1="30" y1="72" x2="86" y2="72"/>
<line class="acc" x1="30" y1="86" x2="86" y2="86"/>
<circle class="acc" cx="122" cy="79" r="19"/>
<circle class="acc thin" cx="122" cy="79" r="13"/>""",
},
{
 'id': 'D4-03',
 'title': 'Severity levels defined by concrete code examples',
 'concept': 'Severity classification stays consistent when each level is defined by explicit criteria with a concrete code example attached, rather than by an instruction to rate severity appropriately.',
 'tested': 'The same class of issue comes back as critical in one run and medium in the next, and the question asks how to make classification consistent. The answer writes explicit criteria per level and attaches a concrete code example to each one. Distractors ask for severity to be rated appropriately, or filter by a confidence score rather than defining the levels.',
 'remember': 'One example of real code per severity level. Definitions plus examples make the boundary testable; an instruction to rate appropriately leaves it to the run.',
 'alt': 'Four severity bands, each paired with a concrete code example',
 'analogy': 'The sentencing grid does not tell the judge to be proportionate; it sets out bands and prints a decided case in each one. Two judges reading the same grid put the same offence in the same band, because they are matching against examples rather than against their own sense of gravity.',
 "svg": """<rect class="tint" x="14" y="16" width="46" height="20" rx="2"/>
<rect class="tint" x="14" y="42" width="46" height="20" rx="2"/>
<rect class="tint" x="14" y="68" width="46" height="20" rx="2"/>
<rect class="tint" x="14" y="94" width="46" height="16" rx="2"/>
<text class="lbl" x="37" y="30" text-anchor="middle">crit</text>
<text class="lbl" x="37" y="56" text-anchor="middle">high</text>
<text class="lbl" x="37" y="82" text-anchor="middle">med</text>
<text class="lbl" x="37" y="106" text-anchor="middle">low</text>
<rect class="acc" x="76" y="16" width="70" height="20" rx="2"/>
<rect class="acc" x="76" y="42" width="70" height="20" rx="2"/>
<rect class="acc" x="76" y="68" width="70" height="20" rx="2"/>
<rect class="acc" x="76" y="94" width="70" height="16" rx="2"/>
<line class="acc thin" x1="84" y1="26" x2="112" y2="26"/>
<line class="acc thin" x1="84" y1="52" x2="118" y2="52"/>
<line class="acc thin" x1="84" y1="78" x2="106" y2="78"/>
<line class="acc thin" x1="84" y1="103" x2="114" y2="103"/>""",
},
{
 'id': 'D4-04',
 'title': 'Few-shot examples for consistent format when instructions fail',
 'concept': 'Few-shot examples showing the exact required shape — location, issue, severity, suggested fix — are the most effective technique when detailed instructions alone produce inconsistent output.',
 'tested': 'The output format varies run to run although the prompt already specifies it, and the question asks the most effective improvement. The answer adds examples demonstrating the exact format. The distractor rewrites the instructions to be longer or more explicit, which adds text to something that is already failing.',
 'remember': 'Format inconsistent despite instructions → show the shape, do not describe it again. More explicit wording is the standing distractor wherever examples are the answer.',
 'alt': 'Two example forms producing three outputs in the same layout',
 'analogy': 'The clerk handed a memo describing how findings should be laid out returns a different layout every week. Two completed forms laid on the desk, as the pattern to follow, end the variation; a longer memo does not.',
 "svg": """<rect class="acc" x="14" y="20" width="34" height="40" rx="2"/>
<line class="acc thin" x1="20" y1="32" x2="42" y2="32"/>
<line class="acc thin" x1="20" y1="44" x2="36" y2="44"/>
<rect class="acc" x="14" y="66" width="34" height="40" rx="2"/>
<line class="acc thin" x1="20" y1="78" x2="42" y2="78"/>
<line class="acc thin" x1="20" y1="90" x2="36" y2="90"/>
<path d="M56 62 h16 M66 56 l6 6 -6 6"/>
<rect class="paper" x="80" y="18" width="30" height="38" rx="2"/>
<line class="thin" x1="86" y1="30" x2="104" y2="30"/><line class="thin" x1="86" y1="42" x2="98" y2="42"/>
<rect class="paper" x="80" y="68" width="30" height="38" rx="2"/>
<line class="thin" x1="86" y1="80" x2="104" y2="80"/><line class="thin" x1="86" y1="92" x2="98" y2="92"/>
<rect class="paper" x="116" y="43" width="30" height="38" rx="2"/>
<line class="thin" x1="122" y1="55" x2="140" y2="55"/><line class="thin" x1="122" y1="67" x2="134" y2="67"/>""",
},
{
 'id': 'D4-05',
 'title': 'Aim examples at the ambiguous cases, with the reasoning',
 'concept': 'Two to four examples aimed at the ambiguous cases, each showing why one action was chosen over a plausible alternative, let the model generalise its judgment to new patterns.',
 'tested': 'Requests that sit between two tools are misrouted, or borderline coverage gaps are missed, and the question asks what to add. The answer is a small set of examples on exactly those borderline cases, each carrying the reasoning for the choice. The distractor supplies ten to fifteen examples of clear, unambiguous requests, which never touch the cases that fail. The same technique reduces false positives in review: examples contrasting acceptable patterns with genuine issues, so judgment generalises instead of matching a fixed list.',
 'remember': 'Target the boundary, not the clear cases, and include the reasoning. Two to four examples with rationale beat a dozen obvious ones; the reasoning is what generalises.',
 'alt': 'Examples clustered on the boundary; a clump far from it crossed out',
 'analogy': 'The precedent binder is filled with the cases that could have gone either way, each recorded with the reasoning the court gave for going one way. A run of straightforward judgments would add pages without helping the bench decide the case in front of it, which is hard because it sits on the line.',
 "svg": """<line class="dash" x1="80" y1="14" x2="80" y2="106"/>
<text class="lbl" x="34" y="24" text-anchor="middle">A</text>
<text class="lbl" x="126" y="24" text-anchor="middle">B</text>
<circle class="accfill" cx="70" cy="44" r="5"/>
<circle class="accfill" cx="90" cy="58" r="5"/>
<circle class="accfill" cx="68" cy="74" r="5"/>
<circle class="accfill" cx="92" cy="88" r="5"/>
<circle class="tint" cx="22" cy="60" r="5"/>
<circle class="tint" cx="34" cy="76" r="5"/>
<circle class="tint" cx="24" cy="92" r="5"/>
<line class="no" x1="16" y1="58" x2="40" y2="94"/>
<line class="no" x1="40" y1="58" x2="16" y2="94"/>""",
},
{
 'id': 'D4-06',
 'title': 'Few-shot for extraction across varied documents',
 'concept': 'Few-shot examples covering varied document structures — inline citations versus bibliographies, methodology sections versus details embedded in prose — reduce hallucination in extraction and stop required fields coming back empty.',
 'tested': '12% of extractions carry a fabricated value in a required field, or the same field returns null whenever the source lays it out differently, and the question asks the fix. The answer adds examples showing correct extraction from each document layout the source set actually contains. Distractors write the extraction instructions out in more detail, or add more examples of the one layout that already works.',
 'remember': 'Varied layouts, and informal wordings such as loose measurements → one worked example per case, showing where the value sits. Examples cut fabrication in extraction; longer instructions do not.',
 'alt': 'Three differently laid-out documents feeding one uniformly filled record',
 'analogy': 'Evidence arrives in whatever form the parties kept it: a source cited in the body of a letter, the same source listed at the back of a report, a method described in a paragraph rather than under a heading. The binder holds one worked example of each form, so the clerk knows where to look instead of leaving the box blank or writing something plausible.',
 "svg": """<rect class="tint" x="12" y="14" width="36" height="26" rx="2"/>
<line class="thin" x1="18" y1="24" x2="42" y2="24"/><line class="thin" x1="18" y1="32" x2="36" y2="32"/>
<rect class="tint" x="12" y="47" width="36" height="26" rx="2"/>
<rect class="thin" x="18" y="53" width="14" height="8"/><line class="thin" x1="18" y1="66" x2="42" y2="66"/>
<rect class="tint" x="12" y="80" width="36" height="26" rx="2"/>
<line class="thin" x1="30" y1="86" x2="30" y2="100"/><line class="thin" x1="18" y1="93" x2="42" y2="93"/>
<line class="acc" x1="52" y1="27" x2="88" y2="52"/>
<line class="acc" x1="52" y1="60" x2="88" y2="60"/>
<line class="acc" x1="52" y1="93" x2="88" y2="68"/>
<rect class="paper" x="92" y="34" width="52" height="52" rx="3"/>
<line class="acc thin" x1="100" y1="50" x2="136" y2="50"/>
<line class="acc thin" x1="100" y1="62" x2="136" y2="62"/>
<line class="acc thin" x1="100" y1="74" x2="124" y2="74"/>""",
},
{
 'id': 'D4-07',
 'title': 'tool_use with a JSON schema is the structured-output guarantee',
 'concept': 'Defining a tool whose input schema is the output structure you want, then reading the data from the `tool_use` block, guarantees schema-compliant output and removes JSON syntax errors.',
 'tested': 'A pipeline must receive parseable JSON on every document, and the question asks how to guarantee it. The answer defines an extraction tool whose input schema is the target structure and reads the `tool_use` block. Distractors ask in the prompt for valid JSON only, which still returns prose preambles and markdown fences, or bolt a JSON repair library onto free-text output, which treats the symptom.',
 'remember': 'The tool need not do anything; its input schema is the contract. `tool_use` removes the syntax class of error, and a prompt asking for JSON does not.',
 'alt': 'Standard form with boxes, stamped; a free-text sheet crossed out',
 'analogy': "The clerk's standard form is the mechanism: a box for each thing the record must contain, and nothing filed that is not on the form. Asking counsel to submit their evidence in a tidy layout produces a different document every time, whereas the form comes back with the boxes filled.",
 "svg": """<rect class="acc" x="42" y="14" width="64" height="90" rx="3"/>
<line class="acc" x1="52" y1="26" x2="96" y2="26"/>
<rect class="thin" x="52" y="36" width="44" height="12" rx="1"/>
<rect class="thin" x="52" y="56" width="44" height="12" rx="1"/>
<rect class="thin" x="52" y="76" width="44" height="12" rx="1"/>
<rect class="tint" x="10" y="34" width="24" height="46" rx="2"/>
<path class="dash thin" d="M15 44 h14 M15 54 h14 M15 64 h10"/>
<line class="no" x1="12" y1="40" x2="32" y2="74"/>
<line class="no" x1="32" y1="40" x2="12" y2="74"/>
<circle class="acc" cx="128" cy="76" r="16"/>
<circle class="acc thin" cx="128" cy="76" r="11"/>""",
},
{
 'id': 'D4-08',
 'title': 'tool_choice: only any and forced guarantee a tool call',
 'concept': '`tool_choice: "auto"` lets the model answer in text instead of calling a tool, `"any"` forces some tool call with the model choosing which, and `{"type": "tool", "name": "..."}` forces that named tool.',
 'tested': 'An extraction pipeline must always receive structured output and the document may be an invoice, a receipt or a contract, each with its own tool; the answer is `tool_choice: "any"`, and where one named extraction must run before the enrichment steps, `{"type": "tool", "name": "extract_metadata"}`. The trap is an option that pairs `auto` with a prompt instruction to always call the tool and offers the pair as a guarantee. `auto` leaves the model free to answer in text, and no instruction in the prompt changes that.',
 'remember': '`auto` = may return text. `any` = must call a tool, model picks which. `{"type": "tool", "name": ...}` = must call that one. A prompt instruction is not a guarantee.',
 'alt': 'auto branches to text or a tool; any and forced always call',
 'analogy': 'The judge can tell the clerk to file if the clerk thinks it appropriate, to file on some form of the clerk\'s choosing, or to file on form twelve. Only the last two produce a filing; under the first the clerk may hand back a note in their own words, and adding "be sure to file" to the direction does not change what was directed.',
 "svg": """<text class="lbl" x="24" y="24" text-anchor="middle">auto</text>
<path class="dash thin" d="M42 20 l16 -6"/>
<path class="dash thin" d="M42 24 l16 6"/>
<rect class="tint" x="62" y="8" width="26" height="14" rx="2"/>
<line class="thin" x1="68" y1="15" x2="82" y2="15"/>
<path class="thin" d="M62 32 q6 -4 11 0 q5 4 11 0"/>
<rect class="tint" x="112" y="10" width="34" height="22" rx="2"/>
<path class="thin" d="M118 21 q5 -3 9 0 q4 3 9 0"/>
<line class="no" x1="114" y1="12" x2="144" y2="30"/>
<line class="no" x1="144" y1="12" x2="114" y2="30"/>
<text class="lbl" x="24" y="64" text-anchor="middle">any</text>
<path class="acc" d="M42 60 h16 M48 55 l6 5 -6 5"/>
<rect class="acc" x="62" y="50" width="26" height="20" rx="2"/>
<rect class="acc" x="94" y="50" width="26" height="20" rx="2"/>
<text class="lbl" x="24" y="104" text-anchor="middle">tool</text>
<path class="acc" d="M42 100 h16 M48 95 l6 5 -6 5"/>
<rect class="acc" x="62" y="90" width="26" height="20" rx="2"/>
<rect class="dash thin" x="94" y="90" width="26" height="20" rx="2"/>""",
},
{
 'id': 'D4-09',
 'title': 'Schema-valid is not the same as correct',
 'concept': 'A strict JSON schema through tool use eliminates syntax errors but not semantic ones: line items that do not sum to the stated total, or values in the wrong field, pass validation.',
 'tested': 'JSON parse failures dropped to zero after the move to `tool_use`, and downstream reconciliation still finds totals that do not match their line items; the question asks what is happening or what to do next. The answer treats this as expected, because the schema removed the syntax class and the remaining failures are semantic and need business-rule checks. Distractors tighten the schema further, which no schema constraint can do for arithmetic, or abandon tool use, which adds the syntax class back on top.',
 'remember': 'Schema compliance is structural. Sums, field placement and category choice are semantic and need validation in code. Zero parse errors is not zero extraction errors.',
 'alt': 'Fully filled form; the circled total does not match the lines',
 'analogy': "Every box on the clerk's form is filled in, legibly and in the right place, and the figures still do not add up to the total written at the foot. The form was checked for completeness, which is a different question from whether the record is true.",
 "svg": """<rect class="paper" x="34" y="12" width="92" height="96" rx="3"/>
<path class="thin" d="M44 20 l4 4 7 -8"/>
<line class="thin" x1="44" y1="32" x2="86" y2="32"/>
<text class="lbl" x="110" y="36" text-anchor="middle">40</text>
<line class="thin" x1="44" y1="50" x2="86" y2="50"/>
<text class="lbl" x="110" y="54" text-anchor="middle">55</text>
<line class="thin" x1="44" y1="68" x2="86" y2="68"/>
<text class="lbl" x="110" y="72" text-anchor="middle">50</text>
<line x1="44" y1="80" x2="118" y2="80"/>
<line class="acc" x1="44" y1="97" x2="86" y2="97"/>
<text class="lbl" x="110" y="101" text-anchor="middle">150</text>
<circle class="acc" cx="110" cy="97" r="12"/>""",
},
{
 'id': 'D4-10',
 'title': 'Nullable fields stop fabrication',
 'concept': 'Fields whose information may be absent from the source are marked optional or nullable, because a required non-nullable field pushes the model to invent a value to satisfy the schema.',
 'tested': 'Extractions come back with a plausible but fabricated value in a required field that the source document never contained, and the question asks the schema change. The answer takes the field out of `required` and allows null, so the model can return `null` instead. The distractor makes every field required so that output is always complete, which buys completeness with fabrication.',
 'remember': 'Required means always present in the source, not always wanted in the output. A field that may be missing is nullable, and `null` is a real answer.',
 'alt': 'Required box holding an invented figure, crossed out; nullable box returns null',
 'analogy': 'A box on the form marked as mandatory has to be filled before the form can be filed, so a clerk with nothing to put in it writes something. Marking the box as one that may be left blank is what makes an empty box an honest answer rather than a rejected form.',
 "svg": """<rect class="tint" x="12" y="16" width="60" height="88" rx="3"/>
<line class="thin" x1="20" y1="34" x2="64" y2="34"/>
<rect class="thin" x="20" y="46" width="44" height="16" rx="1"/>
<text class="lbl" x="42" y="58" text-anchor="middle">1234</text>
<line class="thin" x1="20" y1="80" x2="64" y2="80"/>
<line class="no" x1="16" y1="42" x2="68" y2="66"/>
<line class="no" x1="68" y1="42" x2="16" y2="66"/>
<rect class="tint" x="88" y="16" width="60" height="88" rx="3"/>
<line class="thin" x1="96" y1="34" x2="140" y2="34"/>
<rect class="acc dash" x="96" y="46" width="44" height="16" rx="1"/>
<text class="lbl" x="118" y="58" text-anchor="middle">null</text>
<line class="thin" x1="96" y1="80" x2="140" y2="80"/>""",
},
{
 'id': 'D4-11',
 'title': 'Enum values: unclear for ambiguity, other plus detail',
 'concept': 'An enum gets an `"unclear"` value so ambiguous cases are recorded as ambiguous, and an `"other"` value with a companion detail string so a category outside the list can still be captured.',
 'tested': 'A category field has to cope with documents the model cannot confidently place, and with values that fall outside the list the schema was written against; the question asks the schema change. The answer adds `"unclear"` to the enum for the first and `"other"` with a detail string for the second, against a distractor that has the model pick from the fixed list anyway, which records a confident wrong category.',
 'remember': '`"unclear"` for cannot-tell, `"other"` plus a detail string for outside-the-list. An honest `"unclear"` beats a confident wrong category.',
 'alt': 'Enum list with other linked to a detail box and an unclear row',
 'analogy': "The clerk's form offers a fixed list of pleas, plus a line for a case that fits none of them and a blank to say what it was. There is also a box for cases the clerk cannot classify from the papers in front of them, recorded as such instead of being pushed into the nearest heading.",
 "svg": """<rect class="paper" x="16" y="12" width="76" height="96" rx="3"/>
<circle class="thin" cx="28" cy="30" r="4"/><line class="thin" x1="38" y1="30" x2="82" y2="30"/>
<circle class="thin" cx="28" cy="50" r="4"/><line class="thin" x1="38" y1="50" x2="82" y2="50"/>
<circle class="accfill" cx="28" cy="72" r="4"/>
<text class="lbl" x="60" y="76" text-anchor="middle">other</text>
<circle class="accfill" cx="28" cy="94" r="4"/>
<text class="lbl" x="58" y="98" text-anchor="middle">?</text>
<path class="acc" d="M96 72 h14 M104 67 l6 5 -6 5"/>
<rect class="acc dash" x="112" y="60" width="36" height="24" rx="2"/>
<line class="acc thin" x1="118" y1="72" x2="142" y2="72"/>""",
},
{
 'id': 'D4-12',
 'title': 'Normalisation rules travel with the schema',
 'concept': 'Format normalisation rules go in the prompt alongside the strict output schema, because the schema fixes the shape of the output while the prompt governs how inconsistent source formats map into it.',
 'tested': "Source documents write dates and currencies differently, and the extracted values arrive in whatever form the document used even though the schema validates; the question asks what to add. The answer states the normalisation rules in the prompt beside the schema. The distractor tightens the schema, which can constrain a field's type but cannot decide how a messy input is rewritten into it.",
 'remember': 'Schema = shape. Prompt = how messy inputs become that shape. Inconsistent source formatting is a prompt instruction, not a schema constraint.',
 'alt': 'Three date formats passing through a rules note into one schema box',
 'analogy': 'The form has a box for the date of the offence, and the statements in the file write it a dozen ways. The direction to the clerk says which way to render it in the box; the box itself only says that a date belongs there.',
 "svg": """<rect class="tint" x="12" y="14" width="40" height="18" rx="2"/>
<text class="lbl" x="32" y="27" text-anchor="middle">3/4</text>
<rect class="tint" x="12" y="48" width="40" height="18" rx="2"/>
<text class="lbl" x="32" y="61" text-anchor="middle">4 Mar</text>
<rect class="tint" x="12" y="82" width="40" height="18" rx="2"/>
<text class="lbl" x="32" y="95" text-anchor="middle">03-04</text>
<line class="thin" x1="52" y1="23" x2="62" y2="45"/>
<line class="thin" x1="52" y1="57" x2="62" y2="60"/>
<line class="thin" x1="52" y1="91" x2="62" y2="75"/>
<rect class="acc" x="62" y="34" width="34" height="52" rx="3"/>
<line class="acc thin" x1="68" y1="48" x2="90" y2="48"/>
<line class="acc thin" x1="68" y1="60" x2="90" y2="60"/>
<line class="acc thin" x1="68" y1="72" x2="90" y2="72"/>
<path d="M100 60 h12 M108 55 l6 5 -6 5"/>
<rect class="paper" x="116" y="44" width="32" height="32" rx="2"/>
<rect class="thin" x="122" y="54" width="20" height="12" rx="1"/>""",
},
{
 'id': 'D4-13',
 'title': 'Retry with the specific validation error',
 'concept': 'A retry that includes the original document, the failed extraction and the exact validation error gives the model the material it needs to correct format and structural faults.',
 'tested': 'Validation fails on a share of extracted documents and the question asks how the retry should be built. The answer sends three things back together — the original document, the previous extraction, and the specific error text, such as a total that does not match the sum of the line items. Distractors resend the document with a bare instruction to try again, or raise the retry ceiling, neither of which carries a correction signal.',
 'remember': 'Retry payload = original document + failed extraction + the exact error. A retry with no error text gives the model nothing to act on.',
 'alt': 'Failed form plus the exact error bundled into one retry request',
 'analogy': 'An appeal is remitted with the grounds written into the order: which finding is unsupported, and on what point the court below must rule again. The file goes down with the earlier judgment and the ground attached to it, which is what makes the second hearing different from the first.',
 "svg": """<rect class="paper" x="14" y="26" width="46" height="64" rx="3"/>
<line class="thin" x1="22" y1="40" x2="52" y2="40"/>
<line class="thin" x1="22" y1="52" x2="52" y2="52"/>
<line class="thin" x1="22" y1="64" x2="52" y2="64"/>
<line class="no" x1="26" y1="58" x2="38" y2="70"/>
<line class="no" x1="38" y1="58" x2="26" y2="70"/>
<path class="acc" d="M66 58 h18 M78 52 l6 6 -6 6"/>
<rect class="tint" x="92" y="22" width="52" height="20" rx="3"/>
<rect class="tint" x="92" y="48" width="52" height="20" rx="3"/>
<rect class="acc" x="92" y="74" width="52" height="20" rx="3"/>
<text class="lbl" x="118" y="36" text-anchor="middle">doc</text>
<text class="lbl" x="118" y="62" text-anchor="middle">fail</text>
<text class="lbl" x="118" y="88" text-anchor="middle">err</text>""",
},
{
 'id': 'D4-14',
 'title': 'Retry cannot supply information the source lacks',
 'concept': 'Retries correct format and structural errors, and no number of them extracts a value that the source document does not contain.',
 'tested': 'A required field fails validation on a set of documents and investigation shows those documents never carried that value; the question asks what to change. The answer makes the field nullable and treats absence as a legitimate result. Distractors raise the retry limit, sharpen the wording of the retry feedback, or keep the field required for data quality, which pressures the model into fabricating a value.',
 'remember': 'Sort the failure first: format and structure retry well, absent information never appears. Absent means a nullable field, not a higher retry ceiling.',
 'alt': 'Document with an empty nullable field; the retry loop crossed out',
 'analogy': 'The appeals bench can order a point to be heard again, and it cannot rule on evidence that was never entered in the record. A file sent back a second and a third time returns the same finding when the document was never filed.',
 "svg": """<rect class="paper" x="16" y="24" width="56" height="72" rx="3"/>
<line class="thin" x1="26" y1="40" x2="62" y2="40"/>
<line class="thin" x1="26" y1="52" x2="62" y2="52"/>
<rect class="acc dash" x="26" y="62" width="40" height="18" rx="2"/>
<text class="lbl" x="46" y="75" text-anchor="middle">null</text>
<circle cx="112" cy="60" r="24"/>
<polygon points="112,36 118,46 106,46"/>
<line class="no" x1="98" y1="46" x2="126" y2="74"/>
<line class="no" x1="126" y1="46" x2="98" y2="74"/>""",
},
{
 'id': 'D4-15',
 'title': 'detected_pattern turns dismissals into a feedback loop',
 'concept': 'A `detected_pattern` field on each structured finding records which code construct triggered it, so dismissed findings can be grouped and analysed by pattern.',
 'tested': 'Developers dismiss a large share of review findings and the team cannot tell which finding types are noise; the question asks what to add. The answer puts a `detected_pattern` field on every finding so dismissal rates can be read per pattern. The distractor collects a free-text reason on each dismissal, which does not aggregate into anything actionable.',
 'remember': '`detected_pattern` names the construct that fired. Group dismissals by it and the noisy category identifies itself; free-text reasons do not aggregate.',
 'alt': 'Findings tagged by pattern, sorted into per-pattern dismissal bars',
 'analogy': 'Every finding leaves the bench stamped with the ground it was brought under. When the clerk sorts the dismissed files months later, the stamps show which ground keeps failing rather than a shelf of unlike cases.',
 "svg": """<rect class="paper" x="14" y="22" width="32" height="20" rx="2"/>
<text class="lbl" x="30" y="36" text-anchor="middle">P1</text>
<rect class="paper" x="14" y="48" width="32" height="20" rx="2"/>
<text class="lbl" x="30" y="62" text-anchor="middle">P2</text>
<rect class="paper" x="14" y="74" width="32" height="20" rx="2"/>
<text class="lbl" x="30" y="88" text-anchor="middle">P1</text>
<path d="M54 58 h16 M64 52 l6 6 -6 6"/>
<line x1="80" y1="92" x2="148" y2="92"/>
<rect class="acc" x="88" y="34" width="20" height="58"/>
<rect class="tint" x="118" y="70" width="20" height="22"/>
<text class="lbl" x="98" y="106" text-anchor="middle">P1</text>
<text class="lbl" x="128" y="106" text-anchor="middle">P2</text>""",
},
{
 'id': 'D4-16',
 'title': 'Self-checking schema: calculated_total beside stated_total',
 'concept': 'Extracting `calculated_total` alongside `stated_total` with a `conflict_detected` boolean makes a discrepancy surface as data at extraction time rather than at reconciliation.',
 'tested': 'An invoice pipeline reports totals that do not match their line items, discovered weeks later in reconciliation; the question asks how to catch it at extraction. The answer re-derives the total inside the schema and flags disagreement with a boolean. Distractors add a monthly reconciliation report, which keeps the delay, or a prompt instruction to be careful with totals, which builds no detection mechanism.',
 'remember': 'Extract the claimed value and an independently derived value, plus a boolean for disagreement. The check belongs in the schema, not in an instruction.',
 'alt': 'Form holding stated and calculated totals with a conflict box ticked',
 'analogy': "The clerk's form asks for the figure twice: as written on the exhibit, and as the clerk adds it up from the items listed. A third box records that the two disagree, so the disagreement travels with the file instead of surfacing at the year-end audit.",
 "svg": """<rect class="paper" x="14" y="24" width="132" height="72" rx="3"/>
<rect class="thin" x="24" y="36" width="46" height="20" rx="2"/>
<text class="lbl" x="47" y="50" text-anchor="middle">150</text>
<rect class="thin" x="90" y="36" width="46" height="20" rx="2"/>
<text class="lbl" x="113" y="50" text-anchor="middle">145</text>
<path class="acc" d="M74 42 h12 M74 50 h12"/>
<line class="acc" x1="86" y1="38" x2="74" y2="54"/>
<rect class="acc" x="24" y="66" width="16" height="16" rx="2"/>
<path class="acc" d="M27 74 l4 5 l8 -10"/>
<line class="thin" x1="48" y1="76" x2="120" y2="76"/>""",
},
{
 'id': 'D4-17',
 'title': 'Batches API: 50% cheaper, up to 24 hours',
 'concept': 'The Message Batches API costs 50% less than synchronous calls, with a processing window of up to 24 hours and no guaranteed latency SLA.',
 'tested': 'Two workflows run on real-time calls — a blocking pre-merge check and a technical-debt report generated overnight — and a manager proposes moving both to the Batches API for the 50% saving. The answer batches the overnight report and leaves the pre-merge check synchronous, because developers wait on it. Distractors move both with status polling, keep both synchronous over a result-ordering worry that `custom_id` already answers, or add a timeout fallback to real time.',
 'remember': '50% cheaper, up to 24 hours, no latency SLA. Someone is blocked waiting → synchronous. Needed by morning or next week → batch.',
 'alt': 'Clock sweeping 24h marked 50%, with a waiting person crossed out',
 'analogy': 'The night docket costs half as much and usually clears by morning, though the court promises no hour. A matter where the parties are standing in the corridor waiting for the order stays on the day list at full price.',
 "svg": """<circle class="paper" cx="60" cy="58" r="30"/>
<path class="acc" d="M60 58 V28 A30 30 0 1 1 34 73 Z"/>
<path d="M60 58 V36 M60 58 L76 66"/>
<text class="lbl" x="60" y="20" text-anchor="middle">50%</text>
<text class="lbl" x="60" y="102" text-anchor="middle">24h</text>
<circle cx="124" cy="44" r="8"/>
<path d="M124 52 v18 M114 60 h20"/>
<line class="no" x1="112" y1="40" x2="136" y2="72"/>
<line class="no" x1="136" y1="40" x2="112" y2="72"/>""",
},
{
 'id': 'D4-18',
 'title': 'A batch request cannot run a tool loop mid-request',
 'concept': 'The Batches API does not support multi-turn tool calling inside a single request: it cannot execute a tool mid-request and return the result to the model.',
 'tested': 'A workload tolerates delay, but its review fetches related files through tool calls as it goes, and the question asks whether it can move to batch for the saving. The answer keeps it synchronous, because a batch request is one submission and one response. The distractor reads the 50% saving and the tolerance for delay as sufficient and overlooks the tool loop.',
 'remember': 'One submission, one response per request, and you poll for completion. Work that needs a tool result returned mid-request stays synchronous however patient it is.',
 'alt': 'One request in, one response out; the mid-request tool loop crossed out',
 'analogy': 'A matter placed on the night docket is decided on the papers as filed. If the judge would need to call for a further document, hear the answer and carry on the same night, the matter belongs on the day list.',
 "svg": """<rect class="tint" x="54" y="46" width="52" height="34" rx="4"/>
<path class="acc" d="M16 63 h30 M40 57 l6 6 -6 6"/>
<path class="acc" d="M114 63 h30 M138 57 l6 6 -6 6"/>
<rect class="dash" x="60" y="14" width="40" height="20" rx="3"/>
<text class="lbl" x="80" y="29" text-anchor="middle">tool</text>
<path class="dash thin" d="M68 46 V36"/>
<path class="dash thin" d="M92 36 V46"/>
<line class="no" x1="70" y1="34" x2="90" y2="48"/>
<line class="no" x1="90" y1="34" x2="70" y2="48"/>""",
},
{
 'id': 'D4-19',
 'title': 'custom_id correlates results; resubmit only the failures',
 'concept': '`custom_id` is the field that joins a batch request to its response, which is how failed items are identified and resubmitted with a fix such as chunking.',
 'tested': 'A batch returns mostly successes with a few failures, some of which exceeded the context limit, and the question asks what to resubmit. The answer resubmits only the failed items, found by `custom_id`, chunked so they fit. Distractors resubmit the whole batch, resubmit the failures unchanged, or avoid batch altogether over result ordering, which `custom_id` already handles.',
 'remember': '`custom_id` is the join key; arrival order is not. Resubmit only what failed, and change what made it fail.',
 'alt': 'Stamped request and stamped result; matching by position crossed out',
 'analogy': 'Every file sent to the night docket carries a case-number stamp, and the orders come back stamped the same way in whatever order the court reaches them. The clerk pulls the five that failed by number, has the over-long ones split into volumes, and sends back only those.',
 "svg": """<rect class="paper" x="14" y="22" width="46" height="40" rx="3"/>
<circle class="acc" cx="52" cy="30" r="7"/>
<path d="M68 42 h18 M80 36 l6 6 -6 6"/>
<rect class="tint" x="94" y="22" width="46" height="40" rx="3"/>
<circle class="acc" cx="132" cy="30" r="7"/>
<rect class="paper" x="34" y="76" width="24" height="22" rx="2"/>
<text class="lbl" x="46" y="92" text-anchor="middle">1</text>
<rect class="paper" x="66" y="76" width="24" height="22" rx="2"/>
<text class="lbl" x="78" y="92" text-anchor="middle">2</text>
<rect class="paper" x="98" y="76" width="24" height="22" rx="2"/>
<text class="lbl" x="110" y="92" text-anchor="middle">3</text>
<line class="no" x1="64" y1="74" x2="94" y2="100"/>
<line class="no" x1="94" y1="74" x2="64" y2="100"/>""",
},
{
 'id': 'D4-20',
 'title': 'Submission cadence from the SLA arithmetic',
 'concept': 'Batch submission windows are sized against the 24-hour worst case, so guaranteeing a 30-hour SLA with up to 24 hours of processing means submitting in roughly four-hour windows.',
 'tested': 'A recurring pipeline owes results inside a stated SLA and runs on batch, and the question asks how often to submit. The answer works back from the SLA against the full 24-hour worst case rather than typical completion, giving four-hour submission windows for a 30-hour SLA. The distractor plans around how long batches usually take, which no SLA supports.',
 'remember': 'Budget the full 24 hours, never the usual completion time. A 30-hour SLA with 24-hour processing gives four-hour submission windows.',
 'alt': 'Four-hour submission blocks under a 24-hour span before a 30-hour deadline',
 'analogy': 'The night docket clears by morning most nights, and the court undertakes only that it will be within the day. A registry that must return every order inside thirty hours therefore sends files up in short blocks through the day, so no file rests on a promise the court never made.',
 "svg": """<line x1="14" y1="92" x2="146" y2="92"/>
<rect class="acc" x="16" y="76" width="24" height="16" rx="2"/>
<rect class="acc" x="46" y="76" width="24" height="16" rx="2"/>
<rect class="acc" x="76" y="76" width="24" height="16" rx="2"/>
<rect class="acc" x="106" y="76" width="24" height="16" rx="2"/>
<text class="lbl" x="28" y="106" text-anchor="middle">4h</text>
<path class="dash" d="M16 52 H120"/>
<text class="lbl" x="68" y="44" text-anchor="middle">24h</text>
<line x1="140" y1="34" x2="140" y2="62"/>
<text class="lbl" x="140" y="26" text-anchor="middle">30h</text>""",
},
{
 'id': 'D4-21',
 'title': 'Refine on a sample before the big batch',
 'concept': 'Refining the extraction prompt on a small sample before submitting a large batch raises the first-pass success rate and reduces the cost of resubmission.',
 'tested': 'A large volume of documents is about to go through one extraction prompt and the question asks what to do first. The answer refines the prompt on a representative sample, then submits the volume. The distractor submits the full batch and iterates on it, where every round pays for the whole batch and waits up to 24 hours to learn one thing.',
 'remember': 'Sample first, batch second. A defect found on a sample costs a sample; the same defect found after a full batch costs the batch and up to 24 hours.',
 'alt': 'Small sample checked first, then the full stack submitted',
 'analogy': 'A registry about to send ten thousand files up on one form tries the form on a dozen first. A defect caught on the dozen costs a morning; the same defect caught after the night docket has run costs every file on it.',
 "svg": """<rect class="paper" x="16" y="36" width="28" height="36" rx="2"/>
<rect class="paper" x="22" y="42" width="28" height="36" rx="2"/>
<rect class="paper" x="28" y="48" width="28" height="36" rx="2"/>
<path class="acc" d="M34 64 l6 7 l10 -14"/>
<path d="M66 62 h18 M78 56 l6 6 -6 6"/>
<rect class="tint" x="94" y="18" width="52" height="14" rx="2"/>
<rect class="tint" x="94" y="36" width="52" height="14" rx="2"/>
<rect class="tint" x="94" y="54" width="52" height="14" rx="2"/>
<rect class="tint" x="94" y="72" width="52" height="14" rx="2"/>
<rect class="tint" x="94" y="90" width="52" height="14" rx="2"/>""",
},
{
 'id': 'D4-22',
 'title': 'An independent instance reviews; the author does not',
 'concept': 'A model that generated code retains its reasoning from that session and is less likely to question its own decisions, so review goes to a second instance without that context.',
 'tested': "Generated code passes its own careful-review step and bugs keep reaching production; the question asks how to restructure the review. The answer routes the artifact to a second, independent instance that never sees the generator's reasoning. Distractors strengthen the self-review instruction, enable extended thinking on the generator, or ask the same conversation for a second pass, all of which keep the original reasoning in context.",
 'remember': 'Independence is a property of context, not of effort. Fresh instance, artifact and criteria only, none of the generating conversation — though earlier review findings may travel, which is a different thing (D3-24).',
 'alt': "The trial judge's reasoning does not travel to the second judge",
 'analogy': 'The judge who tried the case reads the file through reasoning already settled on. An appeal is heard by a bench that did not sit at the trial and receives only the record and the grounds, which is why it notices what the first judge had explained away.',
 "svg": """<circle cx="38" cy="30" r="9"/>
<path d="M38 39 v22 M26 48 h24"/>
<rect class="dash" x="16" y="70" width="44" height="26" rx="3"/>
<text class="lbl" x="38" y="87" text-anchor="middle">why</text>
<line class="dash thin" x1="60" y1="83" x2="98" y2="83"/>
<line class="no" x1="72" y1="74" x2="86" y2="92"/>
<line class="no" x1="86" y1="74" x2="72" y2="92"/>
<path class="acc" d="M68 46 h22 M84 40 l6 6 -6 6"/>
<circle class="acc" cx="120" cy="30" r="9"/>
<path class="acc" d="M120 39 v22 M108 48 h24"/>
<rect class="paper" x="98" y="70" width="44" height="26" rx="3"/>
<line class="thin" x1="106" y1="80" x2="134" y2="80"/>
<line class="thin" x1="106" y1="88" x2="126" y2="88"/>""",
},
{
 'id': 'D4-23',
 'title': 'Per-file passes plus a cross-file integration pass',
 'concept': 'Splitting a large multi-file review into a focused pass per file for local issues plus a separate integration pass for cross-file data flow avoids attention dilution and contradictory findings.',
 'tested': 'A pull request touching 14 files draws detailed feedback on some files, superficial comments on others, missed bugs, and the same pattern flagged in one file and approved in another; the question asks how to restructure the review. The answer analyses each file individually, then runs a separate integration-focused pass over cross-file data flow. Distractors reach for a larger context window, which does not improve attention quality, push developers to split the pull request into smaller submissions, or run three full passes and keep only findings that appear in two of them, which suppresses real bugs caught intermittently.',
 'remember': 'Uneven depth and contradictions across files → split the passes. A bigger context window does not buy attention quality, and consensus voting drops real findings.',
 'alt': 'Three files each get their own pass, then one integration pass',
 'analogy': 'Fourteen exhibits heard in one sitting get uneven attention: the first examined closely, the twelfth waved through, the same clause read two ways in a single judgment. The registry lists each exhibit for its own short hearing, then one further hearing on how they fit together.',
 "svg": """<rect class="paper" x="16" y="16" width="30" height="28" rx="2"/>
<rect class="paper" x="65" y="16" width="30" height="28" rx="2"/>
<rect class="paper" x="114" y="16" width="30" height="28" rx="2"/>
<path class="acc" d="M31 48 v12 M27 56 l4 5 l4 -5"/>
<path class="acc" d="M80 48 v12 M76 56 l4 5 l4 -5"/>
<path class="acc" d="M129 48 v12 M125 56 l4 5 l4 -5"/>
<circle class="acc" cx="31" cy="72" r="8"/>
<circle class="acc" cx="80" cy="72" r="8"/>
<circle class="acc" cx="129" cy="72" r="8"/>
<rect class="tint" x="16" y="90" width="128" height="20" rx="3"/>
<text class="lbl" x="80" y="104" text-anchor="middle">int</text>""",
},
{
 'id': 'D4-24',
 'title': 'Confidence beside each finding routes the review',
 'concept': 'A verification pass in which the model self-reports confidence alongside each finding lets routing be calibrated, so low-confidence findings reach a person.',
 'tested': 'A verification pass emits every finding the same way and there is no basis for deciding which need a human; the question asks how to route them. The answer has the model report its confidence with each finding, sending high-confidence items straight out and low-confidence items to review. The distractor filters at the source, instructing the model to report only high-confidence findings, which drops findings rather than routing them.',
 'remember': 'Confidence routes a finding; it never suppresses one. Report it per finding, send the doubtful ones to a person. Filtering to high-confidence only is the distractor (D4-01).',
 'alt': 'High-confidence finding auto-posted; low-confidence finding routed to a person',
 'analogy': 'Each finding leaves the bench with a note of how firmly it is held. The clerk sends the firm ones straight out and lists the doubtful ones for a person to look at, so doubt is routed rather than discarded.',
 "svg": """<rect class="paper" x="12" y="28" width="44" height="22" rx="2"/>
<text class="lbl" x="34" y="43" text-anchor="middle">hi</text>
<rect class="paper" x="12" y="70" width="44" height="22" rx="2"/>
<text class="lbl" x="34" y="85" text-anchor="middle">lo</text>
<path class="acc" d="M62 39 h20 M76 33 l6 6 -6 6"/>
<path class="acc" d="M62 81 h20 M76 75 l6 6 -6 6"/>
<rect class="tint" x="90" y="24" width="54" height="30" rx="3"/>
<path d="M104 39 l5 6 l12 -14"/>
<circle cx="116" cy="70" r="9"/>
<path d="M116 79 v16 M104 87 h24"/>""",
},
]
