# Domain 5 — Context Management & Reliability · building: the hospital ward
# Generated by merge_parts.py from the authoring halves — edit the halves, not this file.

ITEMS = [
{
 'id': 'D5-01',
 'title': 'Keep a case-facts block outside the summary',
 'concept': 'Amounts, percentages, dates, order numbers and statuses are extracted into a persistent case-facts block included in every prompt, outside the summarised history, so compression cannot blur them.',
 'tested': 'After a long support conversation the agent quotes a discount or refund amount that no longer matches what the customer was promised, and the question asks which change preserves precision. Extracting the transactional facts into a case-facts block sent outside the summarised history is the answer; the distractors revise the summarisation prompt to preserve numbers or raise the summarisation threshold, and both still route the amounts through compression.',
 'remember': 'Precise numbers live outside summarisation, in a case-facts block sent every turn. A better summarisation prompt still depends on the summariser executing perfectly.',
 'alt': 'Chart clipboard reading 89.99; its route into the blurred summary crossed out',
 'analogy': 'The shift summary says the patient is comfortable and improving; the chart at the foot of the bed still carries the dose, the time it was given and the allergy. Every handover rewrites the summary, and the chart is carried across untouched.',
 "svg": """<rect class="dash" x="10" y="26" width="38" height="54" rx="2"/>
<path class="thin" d="M16 42 q5 -5 10 0 t10 0 M16 54 q5 -5 10 0 t10 0 M16 66 h20"/>
<rect class="tint" x="58" y="70" width="84" height="22" rx="4"/>
<rect x="58" y="52" width="9" height="40"/>
<path d="M66 92 v10 M136 92 v10"/>
<rect class="acc" x="100" y="20" width="46" height="34" rx="2"/>
<rect class="thin" x="116" y="14" width="14" height="6" rx="1"/>
<text class="lbl" x="123" y="42" text-anchor="middle">89.99</text>
<line class="thin" x1="123" y1="54" x2="123" y2="70"/>
<line class="dash thin" x1="96" y1="36" x2="52" y2="40"/>
<line class="no" x1="66" y1="30" x2="82" y2="46"/>
<line class="no" x1="82" y1="30" x2="66" y2="46"/>""",
},
{
 'id': 'D5-02',
 'title': 'Lost in the middle: summary first, headers throughout',
 'concept': 'Models process the beginning and end of long inputs reliably and may omit findings from middle sections, so key findings go at the start and the detail carries explicit section headers.',
 'tested': "A synthesis agent reads a large aggregated input and its report reflects the opening and closing material while findings from the middle are missing; the question asks the mitigation. A key-findings summary at the start plus explicit section headers is the answer, against rotating which agent's output appears first, which leaves the attention pattern unchanged, and compressing everything under a token target, which can drop critical information.",
 'remember': 'Beginning and end are read reliably. Key findings at the top, explicit section headers throughout. Rotation and blanket compression are the distractors.',
 'alt': 'Long file with a faint middle; key-findings board pinned at the top',
 'analogy': 'The ward round starts at the summary board, and what is written there is what the team carries to every bed. Findings buried in the middle of a long file get skimmed, so they are moved to the board and each part of the file is given a heading.',
 "svg": """<rect class="acc" x="24" y="10" width="80" height="18" rx="2"/>
<text class="lbl" x="64" y="23" text-anchor="middle">key</text>
<rect class="tint" x="24" y="34" width="80" height="74" rx="2"/>
<rect class="accfill" x="30" y="40" width="6" height="6"/>
<line x1="42" y1="43" x2="96" y2="43"/>
<line class="thin" x1="30" y1="53" x2="88" y2="53"/>
<line class="thin" opacity="0.35" x1="30" y1="63" x2="96" y2="63"/>
<line class="thin" opacity="0.35" x1="30" y1="71" x2="86" y2="71"/>
<line class="thin" opacity="0.35" x1="30" y1="79" x2="92" y2="79"/>
<rect class="accfill" x="30" y="86" width="6" height="6"/>
<line x1="42" y1="89" x2="96" y2="89"/>
<line class="thin" x1="30" y1="99" x2="88" y2="99"/>
<line class="acc" x1="114" y1="43" x2="128" y2="43"/>
<line class="dash thin" x1="114" y1="71" x2="128" y2="71"/>
<line class="acc" x1="114" y1="89" x2="128" y2="89"/>""",
},
{
 'id': 'D5-03',
 'title': 'Trim tool output before it enters context',
 'concept': 'Tool results accumulate in context and consume tokens out of proportion to their relevance, so a lookup returning forty-plus fields is cut to the five the task needs before it lands.',
 'tested': 'Long multi-issue sessions fill with order lookups returning forty-plus fields when five matter, and the question asks how to conserve context. Trimming tool output to the relevant fields before it accumulates is the answer; distractors instruct the model to ignore the irrelevant fields, which still pays the tokens, or summarise the conversation harder, which treats the symptom while the verbose results keep arriving.',
 'remember': 'Trim at the source, before the result enters context. Telling the model to ignore fields still spends the tokens; heavier summarisation leaves the flood in place.',
 'alt': 'Forty-row lab panel trimmed to five relevant lines',
 'analogy': "A full lab panel prints forty values and today's decision turns on five of them. The chart carries those five, because filing the whole panel at every review buries the lines anyone will read.",
 "svg": """<rect class="tint" x="12" y="18" width="46" height="88" rx="2"/>
<text class="lbl" x="35" y="34" text-anchor="middle">40</text>
<line class="thin" x1="18" y1="44" x2="52" y2="44"/>
<line class="thin" x1="18" y1="52" x2="52" y2="52"/>
<line class="thin" x1="18" y1="60" x2="52" y2="60"/>
<line class="thin" x1="18" y1="68" x2="52" y2="68"/>
<line class="thin" x1="18" y1="76" x2="52" y2="76"/>
<line class="thin" x1="18" y1="84" x2="52" y2="84"/>
<line class="thin" x1="18" y1="92" x2="52" y2="92"/>
<line class="thin" x1="18" y1="100" x2="52" y2="100"/>
<path d="M64 62 h18 M76 56 l6 6 -6 6"/>
<rect class="paper" x="94" y="32" width="48" height="62" rx="2"/>
<text class="lbl" x="118" y="48" text-anchor="middle">5</text>
<line class="acc" x1="100" y1="58" x2="136" y2="58"/>
<line class="acc" x1="100" y1="66" x2="136" y2="66"/>
<line class="acc" x1="100" y1="74" x2="136" y2="74"/>
<line class="acc" x1="100" y1="82" x2="136" y2="82"/>
<line class="acc" x1="100" y1="90" x2="136" y2="90"/>""",
},
{
 'id': 'D5-04',
 'title': 'The API is stateless: resend the history',
 'concept': 'Claude holds no server-side memory between requests, so conversational coherence comes from the application passing the complete prior conversation in the `messages` array of each new request.',
 'tested': 'A user states a preference in turn one and the agent asks for it again two turns later, or the same history is re-sent on every turn and the question asks the root cause. The stateless API is the answer: the application must include prior messages, and every request re-sends them. Distractors invent a `session_id` parameter or reach for a vector database, which serves retrieval over months of history rather than ordinary multi-turn memory.',
 'remember': 'No server-side memory. Memory is the `messages` array you send. There is no `session_id`, and ordinary multi-turn conversation needs no vector database.',
 'alt': 'Three requests each resending the whole history; a memory store crossed out',
 'analogy': "A locum takes the ward round each shift and has never met anyone in the beds. Whatever the folder handed over contains is what is known, and nothing carries over in anyone's head.",
 "svg": """<rect class="tint" x="10" y="14" width="52" height="20" rx="2"/>
<line class="thin" x1="16" y1="24" x2="36" y2="24"/>
<rect class="tint" x="10" y="42" width="52" height="28" rx="2"/>
<line class="thin" x1="16" y1="52" x2="36" y2="52"/>
<line class="thin" x1="16" y1="62" x2="46" y2="62"/>
<rect class="acc" x="10" y="78" width="52" height="34" rx="2"/>
<line class="thin" x1="16" y1="88" x2="36" y2="88"/>
<line class="thin" x1="16" y1="98" x2="46" y2="98"/>
<line class="thin" x1="16" y1="106" x2="52" y2="106"/>
<path d="M70 56 h16 M80 50 l6 6 -6 6"/>
<rect class="tint" x="94" y="34" width="52" height="36" rx="3"/>
<text class="lbl" x="120" y="56" text-anchor="middle">API</text>
<line class="dash thin" x1="120" y1="70" x2="120" y2="84"/>
<rect class="dash" x="100" y="84" width="40" height="20" rx="10"/>
<line class="no" x1="104" y1="86" x2="136" y2="102"/>
<line class="no" x1="136" y1="86" x2="104" y2="102"/>""",
},
{
 'id': 'D5-05',
 'title': 'Subagents return structured findings, not prose',
 'concept': 'Subagents return key facts, citations, relevance scores and metadata such as dates, source locations and methodological context in structured outputs, rather than verbose content and reasoning chains.',
 'tested': "Combined subagent output far exceeds what the downstream agent's context budget allows, or the synthesis loses the context needed to interpret a finding, and the question asks where to fix it. Changing the upstream agents to emit structured data with metadata is the answer; the distractor inserts an intermediate summarisation agent, which adds a stage and another point of failure without addressing the source.",
 'remember': 'Fix the output format upstream: key facts, citations, relevance scores, dates and source locations. An extra summarisation stage treats the volume rather than its cause.',
 'alt': 'Rambling page crossed out beside a structured handover form with labelled fields',
 'analogy': "A handover that says she is fine leaves the next doctor to reconstruct everything. The ward's handover form has a field for the finding, when it was measured and who recorded it, which is what makes the next shift's decisions safe.",
 "svg": """<rect class="dash" x="10" y="28" width="46" height="60" rx="2"/>
<path class="thin" d="M16 44 q5 -5 10 0 t10 0 M16 56 q5 -5 10 0 t10 0 M16 68 q5 -5 10 0 t10 0"/>
<line class="no" x1="16" y1="34" x2="50" y2="82"/>
<line class="no" x1="50" y1="34" x2="16" y2="82"/>
<path d="M64 58 h18 M76 52 l6 6 -6 6"/>
<rect class="paper" x="92" y="18" width="54" height="82" rx="2"/>
<rect class="accfill" x="98" y="28" width="6" height="6"/>
<line class="acc" x1="110" y1="31" x2="140" y2="31"/>
<rect class="accfill" x="98" y="46" width="6" height="6"/>
<line class="acc" x1="110" y1="49" x2="140" y2="49"/>
<rect class="accfill" x="98" y="64" width="6" height="6"/>
<line class="acc" x1="110" y1="67" x2="134" y2="67"/>
<rect class="accfill" x="98" y="82" width="6" height="6"/>
<line class="acc" x1="110" y1="85" x2="140" y2="85"/>""",
},
{
 'id': 'D5-06',
 'title': 'Behavioural drift is dilution, not overflow',
 'concept': 'When system-prompt behaviour degrades after a handful of turns at around 2,500 tokens, the cause is accumulated assistant responses diluting the instruction rather than a full context window.',
 'tested': 'An agent stops following a system-prompt rule by the seventh turn while the conversation totals about 2,500 tokens, and the question asks the root cause. Accumulated responses diluting the system prompt is the answer; context-window overflow is impossible at that size, and the claim that the system prompt applies only to the first turn is false, since it is included in every request.',
 'remember': 'Small token count plus fading rule-following means dilution, not overflow. The system prompt is sent every request, and it competes with everything accumulated after it.',
 'alt': 'Barely filled window crossed out; one accent line among many later notes',
 'analogy': "The protocol notice is still pinned by the door, unchanged, but after seven pages of the team's own notes it is one line among many that the reader passes. The folder is nowhere near full; the notice has been outnumbered.",
 "svg": """<rect class="dash" x="10" y="14" width="58" height="92" rx="3"/>
<rect class="tint" x="14" y="86" width="50" height="16" rx="2"/>
<text class="lbl" x="39" y="76" text-anchor="middle">2.5K</text>
<line class="no" x1="50" y1="20" x2="66" y2="36"/>
<line class="no" x1="66" y1="20" x2="50" y2="36"/>
<line class="acc" x1="84" y1="20" x2="148" y2="20"/>
<line class="thin" x1="84" y1="32" x2="148" y2="32"/>
<line class="thin" x1="84" y1="44" x2="148" y2="44"/>
<line class="thin" x1="84" y1="56" x2="148" y2="56"/>
<line class="thin" x1="84" y1="68" x2="148" y2="68"/>
<line class="thin" x1="84" y1="80" x2="148" y2="80"/>
<line class="thin" x1="84" y1="92" x2="148" y2="92"/>
<line class="thin" x1="84" y1="104" x2="148" y2="104"/>""",
},
{
 'id': 'D5-07',
 'title': 'Months of history need retrieval, not summarisation',
 'concept': 'Recalling a specific past exchange from months of conversation, around 85K tokens, calls for semantic embeddings with retrieval, because progressive summarisation compresses those conclusions into abstractions.',
 'tested': 'The question asks what was concluded about a particular point weeks earlier, across a history of about 85K tokens, and the design decision is how the system should recall it. Semantic retrieval over the stored exchanges is the answer; progressive summarisation is the distractor, since the specific conclusion is what compression removes.',
 'remember': 'Specific recall from months of history → retrieve the actual exchange; summarisation keeps the gist and loses the sentence being asked about. How retrieval is built is out of scope.',
 'alt': 'One record pulled from an 85K archive; blurred summary page crossed out',
 'analogy': 'The archive holds every clinic letter from the past three months, and the question is what the cardiologist concluded in March. The March letter is pulled and read; a discharge summary recording that a cardiac review took place cannot answer it.',
 "svg": """<rect class="tint" x="10" y="58" width="76" height="46" rx="3"/>
<text class="lbl" x="14" y="24">85K</text>
<line class="thin" x1="20" y1="66" x2="20" y2="98"/>
<line class="thin" x1="30" y1="66" x2="30" y2="98"/>
<line class="thin" x1="40" y1="66" x2="40" y2="98"/>
<line class="thin" x1="62" y1="66" x2="62" y2="98"/>
<line class="thin" x1="72" y1="66" x2="72" y2="98"/>
<rect class="acc paper" x="44" y="20" width="16" height="34" rx="1" transform="rotate(-8 52 37)"/>
<line class="acc thin" x1="52" y1="56" x2="52" y2="64"/>
<rect class="dash" x="96" y="36" width="48" height="54" rx="2"/>
<path class="thin" d="M102 50 q5 -5 10 0 t10 0 M102 62 q5 -5 10 0 t10 0 M102 74 h20"/>
<line class="no" x1="102" y1="42" x2="138" y2="84"/>
<line class="no" x1="138" y1="42" x2="102" y2="84"/>""",
},
{
 'id': 'D5-08',
 'title': 'Escalate on request, policy gap, or stalled progress',
 'concept': 'The escalation triggers are an explicit customer request for a human, a policy exception or gap where policy is silent or ambiguous, and inability to make meaningful progress.',
 'tested': "A customer asks for something policy does not address, such as matching a competitor's price when policy covers only the company's own adjustments, and the question asks what the agent should do. Escalation is the answer, on the ground that policy is silent rather than that the case is hard; distractors improvise a decision from adjacent policy or treat complexity on its own as the trigger.",
 'remember': 'Three structural triggers: they asked for a human, policy is silent or ambiguous, progress has stalled. Difficulty on its own is not one of them.',
 'alt': 'Three ticked escalation criteria; a vague fourth trigger crossed out',
 'analogy': 'The ward calls the consultant on written triggers: the patient asks for one, the protocol does not cover this presentation, or the plan has stopped moving. A demanding case is not on that list, and neither is a junior finding it uncomfortable.',
 "svg": """<rect class="paper" x="10" y="16" width="74" height="60" rx="2"/>
<rect class="thin" x="16" y="24" width="8" height="8"/>
<path class="acc" d="M18 28 l3 3 l5 -6"/>
<line class="thin" x1="30" y1="28" x2="76" y2="28"/>
<rect class="thin" x="16" y="42" width="8" height="8"/>
<path class="acc" d="M18 46 l3 3 l5 -6"/>
<line class="thin" x1="30" y1="46" x2="76" y2="46"/>
<rect class="thin" x="16" y="60" width="8" height="8"/>
<path class="acc" d="M18 64 l3 3 l5 -6"/>
<line class="thin" x1="30" y1="64" x2="76" y2="64"/>
<line class="dash thin" x1="30" y1="90" x2="76" y2="90"/>
<line class="no" x1="40" y1="82" x2="56" y2="98"/>
<line class="no" x1="56" y1="82" x2="40" y2="98"/>
<path class="acc" d="M92 46 h16 M102 40 l6 6 -6 6"/>
<circle cx="128" cy="34" r="9"/>
<path d="M128 43 v20 M116 50 h24 M120 78 l8 -15 M136 78 l-8 -15"/>""",
},
{
 'id': 'D5-09',
 'title': 'Explicit criteria with examples, not sentiment or self-confidence',
 'concept': 'Escalation calibration comes from explicit criteria in the system prompt with few-shot examples of when to escalate and when to resolve, because sentiment and self-reported confidence do not track case complexity.',
 'tested': 'An agent escalates straightforward cases while attempting the ones that need policy exceptions, and the question asks the most effective way to improve escalation calibration. Explicit criteria with few-shot examples is the answer; a self-reported confidence score fails because the agent is already confidently wrong on the hard cases, sentiment analysis addresses a different problem, and a separately trained classifier is over-engineering before prompt work has been tried.',
 'remember': 'Unclear decision boundaries are fixed with written criteria plus worked examples. Self-rated confidence is uncalibrated, mood does not track complexity, and a trained classifier is premature.',
 'alt': 'Criteria card with worked examples; mood face and confidence dial crossed out',
 'analogy': 'The consultant is called on written criteria with worked examples of calls that were right and calls that were not. How distressed the patient sounds, and how sure the junior feels, are not the trigger.',
 "svg": """<rect class="paper" x="10" y="14" width="70" height="92" rx="2"/>
<line class="acc" x1="18" y1="28" x2="72" y2="28"/>
<rect class="thin" x="18" y="40" width="20" height="14" rx="2"/>
<path d="M42 47 h10 M48 43 l4 4 -4 4"/>
<rect class="acc thin" x="56" y="40" width="16" height="14" rx="2"/>
<rect class="thin" x="18" y="66" width="20" height="14" rx="2"/>
<path d="M42 73 h10 M48 69 l4 4 -4 4"/>
<rect class="acc thin" x="56" y="66" width="16" height="14" rx="2"/>
<line class="thin" x1="18" y1="94" x2="64" y2="94"/>
<circle cx="114" cy="34" r="15"/>
<path class="thin" d="M108 29 v3 M120 29 v3 M107 43 q7 -6 14 0"/>
<line class="no" x1="124" y1="40" x2="138" y2="54"/>
<line class="no" x1="138" y1="40" x2="124" y2="54"/>
<circle cx="114" cy="84" r="15"/>
<path class="thin" d="M100 86 a14 14 0 0 1 28 0 M114 86 l9 -7"/>
<line class="no" x1="124" y1="90" x2="138" y2="104"/>
<line class="no" x1="138" y1="90" x2="124" y2="104"/>""",
},
{
 'id': 'D5-10',
 'title': 'Explicit request escalates now; frustration gets an offer',
 'concept': 'An explicit request for a human is honoured immediately without first attempting investigation, while frustration over a solvable issue gets acknowledgement and an offer, escalating only if the customer reiterates.',
 'tested': 'One message demands a manager and another vents about a problem the agent can fix, and the question asks how each should be handled. The demand is escalated at once with no investigation first; the frustration is acknowledged and answered with a concrete resolution, and escalated when the customer repeats the request. Distractors attempt a fix before honouring the explicit request, or escalate at the first sign of dissatisfaction.',
 'remember': 'Asked for a human → escalate now, no investigation first. Frustrated about something solvable → acknowledge, offer the fix, escalate if they ask again.',
 'alt': 'Human request goes straight to the consultant; frustration gets an offer first',
 'analogy': 'A patient who asks to see the consultant is referred straight away, without the ward first trying to talk them round. A patient upset about a delay the ward can fix is heard out and offered the fix, and referred if they ask again.',
 "svg": """<path class="tint" d="M10 12 h56 v24 h-42 l-8 8 v-8 h-6 z"/>
<text class="lbl" x="36" y="29" text-anchor="middle">human</text>
<path class="acc" d="M72 26 h22 M86 20 l6 6 -6 6"/>
<circle cx="118" cy="14" r="8"/>
<path d="M118 22 v14 M108 28 h20 M112 50 l6 -14 M124 50 l-6 -14"/>
<path class="tint" d="M10 60 h46 v24 h-32 l-8 8 v-8 h-6 z"/>
<path class="thin" d="M18 78 l6 -10 l5 10 l6 -10 l5 10"/>
<path d="M60 74 h16 M68 68 l6 6 -6 6"/>
<rect class="paper" x="80" y="58" width="30" height="32" rx="2"/>
<path class="acc" d="M86 74 l5 5 l10 -12"/>
<line class="dash thin" x1="114" y1="74" x2="126" y2="74"/>
<circle class="dash" cx="138" cy="74" r="9"/>""",
},
{
 'id': 'D5-11',
 'title': 'Two matches: ask for another identifier',
 'concept': 'When a lookup returns multiple matching customers the agent asks for an additional identifier such as an email or order number, rather than selecting a match by heuristic.',
 'tested': 'A name search returns several accounts and the question asks what the agent should do next. Requesting another identifier is the answer; distractors take the most recently active account or the first result the tool returned, both of which risk actioning the wrong customer, while escalating to a human is heavier than an ambiguity a question resolves.',
 'remember': 'Multiple matches → ask for one more identifier. Most recent and first-in-list are heuristics, and escalation is more than this ambiguity needs.',
 'alt': 'Two identical wristbands; picking one crossed out, an identifier requested instead',
 'analogy': 'Two patients on the ward share a surname, so nothing is given until the wristband is checked against a second detail. Choosing the one whose notes are nearest to hand is how the wrong person gets treated.',
 "svg": """<rect class="tint" x="10" y="18" width="54" height="20" rx="10"/>
<text class="lbl" x="37" y="32" text-anchor="middle">J Lee</text>
<rect class="tint" x="10" y="60" width="54" height="20" rx="10"/>
<text class="lbl" x="37" y="74" text-anchor="middle">J Lee</text>
<path class="dash thin" d="M88 28 h-16 M78 24 l-6 4 6 4"/>
<line class="no" x1="72" y1="20" x2="88" y2="36"/>
<line class="no" x1="88" y1="20" x2="72" y2="36"/>
<rect class="acc" x="92" y="52" width="52" height="32" rx="3"/>
<text class="lbl" x="118" y="72" text-anchor="middle">DOB?</text>
<line class="acc thin" x1="92" y1="60" x2="66" y2="40"/>
<line class="acc thin" x1="92" y1="76" x2="66" y2="72"/>""",
},
{
 'id': 'D5-12',
 'title': 'State assumptions and proceed on a vague request',
 'concept': 'For a vague request the effective response proceeds on reasonable assumptions that are stated in the reply and open to correction.',
 'tested': 'A request arrives underspecified and the question asks how the agent should handle it. Proceeding on stated assumptions with an invitation to correct them is the answer; a wall of clarifying questions drives people to abandon the interaction, and defaults applied silently leave them puzzled when the output does not match what they meant.',
 'remember': "Say what you assumed, do the work, invite correction. This is an underspecified task request; when a tool returns several possible customers, the guide's answer is to ask for one more identifier instead (D5-11).",
 'alt': 'Four-question form crossed out; note of stated assumptions, work continuing',
 'analogy': 'A request for the usual discharge paperwork does not say which template is meant. The ward notes which one it has assumed, prepares it, and flags the assumption for correction, rather than returning a questionnaire and waiting. Where the doubt is which patient is meant, the wristband is checked instead.',
 "svg": """<rect class="dash" x="10" y="24" width="46" height="64" rx="2"/>
<text class="lbl" x="33" y="44" text-anchor="middle">?</text>
<line class="thin" x1="18" y1="56" x2="48" y2="56"/>
<line class="thin" x1="18" y1="66" x2="48" y2="66"/>
<line class="thin" x1="18" y1="76" x2="48" y2="76"/>
<line class="no" x1="16" y1="30" x2="50" y2="82"/>
<line class="no" x1="50" y1="30" x2="16" y2="82"/>
<path d="M62 56 h16 M70 50 l6 6 -6 6"/>
<rect class="paper" x="86" y="24" width="58" height="62" rx="2"/>
<line class="acc" x1="94" y1="38" x2="136" y2="38"/>
<line class="acc" x1="94" y1="50" x2="130" y2="50"/>
<line class="thin" x1="94" y1="62" x2="136" y2="62"/>
<line class="thin" x1="94" y1="74" x2="124" y2="74"/>
<path class="acc" d="M112 94 h20 M126 88 l6 6 -6 6"/>""",
},
{
 'id': 'D5-13',
 'title': 'Structured error context enables coordinator recovery',
 'concept': 'A failing subagent returns structured error context — the failure type, the query attempted, any partial results and potential alternatives — so the coordinator can choose how to recover.',
 'tested': 'The web search subagent times out and the question asks which error propagation approach best enables intelligent recovery. Structured error context is the answer; a generic status such as search unavailable after retries hides what the coordinator needs, returning an empty result set marked successful suppresses the failure, and propagating the exception to a top-level handler terminates the whole workflow while recovery was still available.',
 'remember': 'Failure type, attempted query, partial results, alternatives. A bare status leaves only retry or abort; silent success and whole-workflow termination are both anti-patterns.',
 'alt': 'Handover slip with four labelled fields; a bare fail tag crossed out',
 'analogy': 'A specimen that could not be processed comes back with the reason, which test was attempted, what was salvageable and what could be run instead. A slip that says unavailable leaves the ward to repeat everything or drop the investigation.',
 "svg": """<rect class="paper" x="10" y="14" width="64" height="90" rx="2"/>
<rect class="accfill" x="18" y="26" width="6" height="6"/>
<line class="acc" x1="30" y1="29" x2="66" y2="29"/>
<rect class="accfill" x="18" y="46" width="6" height="6"/>
<line class="acc" x1="30" y1="49" x2="66" y2="49"/>
<rect class="accfill" x="18" y="66" width="6" height="6"/>
<line class="acc" x1="30" y1="69" x2="60" y2="69"/>
<rect class="accfill" x="18" y="86" width="6" height="6"/>
<line class="acc" x1="30" y1="89" x2="66" y2="89"/>
<path class="acc" d="M80 40 h18 M92 34 l6 6 -6 6"/>
<circle cx="126" cy="22" r="9"/>
<path d="M126 31 v14 M116 37 h20 M120 58 l6 -13 M132 58 l-6 -13"/>
<text class="lbl" x="124" y="72" text-anchor="middle">fail</text>
<rect class="dash" x="102" y="78" width="44" height="24" rx="3"/>
<line class="no" x1="108" y1="82" x2="140" y2="98"/>
<line class="no" x1="140" y1="82" x2="108" y2="98"/>""",
},
{
 'id': 'D5-14',
 'title': 'Access failure is not an empty result',
 'concept': 'A timeout is an access failure needing a retry decision while zero matches is a successful query, and error reporting distinguishes the two so the coordinator can decide appropriately.',
 'tested': 'A tool returns nothing and the question turns on whether that is a failure or an answer. Reporting them differently is the answer: an empty result is a valid outcome the workflow can proceed on, while a timeout carries a retry decision. Distractors collapse both into one error status, or mark a timeout as an empty success, which hides a failure the coordinator could have recovered from.',
 'remember': 'Zero results is an answer, not an error. A timeout is an access failure and needs a retry decision. Report them as different things.',
 'alt': 'Vial reading zero ticked; a missing specimen with a clock and retry',
 'analogy': 'A negative test result and a lost specimen arrive on similar slips and mean opposite things. One closes the question; the other means the sample has to be taken again, and a ward that files them together acts on an answer it never had.',
 "svg": """<path class="tint" d="M22 30 h22 v22 a11 11 0 0 1 -22 0 z"/>
<line x1="18" y1="30" x2="48" y2="30"/>
<text class="lbl" x="33" y="48" text-anchor="middle">0</text>
<path class="acc" d="M22 80 l7 8 l14 -17"/>
<line class="dash thin" x1="80" y1="14" x2="80" y2="106"/>
<path class="dash" d="M112 30 h22 v22 a11 11 0 0 1 -22 0 z"/>
<line x1="108" y1="30" x2="138" y2="30"/>
<path class="acc" d="M106 80 q16 -12 32 -2 M131 71 l8 7 -10 3"/>
<circle class="paper" cx="122" cy="96" r="13"/>
<path d="M122 96 v-8 M122 96 l7 5"/>""",
},
{
 'id': 'D5-15',
 'title': 'Recover locally, propagate what you could not fix',
 'concept': 'Subagents implement local recovery for transient failures and propagate only the errors they cannot resolve, including what was attempted and any partial results.',
 'tested': 'A subagent hits a failure that a retry would clear, and the question asks where recovery belongs. Handling transient failures inside the subagent and escalating only the unresolved ones is the answer, carrying the attempts made and the partial results with them; distractors send every failure up to the coordinator, losing the cheap local fix, or retry internally and then report a bare status, stripping the context the coordinator needs.',
 'remember': 'Transient failures are handled where they happen. What reaches the coordinator is what could not be fixed, plus the attempts made and any partial results.',
 'alt': 'Subagent retries locally, then sends attempts and partial results upward',
 'analogy': 'The ward repeats a specimen that clotted before it troubles the consultant. What goes up the line is the problem the ward cannot resolve, with the attempts already made and whatever results did come back.',
 "svg": """<rect class="tint" x="10" y="62" width="56" height="44" rx="4"/>
<path class="acc" d="M20 88 q12 -16 26 -4 M40 78 l7 6 -9 3"/>
<text class="lbl" x="38" y="102" text-anchor="middle">retry</text>
<path d="M70 76 h8"/>
<rect class="paper" x="80" y="58" width="30" height="34" rx="2"/>
<line class="thin" x1="86" y1="70" x2="104" y2="70"/>
<line class="thin" x1="86" y1="80" x2="100" y2="80"/>
<path class="acc" d="M110 74 h14 v-26 M118 54 l6 -6 6 6"/>
<rect class="tint" x="100" y="14" width="48" height="30" rx="4"/>
<line class="dash thin" x1="44" y1="60" x2="100" y2="36"/>
<line class="no" x1="64" y1="42" x2="80" y2="58"/>
<line class="no" x1="80" y1="42" x2="64" y2="58"/>""",
},
{
 'id': 'D5-16',
 'title': 'Coverage annotations in the synthesis',
 'concept': 'Synthesis output carries coverage annotations marking which findings are well supported and which topic areas have gaps because a source was unavailable.',
 'tested': 'A subagent times out, the coordinator proceeds with partial results, and the question asks what the final output must carry. The answer annotates coverage: which findings are well supported, and which topics are thin because a source could not be reached. Distractors present the partial synthesis as a finished report, or terminate the whole workflow on the one failure.',
 'remember': 'Partial results ship with the gap named. A coverage annotation marks each finding as well supported or as thin because a source was unavailable.',
 'alt': 'Report rows: three supported findings and one dashed row marked gap',
 'analogy': 'The discharge summary says which results are back and which bloods the lab could not run, so the doctor taking over knows what is missing. A summary listing only the tests that returned reads as a full workup.',
 "svg": """<rect class="paper" x="30" y="18" width="100" height="90" rx="3"/>
<rect class="tint" x="66" y="10" width="28" height="12" rx="3"/>
<line x1="42" y1="36" x2="102" y2="36"/>
<circle class="accfill" cx="36" cy="52" r="3"/><line class="thin" x1="44" y1="52" x2="104" y2="52"/>
<circle class="accfill" cx="36" cy="66" r="3"/><line class="thin" x1="44" y1="66" x2="104" y2="66"/>
<circle class="accfill" cx="36" cy="80" r="3"/><line class="thin" x1="44" y1="80" x2="104" y2="80"/>
<circle class="acc" cx="36" cy="96" r="3"/><line class="dash acc" x1="44" y1="96" x2="104" y2="96"/>
<text class="lbl" x="110" y="100">gap</text>""",
},
{
 'id': 'D5-17',
 'title': 'Context degradation in long sessions',
 'concept': 'In an extended session the model starts giving inconsistent answers and referencing typical patterns rather than the specific classes it discovered earlier.',
 'tested': 'Two hours into a codebase exploration the answers stop matching earlier ones and generic talk of typical patterns replaces the classes the session had named; the question asks the cause or the first response. The cause is context degradation over the length of the session. The distractor family reaches for a bigger context window or a stronger model instead of persisting the findings outside the session.',
 'remember': 'Late-session inconsistency, plus typical patterns where specific names used to appear, is context degradation. The findings have to live outside the session.',
 'alt': 'Chart trace turns from a specific zigzag into a flat dashed line',
 'analogy': "Late in a long shift the doctor's recall of one patient's actual numbers softens into what a case like this usually looks like. The chart at the foot of the bed still holds the specific values.",
 "svg": """<rect class="paper" x="14" y="20" width="132" height="80" rx="3"/>
<polyline class="acc" points="24,84 38,58 52,74 66,52"/>
<circle class="accfill" cx="24" cy="84" r="3"/>
<line class="dash thin" x1="76" y1="26" x2="76" y2="94"/>
<polyline class="dash" points="84,68 100,68 116,68 134,68"/>
<circle class="thin" cx="126" cy="38" r="10"/>
<path class="thin" d="M126 38 V32 M126 38 l6 3"/>
<text class="lbl" x="34" y="38">spec</text>
<text class="lbl" x="92" y="54">typ</text>""",
},
{
 'id': 'D5-18',
 'title': 'Scratchpad files persist findings across context boundaries',
 'concept': 'Agents write key findings to a scratchpad file and read it back when answering later questions, so the findings survive context boundaries.',
 'tested': "A long investigation whose later answers no longer match what was found earlier, and the question asks what holds the findings. The answer has the agent maintain a scratchpad file of key findings and reference it for subsequent questions. Distractors reach for a bigger context window or leave the findings in the session's own context.",
 'remember': 'Findings that must outlive the window go to a file, read back at each continuation. Compaction compresses what is in the session; the file keeps the finding exact.',
 'alt': 'A session box writes findings to a notes file and reads them back',
 'analogy': "The notes file the doctor keeps at the desk holds the specific findings: which drug the patient reacted to, which line is in which arm. Every return to that bed starts by reading the file, so the ward does not run on anyone's memory of a twelve-hour shift.",
 "svg": """<rect class="dash" x="12" y="18" width="58" height="86" rx="4"/>
<line class="thin" x1="22" y1="38" x2="60" y2="38"/>
<line class="thin" x1="22" y1="50" x2="60" y2="50"/>
<line class="thin" x1="22" y1="62" x2="60" y2="62"/>
<rect class="tint" x="94" y="26" width="52" height="76" rx="3"/>
<line class="thin" x1="102" y1="46" x2="138" y2="46"/>
<line class="thin" x1="102" y1="58" x2="138" y2="58"/>
<line class="thin" x1="102" y1="70" x2="138" y2="70"/>
<path class="acc" d="M74 44 h14 M84 39 l5 5 -5 5"/>
<path class="acc" d="M90 78 h-14 M80 73 l-5 5 5 5"/>
<text class="lbl" x="120" y="20" text-anchor="middle">file</text>""",
},
{
 'id': 'D5-19',
 'title': 'Delegate verbose exploration; the main agent coordinates',
 'concept': 'Subagents are spawned to investigate specific questions such as finding all test files or tracing refund flow dependencies, isolating their verbose output while the main agent coordinates.',
 'tested': 'A multi-phase task whose discovery output would fill the main window before implementation begins, and the question asks how to preserve the main context. The answer spawns a subagent per question and takes back a concise summary, so the verbose output never reaches the main window. The paired option is `/compact`, which the guide lists for reducing usage once a session has already filled.',
 'remember': "One question per subagent; the summary comes back and the main agent stays at coordination level. Isolation prevents the window filling; `/compact` is the guide's remedy once it has.",
 'alt': 'Main whiteboard receives one card from a subagent buried in charts',
 'analogy': "The registrar is sent to work through one patient's old notes and comes back with the two lines that matter, rather than wheeling the whole file trolley onto the round. The consultant leading the round keeps the picture of every bed.",
 "svg": """<text class="lbl" x="34" y="24" text-anchor="middle">main</text>
<rect class="tint" x="10" y="30" width="48" height="40" rx="3"/>
<line class="thin" x1="18" y1="46" x2="50" y2="46"/>
<line class="thin" x1="18" y1="58" x2="40" y2="58"/>
<circle cx="98" cy="30" r="8"/>
<path d="M98 38 v14 M88 44 h20"/>
<rect class="tint" x="108" y="92" width="38" height="8"/>
<rect class="tint" x="112" y="82" width="32" height="8"/>
<rect class="tint" x="106" y="72" width="36" height="8"/>
<rect class="tint" x="110" y="62" width="30" height="8"/>
<rect class="tint" x="114" y="52" width="28" height="8"/>
<rect class="acc" x="70" y="40" width="16" height="12" rx="2"/>
<path class="acc" d="M68 46 h-8 M64 42 l-4 4 4 4"/>""",
},
{
 'id': 'D5-20',
 'title': 'Summarise a phase before spawning the next',
 'concept': "Key findings from one exploration phase are summarised before the next phase's sub-agents are spawned, and that summary is injected into their initial context.",
 'tested': "A multi-phase exploration where the second phase's agents lack what the first phase established, and the question asks the design. The answer summarises phase one and injects the summary into the next phase's initial context. Distractors rely on automatic context inheritance, or hand the next phase the full verbose output of the first.",
 'remember': "Between phases: summarise, then inject into the next agents' initial context. A fresh subagent inherits nothing, so the summary is what it is given.",
 'alt': 'Phase one summarised into a sheet injected into phase two agents',
 'analogy': 'The handover is written up before the incoming team is called in, and each doctor arriving is handed it. Nobody on the new shift is expected to have overheard the previous round.',
 "svg": """<text class="lbl" x="24" y="22" text-anchor="middle">P1</text>
<rect class="tint" x="10" y="28" width="28" height="30" rx="2"/>
<rect class="tint" x="10" y="70" width="28" height="30" rx="2"/>
<path d="M44 64 h12 M52 59 l5 5 -5 5"/>
<rect class="acc" x="62" y="44" width="32" height="40" rx="2"/>
<line class="acc thin" x1="70" y1="58" x2="86" y2="58"/>
<line class="acc thin" x1="70" y1="70" x2="86" y2="70"/>
<text class="lbl" x="132" y="22" text-anchor="middle">P2</text>
<rect class="dash" x="116" y="28" width="30" height="30" rx="2"/>
<rect class="dash" x="116" y="70" width="30" height="30" rx="2"/>
<line class="acc thin" x1="98" y1="56" x2="112" y2="46"/>
<circle class="accfill" cx="114" cy="45" r="3"/>
<line class="acc thin" x1="98" y1="72" x2="112" y2="82"/>
<circle class="accfill" cx="114" cy="83" r="3"/>""",
},
{
 'id': 'D5-21',
 'title': 'Crash recovery: state exports plus a manifest',
 'concept': 'Each agent exports its state to a known location, and on resume the coordinator loads a manifest and injects the persisted findings into agent prompts.',
 'tested': "A long multi-agent run dies partway through and the question asks how the completed work survives. The answer has each agent export structured state to a known location, with a manifest the coordinator reads on resume and injects into prompts. Distractors rely on the interrupted run's own context still being available to the new one, or re-run the whole investigation from the start.",
 'remember': "Agents write state to a known path; the coordinator reads the manifest on resume and injects it. Assuming the dead run's own context is still available is the distractor.",
 'alt': 'Status board read on resume; the lost in-session memory is crossed out',
 'analogy': "The board at the nurses' station carries each bed's status, so the doctor arriving after the power cut resumes from what is written. Nothing on the ward depends on someone remembering the last four hours.",
 "svg": """<rect class="tint" x="10" y="14" width="80" height="62" rx="4"/>
<line x1="10" y1="30" x2="90" y2="30"/>
<text class="lbl" x="50" y="26" text-anchor="middle">state</text>
<circle class="accfill" cx="20" cy="42" r="3"/><line class="thin" x1="28" y1="42" x2="80" y2="42"/>
<circle class="accfill" cx="20" cy="56" r="3"/><line class="thin" x1="28" y1="56" x2="80" y2="56"/>
<circle class="acc" cx="20" cy="70" r="3"/><line class="dash thin" x1="28" y1="70" x2="80" y2="70"/>
<path class="acc" d="M96 42 h14 M104 36 l6 6 -6 6"/>
<circle cx="128" cy="32" r="8"/>
<path d="M128 40 v16 M118 46 h20"/>
<rect class="dash" x="14" y="88" width="46" height="20" rx="3"/>
<line class="no" x1="19" y1="92" x2="55" y2="104"/>
<line class="no" x1="55" y1="92" x2="19" y2="104"/>""",
},
{
 'id': 'D5-22',
 'title': '/compact when discovery output fills the window',
 'concept': '`/compact` reduces context usage during an extended exploration session when the window has filled with verbose discovery output.',
 'tested': '`/compact` sits on both sides of the same distinction. When a session has already filled with verbose discovery output and the work must continue, it is the in-session lever. When the question is how to keep that output out of the main window in the first place, the Explore subagent is the stronger answer, because it prevents the filling rather than compressing after it.',
 'remember': '`/compact` shrinks a session already full of discovery output, which is what the guide lists it for. Where the choice is still open, isolate discovery in a subagent instead.',
 'alt': 'A long notes page compacted into a short one; detail falls away',
 'analogy': 'When the notes file has grown too long to work from, the doctor rewrites it shorter and carries on. Detail goes out with the rewrite, so anything that has to stay exact belongs somewhere the trimming does not reach.',
 "svg": """<rect class="tint" x="12" y="12" width="50" height="96" rx="3"/>
<line class="thin" x1="20" y1="30" x2="54" y2="30"/>
<line class="thin" x1="20" y1="44" x2="54" y2="44"/>
<line class="thin" x1="20" y1="58" x2="54" y2="58"/>
<line class="thin" x1="20" y1="72" x2="54" y2="72"/>
<line class="thin" x1="20" y1="86" x2="54" y2="86"/>
<text class="lbl" x="80" y="42" text-anchor="middle">/comp</text>
<path class="acc" d="M70 58 h16 M80 52 l6 6 -6 6"/>
<rect class="acc" x="96" y="30" width="50" height="44" rx="3"/>
<line class="thin" x1="104" y1="46" x2="138" y2="46"/>
<line class="thin" x1="104" y1="60" x2="138" y2="60"/>
<line class="dash thin" x1="104" y1="88" x2="128" y2="88"/>
<line class="dash thin" x1="112" y1="100" x2="136" y2="100"/>""",
},
{
 'id': 'D5-23',
 'title': '97% overall can hide a bad segment',
 'concept': 'An aggregate accuracy figure such as 97% overall can mask poor performance on one document type or field, so accuracy is validated by segment before high-confidence extractions are automated.',
 'tested': 'An extraction system reports 97% overall accuracy and the team proposes auto-processing everything above the confidence threshold; the question asks the first step. The answer analyses accuracy by document type and by field, so every segment is shown to meet the bar on its own. The distractor family trusts the aggregate: auto-process on the overall number, or raise the threshold without ever breaking the number down.',
 'remember': 'An aggregate can mask a bad segment. Break accuracy down by document type and by field before reducing human review.',
 'alt': 'Five accuracy bars under one dashed average; one accent bar falls short',
 'analogy': "The ward's overall infection figure looks acceptable while one bay accounts for most of the cases. The audit is run department by department, because the hospital average is the number that hides it.",
 "svg": """<line x1="14" y1="100" x2="148" y2="100"/>
<line class="dash" x1="14" y1="40" x2="148" y2="40"/>
<text class="lbl" x="28" y="32" text-anchor="middle">97%</text>
<rect class="tint" x="22" y="44" width="18" height="56"/>
<rect class="tint" x="48" y="42" width="18" height="58"/>
<rect class="tint" x="74" y="46" width="18" height="54"/>
<rect class="acc" x="100" y="74" width="18" height="26"/>
<rect class="tint" x="126" y="44" width="18" height="56"/>""",
},
{
 'id': 'D5-24',
 'title': 'Stratified random sampling of high-confidence output',
 'concept': 'Stratified random sampling of high-confidence extractions measures the error rate of the automated path and detects novel error patterns.',
 'tested': 'A pipeline auto-processes its high-confidence extractions and the question asks what ongoing measurement to keep. The answer samples that high-confidence stream at random, stratified across document types and field categories. Distractors review only the low-confidence queue, or sample a flat percentage without stratifying, which leaves the automated path unmeasured and the rare segments under-sampled.',
 'remember': 'Keep sampling the confident output, stratified across document types and fields. Reviewing only what the model flagged low measures nothing about the automated path.',
 'alt': 'One chart sampled from every bay, collected into a review tray',
 'analogy': 'The ward pulls a set number of charts from every bay each week, including the ones nobody flagged, because an error nobody has noticed shows up no other way. Reading only the charts already marked doubtful leaves the routine ones unread.',
 "svg": """<rect class="tint" x="14" y="18" width="14" height="20" rx="2"/>
<rect class="tint" x="32" y="18" width="14" height="20" rx="2"/>
<rect class="acc" x="50" y="18" width="14" height="20" rx="2"/>
<rect class="tint" x="14" y="46" width="14" height="20" rx="2"/>
<rect class="acc" x="32" y="46" width="14" height="20" rx="2"/>
<rect class="tint" x="50" y="46" width="14" height="20" rx="2"/>
<rect class="acc" x="14" y="74" width="14" height="20" rx="2"/>
<rect class="tint" x="32" y="74" width="14" height="20" rx="2"/>
<rect class="tint" x="50" y="74" width="14" height="20" rx="2"/>
<path class="acc" d="M72 56 h14 M80 50 l6 6 -6 6"/>
<rect class="tint" x="94" y="34" width="50" height="46" rx="3"/>
<rect class="acc" x="102" y="42" width="12" height="14" rx="2"/>
<rect class="acc" x="118" y="42" width="12" height="14" rx="2"/>
<rect class="acc" x="110" y="60" width="12" height="14" rx="2"/>""",
},
{
 'id': 'D5-25',
 'title': 'Field-level confidence, calibrated on labeled data, routes review',
 'concept': 'Models output a confidence score for each field, review thresholds are calibrated against a labeled validation set, and low-confidence or contradictory-source extractions are routed to human review.',
 'tested': 'A high-volume extraction pipeline has more documents than reviewers, and the question asks how to direct the limited review capacity. The answer scores confidence per field, calibrates the threshold on a labeled validation set, and routes low-confidence or ambiguous-source extractions to people. Distractors take raw self-reported confidence at face value, produce one score per document, or send every document to review.',
 'remember': 'Per field, not per document. Calibrate the threshold on a labeled validation set; route low confidence and contradictory sources to a human.',
 'alt': 'Per-field confidence marks; the low one routes to a human reviewer',
 'analogy': "Each value on the lab panel carries its own flag rather than one verdict for the whole sheet, and the flag levels were set against samples whose answers were already known. The reviewer's time goes to the flagged values and to specimens whose labels disagree.",
 "svg": """<rect class="paper" x="12" y="16" width="76" height="88" rx="3"/>
<line class="thin" x1="20" y1="34" x2="60" y2="34"/><rect class="tint" x="66" y="29" width="14" height="8" rx="2"/>
<line class="thin" x1="20" y1="52" x2="60" y2="52"/><rect class="tint" x="66" y="47" width="14" height="8" rx="2"/>
<line class="thin" x1="20" y1="70" x2="60" y2="70"/><rect class="acc" x="66" y="65" width="14" height="8" rx="2"/>
<line class="thin" x1="20" y1="88" x2="60" y2="88"/><rect class="tint" x="66" y="83" width="14" height="8" rx="2"/>
<path class="acc" d="M94 70 h14 M102 64 l6 6 -6 6"/>
<circle cx="128" cy="46" r="9"/>
<path d="M128 55 v16 M116 62 h24"/>""",
},
{
 'id': 'D5-26',
 'title': 'Claim-source mappings survive synthesis',
 'concept': 'Subagents output structured claim-source mappings, giving the source URL or document name and the relevant excerpt, which the synthesis agent preserves and merges rather than compressing away.',
 'tested': 'A final report states figures that cannot be traced back to any source, and the question asks where the attribution went or how to keep it. The answer requires structured claim-source mappings from the subagents, preserved by downstream agents through synthesis. Distractors compress the mapping away and append a general bibliography, or re-derive attributions by searching the sources again at the end.',
 'remember': 'Attribution is lost at the summarisation step, so claim, excerpt and source travel together through synthesis. A bibliography at the end leaves individual claims untraceable.',
 'alt': 'Each claim keeps its source dot through synthesis into the report',
 'analogy': 'Every entry in the notes records who reported it and what they said, and the discharge summary carries that attribution forward. A list of everyone seen that day, appended at the end, does not say which of them reported the fever.',
 "svg": """<rect class="tint" x="10" y="14" width="34" height="16" rx="2"/><circle class="accfill" cx="54" cy="22" r="4"/>
<rect class="tint" x="10" y="50" width="34" height="16" rx="2"/><circle class="accfill" cx="54" cy="58" r="4"/>
<rect class="tint" x="10" y="86" width="34" height="16" rx="2"/><circle class="accfill" cx="54" cy="94" r="4"/>
<path d="M64 58 h12 M72 53 l5 5 -5 5"/>
<rect class="paper" x="86" y="14" width="60" height="88" rx="3"/>
<line class="thin" x1="94" y1="34" x2="126" y2="34"/><circle class="accfill" cx="134" cy="34" r="4"/>
<line class="thin" x1="94" y1="58" x2="126" y2="58"/><circle class="accfill" cx="134" cy="58" r="4"/>
<line class="thin" x1="94" y1="82" x2="126" y2="82"/><circle class="accfill" cx="134" cy="82" r="4"/>""",
},
{
 'id': 'D5-27',
 'title': 'Conflicting figures: keep both, attribute both',
 'concept': 'When credible sources give different statistics, the analysis is completed with both values included and the conflict annotated with source attribution, leaving the coordinator to reconcile.',
 'tested': 'A document-analysis agent finds a government report at 40% growth and an industry analysis at 12%, both credible, and the question asks what it should do. The answer finishes the analysis with both values, marks the conflict with its source attribution, and passes reconciliation to the coordinator. Distractors pick one of the two values by heuristic, or stop and ask the coordinator before completing the analysis.',
 'remember': 'Do not choose a value. Carry both with their sources and mark the conflict; stopping mid-analysis to ask the coordinator is the other distractor.',
 'alt': 'Both conflicting figures kept with source dots; picking one is crossed out',
 'analogy': 'Two readings of the same measurement both go on the chart, each with the time and the person who took it, and which one to act on goes to the consultant. Rubbing one out because it looks less likely removes the evidence that decision needs.',
 "svg": """<rect class="paper" x="10" y="16" width="78" height="64" rx="3"/>
<circle class="accfill" cx="20" cy="36" r="3"/>
<line class="thin" x1="28" y1="36" x2="52" y2="36"/>
<text class="lbl" x="60" y="40">40%</text>
<circle class="accfill" cx="20" cy="58" r="3"/>
<line class="thin" x1="28" y1="58" x2="52" y2="58"/>
<text class="lbl" x="60" y="62">12%</text>
<path class="acc" d="M92 36 h8 v22 h-8 M100 47 h10"/>
<circle cx="126" cy="36" r="9"/>
<path d="M126 45 v14 M114 51 h24"/>
<rect class="dash" x="14" y="88" width="44" height="20" rx="3"/>
<line class="no" x1="19" y1="92" x2="53" y2="104"/>
<line class="no" x1="53" y1="92" x2="19" y2="104"/>""",
},
{
 'id': 'D5-28',
 'title': 'Well-established and contested findings in separate sections',
 'concept': "Reports carry explicit sections separating well-established findings from contested ones, keeping each source's original characterisation and its methodological context.",
 'tested': "A synthesis flattens strong evidence and disputed claims into one confident narrative, and the question asks how to structure the report. The answer gives well-established and contested findings their own sections and keeps the sources' own characterisations and methodological context. Distractors normalise every finding into one confident format, or drop the methodology note as detail.",
 'remember': "Two named sections: well-established and contested. The source's own hedging and its methodology travel with the finding rather than being smoothed out.",
 'alt': 'One report split into ticked established rows and dashed contested rows',
 'analogy': 'The notes keep what is confirmed apart from what is still suspected, and each entry keeps the wording of the doctor who wrote it, including how the finding was reached. Merged into one list, the suspicions read as settled.',
 "svg": """<rect class="paper" x="24" y="12" width="112" height="96" rx="3"/>
<line x1="24" y1="60" x2="136" y2="60"/>
<path class="acc" d="M34 32 l4 5 8 -10"/>
<line class="thin" x1="52" y1="32" x2="124" y2="32"/>
<path class="acc" d="M34 48 l4 5 8 -10"/>
<line class="thin" x1="52" y1="48" x2="124" y2="48"/>
<text class="lbl" x="38" y="82" text-anchor="middle">?</text>
<line class="dash thin" x1="52" y1="78" x2="124" y2="78"/>
<text class="lbl" x="38" y="98" text-anchor="middle">?</text>
<line class="dash thin" x1="52" y1="94" x2="124" y2="94"/>""",
},
{
 'id': 'D5-29',
 'title': 'Dates in every structured output',
 'concept': 'Structured outputs carry publication or data-collection dates, so that differences between time periods are not read as contradictions.',
 'tested': 'Two credible sources give different figures for the same measure and the pipeline reports a contradiction; the question asks what the outputs are missing. The answer requires publication or collection dates in every structured output, so 10% in one year and 15% in the next reads as change over time. Distractors flag every numeric disagreement as a conflict, or pick one of the two values.',
 'remember': 'Every finding carries its date. Without one, a year of change between two sources is reported as a disagreement.',
 'alt': 'Two dated lab values; an undated third value is crossed out',
 'analogy': 'Every lab value on the chart is stamped with when the sample was taken, so a rising figure reads as a trend rather than two departments contradicting each other. An undated value cannot be set against the one before it.',
 "svg": """<rect class="paper" x="10" y="16" width="126" height="86" rx="3"/>
<line class="thin" x1="20" y1="38" x2="58" y2="38"/>
<text class="lbl" x="66" y="42">10%</text>
<circle class="acc" cx="112" cy="38" r="9"/>
<path class="acc" d="M112 38 v-5 M112 38 l4 3"/>
<line class="thin" x1="20" y1="62" x2="58" y2="62"/>
<text class="lbl" x="66" y="66">15%</text>
<circle class="acc" cx="112" cy="62" r="9"/>
<path class="acc" d="M112 62 v-5 M112 62 l4 3"/>
<line class="dash thin" x1="20" y1="86" x2="58" y2="86"/>
<circle class="dash" cx="112" cy="86" r="9"/>
<line class="no" x1="106" y1="80" x2="118" y2="92"/>
<line class="no" x1="118" y1="80" x2="106" y2="92"/>""",
},
{
 'id': 'D5-30',
 'title': 'Render each content type in its natural form',
 'concept': 'Synthesis output renders financial data as tables, news and analysis as prose, and technical findings as structured lists, rather than converting everything to one uniform format.',
 'tested': 'A synthesis agent converts every finding to uniform narrative prose for consistency, and the question asks the cost or the alternative. The answer renders each content type in its own form: tables for financial data, prose for news and analysis, structured lists for technical findings. The distractor is the single uniform format, which leaves tabular figures imprecise and harder to verify.',
 'remember': 'Tables for figures, prose for news and analysis, lists for technical findings. One uniform format, chosen for consistency, is the distractor.',
 'alt': 'Table, prose and list panels; a uniform-format panel is crossed out',
 'analogy': 'The chart keeps observations in a table, the round note in prose, and the drug list as a list, because each is read differently at the bedside. Written out as a paragraph, an observation that was checked at a glance has to be hunted for.',
 "svg": """<rect class="acc" x="12" y="14" width="46" height="36" rx="2"/>
<line class="acc thin" x1="12" y1="28" x2="58" y2="28"/>
<line class="acc thin" x1="35" y1="14" x2="35" y2="50"/>
<rect class="tint" x="12" y="62" width="46" height="36" rx="2"/>
<line class="thin" x1="18" y1="74" x2="52" y2="74"/>
<line class="thin" x1="18" y1="82" x2="52" y2="82"/>
<line class="thin" x1="18" y1="90" x2="46" y2="90"/>
<rect class="tint" x="94" y="14" width="46" height="36" rx="2"/>
<circle cx="102" cy="26" r="2"/><line class="thin" x1="108" y1="26" x2="134" y2="26"/>
<circle cx="102" cy="38" r="2"/><line class="thin" x1="108" y1="38" x2="134" y2="38"/>
<path class="thin" d="M64 46 L86 62 M86 62 l-8 1 M86 62 l-1 -8"/>
<rect class="dash" x="94" y="62" width="46" height="36" rx="2"/>
<line class="thin" x1="100" y1="72" x2="134" y2="72"/>
<line class="thin" x1="100" y1="80" x2="134" y2="80"/>
<line class="thin" x1="100" y1="88" x2="128" y2="88"/>
<line class="no" x1="100" y1="68" x2="134" y2="92"/>
<line class="no" x1="134" y1="68" x2="100" y2="92"/>""",
},
]
