# Domain 1 — Agentic Architecture & Orchestration · building: the control tower
# Generated by merge_parts.py from the authoring halves — edit the halves, not this file.

ITEMS = [
{
 'id': 'D1-01',
 'title': 'The agentic loop runs on stop_reason',
 'concept': 'After each API call the orchestrator reads `stop_reason`: `tool_use` means execute the requested tools, append the results and call Claude again; `end_turn` means the loop stops.',
 'tested': "Implementation questions give you a loop and ask what the continue-or-stop decision keys on. The correct option branches on `stop_reason`; the distractor reads Claude's text for a completion phrase, which is probabilistic control where a deterministic field already exists.",
 'remember': '`tool_use` → run the tool, append the result, go round again. `end_turn` → stop and return. The field is the signal; the text is not.',
 'alt': 'Flight strip with one arrow looping back and one leaving',
 'analogy': 'Every call from an aircraft ends with one entry on the flight strip: another circuit, or cleared to land. The controller acts on that entry, and a pilot who sounds finished but has not been cleared flies the pattern again.',
 "svg": """<path class="tint" d="M22 104 L26 66 H38 L42 104 Z"/>
<rect class="tint" x="16" y="48" width="32" height="18" rx="4"/>
<path d="M20 48 L24 38 H40 L44 48"/>
<rect class="paper" x="66" y="40" width="52" height="38" rx="3"/>
<line class="thin" x1="74" y1="52" x2="110" y2="52"/>
<line class="thin" x1="74" y1="62" x2="98" y2="62"/>
<path class="acc" d="M118 50 h20 M132 45 l6 5 -6 5"/>
<text class="lbl" x="130" y="34" text-anchor="middle">end</text>
<path class="acc" d="M92 78 v18 H58 V56 h8 M60 51 l6 5 -6 5"/>
<text class="lbl" x="78" y="106" text-anchor="middle">tool</text>""",
},
{
 'id': 'D1-02',
 'title': 'Tool results are appended to the conversation',
 'concept': 'Each tool result is appended to the message history as a `tool_result` block, so the next request carries it and the model reasons over the new information.',
 'tested': "Loop-construction questions ask what has to happen between two iterations. The correct option appends the tool result to the conversation history before the next request; distractors hold the result only in the application's own state, leaving the next iteration to reason without it.",
 'remember': 'Run the tool, append the result to the messages, then call again. Anything the next iteration must reason over has to be in the conversation history.',
 'alt': 'Message stack with the newest block accented, fed by a tool box',
 'analogy': "Every readback the controller takes goes onto the flight strip before the next instruction is issued, so the strip alone carries the picture. A detail kept in the controller's head is not on the strip, and the next decision is made without it.",
 "svg": """<rect class="tint" x="26" y="18" width="56" height="14" rx="2"/>
<rect class="tint" x="26" y="38" width="56" height="14" rx="2"/>
<rect class="tint" x="26" y="58" width="56" height="14" rx="2"/>
<rect class="acc" x="26" y="78" width="56" height="14" rx="2"/>
<path class="acc" d="M116 85 h-22 M100 80 l-6 5 6 5"/>
<rect class="tint" x="116" y="70" width="28" height="30" rx="3"/>
<path class="thin" d="M124 80 h12 M124 88 h12"/>
<text class="lbl" x="54" y="106" text-anchor="middle">msgs</text>""",
},
{
 'id': 'D1-03',
 'title': 'Model-driven decisions, not a hard-coded decision tree',
 'concept': 'In an agentic system Claude reasons from context about which tool to call next, which is what separates it from a pre-configured decision tree or fixed tool sequence.',
 'tested': "Reliability scenarios offer a deterministic front end: a routing layer that parses each request and pre-selects the tool, or a classifier that enables only a subset of tools. The official rationale calls the routing layer over-engineered because it bypasses the model's own language understanding, and the classifier a fix to tool availability rather than to the stated problem.",
 'remember': "Claude picks the next tool from context. A keyword router or pre-set sequence is the over-engineering distractor: it bypasses the model's language understanding.",
 'alt': 'Fixed tool chain crossed out; a hub choosing one of three tools',
 'analogy': 'The controller sequences aircraft from the picture in front of them — weather, fuel states, what is already on the runway — rather than working down an order printed that morning. A tower running the printed order would keep issuing it while the runway is blocked.',
 "svg": """<rect class="tint" x="16" y="20" width="26" height="18" rx="3"/>
<path class="thin" d="M42 29 h12 M50 25 l4 4 -4 4"/>
<rect class="tint" x="54" y="20" width="26" height="18" rx="3"/>
<path class="thin" d="M80 29 h12 M88 25 l4 4 -4 4"/>
<rect class="tint" x="92" y="20" width="26" height="18" rx="3"/>
<line class="no" x1="48" y1="16" x2="86" y2="42"/>
<line class="no" x1="86" y1="16" x2="48" y2="42"/>
<circle class="accfill" cx="66" cy="72" r="9"/>
<circle class="tint" cx="24" cy="100" r="8"/>
<circle class="tint" cx="66" cy="102" r="8"/>
<circle class="tint" cx="108" cy="100" r="8"/>
<line class="dash thin" x1="59" y1="79" x2="31" y2="93"/>
<line class="acc" x1="66" y1="81" x2="66" y2="94"/>
<line class="dash thin" x1="73" y1="79" x2="101" y2="93"/>""",
},
{
 'id': 'D1-04',
 'title': 'Loop-termination anti-patterns',
 'concept': 'Loop termination keys on `stop_reason`; parsing natural-language signals, an arbitrary iteration cap as the primary stopping mechanism, and checking for assistant text are the named anti-patterns.',
 'tested': 'A loop that runs on past the work, or stops before it, is shown and the question asks which change fixes it. The distractor family is probabilistic control where a deterministic field already exists: matching a completion phrase in the response text, or capping iterations and calling that the stopping condition. Read the cap option closely — a cap is an anti-pattern as the primary stopping mechanism.',
 'remember': 'Only `stop_reason` ends the loop. Text matching, assistant-text presence and an iteration cap as the primary mechanism are the three named anti-patterns.',
 'alt': 'Three crossed-out signals; only the stop arrow reaches the exit',
 'analogy': 'The strip is closed by the clearance, not by a pilot who sounds finished, and not by counting how many circuits they have flown. An aircraft on its fifth lap can still be waiting for the runway.',
 "svg": """<rect class="tint" x="14" y="16" width="40" height="16" rx="3"/>
<text class="lbl" x="34" y="28" text-anchor="middle">done</text>
<rect class="tint" x="14" y="40" width="40" height="16" rx="3"/>
<text class="lbl" x="34" y="52" text-anchor="middle">cap</text>
<rect class="tint" x="14" y="64" width="40" height="16" rx="3"/>
<text class="lbl" x="34" y="76" text-anchor="middle">text</text>
<path class="thin" d="M54 24 H66 V72 H54"/>
<path class="thin" d="M66 48 h20"/>
<line class="no" x1="82" y1="40" x2="96" y2="56"/>
<line class="no" x1="96" y1="40" x2="82" y2="56"/>
<rect class="dash" x="116" y="34" width="30" height="70" rx="3"/>
<path class="acc" d="M40 96 H112 M104 90 l8 6 -8 6"/>
<text class="lbl" x="70" y="90" text-anchor="middle">stop</text>""",
},
{
 'id': 'D1-05',
 'title': 'Hub-and-spoke: every message goes through the coordinator',
 'concept': 'In a coordinator–subagent system all communication, error handling and information routing pass through the coordinator; subagents do not talk to each other.',
 'tested': 'A design question offers a shortcut — letting the synthesis agent query the search agent directly, or agents sharing a channel — against routing through the coordinator. The shortcut option loses observability and uniform error handling; the coordinator route is the answer even when it costs a round trip.',
 'remember': 'Coordinator = hub. Subagent-to-subagent links are the distractor. Round trips are the price of observability and controlled information flow.',
 'alt': 'Four aircraft linked to a central tower; a direct plane-to-plane line is crossed out',
 'analogy': 'Pilots on approach never coordinate with each other; each talks only to the tower, and the tower sequences everyone. If two pilots agreed a plan on a private channel, the controller would lose the picture and could not recover the sequence when something went wrong.',
 "svg": """<circle class="accfill" cx="80" cy="60" r="12"/>
<circle class="tint" cx="30" cy="28" r="10"/><circle class="tint" cx="130" cy="28" r="10"/><circle class="tint" cx="30" cy="94" r="10"/><circle class="tint" cx="130" cy="94" r="10"/>
<line x1="38" y1="34" x2="70" y2="53"/><line x1="122" y1="34" x2="90" y2="53"/><line x1="38" y1="88" x2="70" y2="67"/><line x1="122" y1="88" x2="90" y2="67"/>
<line class="dash thin" x1="42" y1="28" x2="118" y2="28"/><line class="no" x1="72" y1="20" x2="88" y2="36"/><line class="no" x1="88" y1="20" x2="72" y2="36"/>""",
},
{
 'id': 'D1-06',
 'title': 'Subagents start with an empty context',
 'concept': "A subagent does not inherit the coordinator's conversation history or share memory between invocations, so every finding it needs must be written into its prompt.",
 'tested': "The synthesis subagent produces work that ignores what search and analysis already found, and the question asks for the fix. The answer puts the complete prior findings inside the synthesis subagent's prompt. Distractors assume an inheritance that does not exist: telling the subagent to refer back to earlier results, or relying on memory shared between invocations.",
 'remember': "Nothing is inherited. Whatever the subagent must reason over goes into its prompt in full, prior agents' findings included.",
 'alt': 'Tower hands a written sheet to a plane; inherited history crossed out',
 'analogy': "A crew boarding for the next leg knows only what is on the sheet handed to them; nothing carries over from the aircraft's last flight. If the controller wants them acting on what an earlier crew reported, it goes on the sheet.",
 "svg": """<path class="tint" d="M22 100 L26 62 H38 L42 100 Z"/>
<rect class="tint" x="16" y="44" width="32" height="18" rx="4"/>
<path d="M20 44 L24 34 H40 L44 44"/>
<rect class="acc" x="58" y="40" width="24" height="30" rx="2"/>
<path class="acc thin" d="M64 50 h12 M64 60 h12"/>
<path class="acc" d="M84 55 h16 M96 50 l5 5 -5 5"/>
<path class="tint" d="M106 56 h30 l12 -6 v12 l-12 -6"/>
<path d="M118 56 l-8 -14 h8 l12 14 M118 56 l-8 14 h8 l12 -14"/>
<rect class="dash" x="104" y="84" width="46" height="20" rx="2"/>
<line class="dash thin" x1="48" y1="86" x2="100" y2="94"/>
<line class="no" x1="68" y1="84" x2="80" y2="96"/>
<line class="no" x1="80" y1="84" x2="68" y2="96"/>""",
},
{
 'id': 'D1-07',
 'title': 'The coordinator decomposes, delegates, aggregates — and chooses',
 'concept': 'The coordinator decomposes the task, decides which subagents this query needs, delegates to them and aggregates their results rather than routing every query through the full pipeline.',
 'tested': 'A design question asks what the coordinator is responsible for, or how to stop a system running every subagent on every query. The answer has the coordinator analyse the request and select the subagents it needs; distractors move that choice elsewhere, putting a routing model in front, or leave the full pipeline in place and optimise the subagents instead.',
 'remember': 'Four coordinator jobs: decompose, delegate, aggregate, and choose which subagents this query needs. Always running the full pipeline is the distractor.',
 'alt': 'Coordinator calls two of three subagents and merges their results',
 'analogy': 'The controller reads what the request needs and calls only the positions involved — one aircraft for a routine arrival, several for an unfolding situation. Working every position on every movement would fill the frequency without improving the outcome.',
 "svg": """<circle class="accfill" cx="28" cy="58" r="10"/>
<circle class="tint" cx="82" cy="22" r="9"/>
<circle class="tint" cx="82" cy="58" r="9"/>
<circle class="dash" cx="82" cy="94" r="9"/>
<line class="acc" x1="37" y1="53" x2="73" y2="28"/>
<line class="acc" x1="38" y1="58" x2="73" y2="58"/>
<line class="dash thin" x1="37" y1="64" x2="73" y2="89"/>
<path d="M91 26 L114 50"/>
<path d="M91 58 h23"/>
<rect class="tint" x="116" y="44" width="30" height="28" rx="3"/>
<path class="thin" d="M124 54 h14 M124 62 h14"/>""",
},
{
 'id': 'D1-08',
 'title': 'Narrow decomposition leaves coverage gaps',
 'concept': "When every subagent succeeds and the output still misses whole parts of the topic, the cause is the coordinator's task decomposition rather than subagent performance.",
 'tested': "The stem states that each subagent completed successfully, quotes the coordinator's log showing three subtasks drawn from one corner of the topic, and asks for the most likely root cause. The correct option names the coordinator's decomposition; the three distractors blame downstream agents that worked correctly inside the scope they were given.",
 'remember': "All subagents succeed, coverage is still partial → look at the coordinator's decomposition. Blaming search quality, synthesis gap-detection or analysis filters blames agents that did their job.",
 'alt': 'Radar circle with all three markers inside one quadrant',
 'analogy': "Three aircraft are sent to search, and all three fly their assigned boxes exactly, but every box was drawn in the same corner of the sea. The gap is in the plan on the controller's table, not in the flying.",
 "svg": """<circle class="dash" cx="80" cy="60" r="42"/>
<circle class="thin" cx="80" cy="60" r="24"/>
<line class="thin" x1="80" y1="18" x2="80" y2="102"/>
<line class="thin" x1="38" y1="60" x2="122" y2="60"/>
<path class="acc" d="M80 60 L80 18 A42 42 0 0 1 122 60 Z"/>
<circle class="accfill" cx="92" cy="34" r="3"/>
<circle class="accfill" cx="104" cy="46" r="3"/>
<circle class="accfill" cx="97" cy="55" r="3"/>""",
},
{
 'id': 'D1-09',
 'title': 'Partition scope so subagents do not duplicate work',
 'concept': 'The coordinator partitions the research space before delegating, assigning each subagent a distinct subtopic or source type.',
 'tested': 'Two subagents come back with overlapping findings and the question asks for the fix. The answer partitions the scope up front, one distinct subtopic or source type per agent. The distractor deduplicates the results after the fact, which leaves the same ground covered twice.',
 'remember': 'One distinct subtopic or source type per subagent, assigned before delegation. Deduplicating afterwards is the distractor: the tokens are already spent.',
 'alt': 'Three separated sectors each with one marker; overlapping circles crossed out',
 'analogy': 'The controller divides the search area into sectors and gives each crew one, so two aircraft never sweep the same water. Sorting out the overlap after everyone has landed does not buy back the fuel.',
 "svg": """<rect class="tint" x="14" y="30" width="56" height="60" rx="3"/>
<line class="thin" x1="14" y1="50" x2="70" y2="50"/>
<line class="thin" x1="14" y1="70" x2="70" y2="70"/>
<circle class="accfill" cx="42" cy="40" r="4"/>
<circle class="accfill" cx="42" cy="60" r="4"/>
<circle class="accfill" cx="42" cy="80" r="4"/>
<circle class="dash" cx="106" cy="52" r="20"/>
<circle class="dash" cx="126" cy="66" r="20"/>
<line class="no" x1="108" y1="52" x2="124" y2="66"/>
<line class="no" x1="124" y1="52" x2="108" y2="66"/>""",
},
{
 'id': 'D1-10',
 'title': 'Iterative refinement: evaluate, re-delegate, re-synthesise',
 'concept': 'The coordinator evaluates the synthesis output for gaps, re-delegates targeted queries to the search and analysis subagents, and re-invokes synthesis until coverage is sufficient.',
 'tested': 'A synthesis comes back with coverage gaps and the question asks what the architecture should do. The answer keeps gap evaluation with the coordinator, which sends targeted follow-up queries and re-runs synthesis. Distractors hand the synthesis agent its own search tools, breaking least privilege, or ship the report with a note that further research is needed.',
 'remember': 'Gap evaluation belongs to the coordinator: re-delegate, re-invoke synthesis, stop on a coverage criterion. Handing synthesis the full search toolset is the distractor; one scoped lookup tool is not (D2-08).',
 'alt': 'Synthesis with a gap sent back through the coordinator for a targeted query',
 'analogy': "The controller reads the picture that comes back, sees the stretch nobody covered, and sends one aircraft to that stretch rather than re-flying the whole task. The picture is rebuilt with the new returns, and the cycle ends when the controller's own criteria are met.",
 "svg": """<rect class="paper" x="40" y="16" width="60" height="32" rx="3"/>
<path class="thin" d="M48 28 h44 M48 38 h24"/>
<rect class="acc dash" x="76" y="33" width="18" height="10" rx="2"/>
<path d="M70 48 v22 M65 64 l5 6 5 -6"/>
<circle class="accfill" cx="70" cy="82" r="10"/>
<path class="acc" d="M80 82 h34 M108 77 l6 5 -6 5"/>
<circle class="tint" cx="126" cy="82" r="10"/>
<path class="acc" d="M126 72 V32 h-26 M106 27 l-6 5 6 5"/>""",
},
{
 'id': 'D1-11',
 'title': 'Task tool + allowedTools includes "Task"',
 'concept': 'Subagents are spawned with the `Task` tool, and a coordinator can invoke them only if `"Task"` is present in its `allowedTools`.',
 'tested': 'A coordinator attempts everything itself instead of delegating, and the question asks the cause or the change to make. The answer checks the coordinator\'s `allowedTools` for `"Task"`. Distractors rewrite the system prompt to instruct it to delegate, or add subagent descriptions to that prompt, neither of which grants a tool the configuration withholds.',
 'remember': 'No `"Task"` in `allowedTools`, no delegation. A prompt cannot grant a tool the configuration withholds, and descriptions spawn nothing on their own.',
 'alt': 'Tool list with Task highlighted, fanning out to three subagents',
 'analogy': 'A controller who has not been given the frequency cannot call the aircraft, however firmly the operations manual says to delegate. The instruction is in the book; the capability is in the equipment.',
 "svg": """<rect class="tint" x="14" y="26" width="56" height="66" rx="3"/>
<path class="thin" d="M22 42 h40 M22 76 h40"/>
<rect class="acc" x="20" y="52" width="44" height="14" rx="2"/>
<text class="lbl" x="42" y="63" text-anchor="middle">Task</text>
<path class="acc" d="M70 59 h20"/>
<path class="thin" d="M90 59 L103 36 M90 59 h13 M90 59 L103 82"/>
<circle class="tint" cx="112" cy="34" r="9"/>
<circle class="tint" cx="112" cy="60" r="9"/>
<circle class="tint" cx="112" cy="84" r="9"/>""",
},
{
 'id': 'D1-12',
 'title': 'AgentDefinition: description, system prompt, tool restrictions',
 'concept': 'An `AgentDefinition` configures each subagent type with a description, its own system prompt and the set of tools it is allowed to use.',
 'tested': "A question asks where a subagent type's behaviour and tool scope are configured, or offers a wider tool set for flexibility. The three levers sit in the `AgentDefinition`: description, system prompt, tool restrictions. Handing every subagent type the full set is the over-provisioning distractor, since restriction per type is how separation of responsibilities and least privilege are enforced.",
 'remember': 'One definition per subagent type, three levers: description, system prompt, tool restrictions. Restricting tools per type is the least-privilege mechanism, not a limit to work around.',
 'alt': 'Definition card with description, system prompt and an accented tools field',
 'analogy': 'Every position in the tower is defined the same way: what it handles, how it is to be worked, and which frequencies and switches it may touch. Handing every position every switch removes the reason for having separate positions.',
 "svg": """<rect class="paper" x="30" y="16" width="76" height="88" rx="3"/>
<line class="thin" x1="38" y1="30" x2="98" y2="30"/>
<text class="lbl" x="38" y="46">desc</text>
<line class="thin" x1="38" y1="52" x2="98" y2="52"/>
<text class="lbl" x="38" y="68">sys</text>
<line class="thin" x1="38" y1="74" x2="98" y2="74"/>
<rect class="acc" x="38" y="80" width="60" height="16" rx="2"/>
<text class="lbl" x="68" y="92" text-anchor="middle">tools</text>
<circle class="acc" cx="122" cy="88" r="7"/>
<path class="acc" d="M129 88 h16 M141 88 v6"/>""",
},
{
 'id': 'D1-13',
 'title': 'Content and metadata travel in separate fields',
 'concept': 'Findings passed between agents use a structured format that keeps content in one field and metadata — source URL, document name, page number — in another, so attribution survives aggregation.',
 'tested': 'The final report carries claims whose citations are missing or attached to the wrong source, and the question asks the root cause or the fix. Content and metadata were passed as merged free text, so the fix is a structured format that separates them. Distractors tell the synthesis agent to remember to cite, which it cannot do from metadata it never received, or send an agent back to the web to find sources for finished claims.',
 'remember': 'Claim in one field; source URL, document name and page number in another. A prompt to cite properly cannot recover metadata that was never passed.',
 'alt': 'Record with content above two accented metadata fields; merged blob crossed out',
 'analogy': 'Each contact goes onto the strip in its own boxes — callsign, level, squawk — so the next controller can read any one of them on its own. A single scribbled line holds the same words and loses which is which.',
 "svg": """<rect class="paper" x="14" y="24" width="60" height="72" rx="3"/>
<rect class="tint" x="22" y="34" width="44" height="22" rx="2"/>
<rect class="acc" x="22" y="62" width="44" height="10" rx="2"/>
<rect class="acc" x="22" y="78" width="44" height="10" rx="2"/>
<text class="lbl" x="44" y="106" text-anchor="middle">meta</text>
<rect class="dash" x="94" y="34" width="52" height="52" rx="3"/>
<path class="thin" d="M102 46 h36 M102 56 h36 M102 66 h36 M102 76 h20"/>
<line class="no" x1="110" y1="50" x2="130" y2="70"/>
<line class="no" x1="130" y1="50" x2="110" y2="70"/>""",
},
{
 'id': 'D1-14',
 'title': 'Parallel subagents: multiple Task calls in one response',
 'concept': 'Parallel subagents are spawned by emitting several `Task` tool calls inside a single coordinator response; the same calls issued across separate turns run sequentially.',
 'tested': 'A coordinator works independent research subtasks, or the parts of a multi-issue request, one after another, and the question asks how to run them in parallel. The answer emits all the `Task` calls in one coordinator response. Distractors ask for parallelism in the prompt wording, add more subagents, or name a concurrency setting that does not exist.',
 'remember': 'Several `Task` calls in one response run in parallel; one call per turn is sequential, whatever the prompt says. Parallelism is a property of the response.',
 'alt': 'One response fanning to three aircraft; a turn-by-turn chain crossed out',
 'analogy': 'The controller clears three aircraft in one transmission and all three start moving together. Reading the same three clearances out one at a time, waiting for each readback before the next, leaves the third aircraft holding while the first is already airborne.',
 "svg": """<rect class="tint" x="12" y="16" width="26" height="64" rx="3"/>
<text class="lbl" x="25" y="52" text-anchor="middle">1</text>
<path class="acc" d="M38 24 h28 M60 20 l6 4 -6 4"/>
<path class="acc" d="M38 48 h28 M60 44 l6 4 -6 4"/>
<path class="acc" d="M38 72 h28 M60 68 l6 4 -6 4"/>
<circle class="tint" cx="78" cy="24" r="8"/>
<circle class="tint" cx="78" cy="48" r="8"/>
<circle class="tint" cx="78" cy="72" r="8"/>
<rect class="dash thin" x="102" y="20" width="26" height="16" rx="2"/>
<path class="thin" d="M115 36 v34 M111 66 l4 4 4 -4"/>
<rect class="dash thin" x="102" y="70" width="26" height="16" rx="2"/>
<line class="no" x1="100" y1="24" x2="130" y2="82"/>
<line class="no" x1="130" y1="24" x2="100" y2="82"/>
<text class="lbl" x="115" y="102" text-anchor="middle">turns</text>""",
},
{
 'id': 'D1-15',
 'title': 'Coordinator prompts state goals and quality criteria, not procedures',
 'concept': "A coordinator's subagent prompts state the research goal and the quality criteria for the result rather than a step-by-step procedure, so subagents can adapt as findings emerge.",
 'tested': "A research coordinator returns shallow, checklist-shaped results, or its subagents stall when a step's output does not match the script, and the question asks how to change the coordinator prompt. The answer states the goal and the quality criteria, such as the areas that must be covered and the number of independent sources per claim, and leaves the method to the subagent. Distractors write more detailed steps, which deepens the rigidity, or add more subagents, which runs the same script more times.",
 'remember': 'Goal plus quality criteria, not step 1, step 2, step 3. More procedural detail and more subagents are the two distractors; both keep the script.',
 'alt': 'A goal target with criteria beside a crossed-out numbered step list',
 'analogy': 'The controller gives a pilot the runway, the level and the sequence, then leaves the flying to the pilot. A controller who called out each control input would have nothing left to give when the wind shifted on final approach.',
 "svg": """<rect class="paper" x="12" y="20" width="60" height="76" rx="3"/>
<circle class="acc" cx="42" cy="42" r="11"/>
<circle class="accfill" cx="42" cy="42" r="4"/>
<line class="thin" x1="22" y1="64" x2="62" y2="64"/>
<line class="thin" x1="22" y1="76" x2="62" y2="76"/>
<line class="thin" x1="22" y1="88" x2="50" y2="88"/>
<rect class="tint" x="88" y="20" width="60" height="76" rx="3"/>
<text class="lbl" x="98" y="42">1</text>
<text class="lbl" x="98" y="60">2</text>
<text class="lbl" x="98" y="78">3</text>
<line class="thin" x1="110" y1="38" x2="140" y2="38"/>
<line class="thin" x1="110" y1="56" x2="140" y2="56"/>
<line class="thin" x1="110" y1="74" x2="140" y2="74"/>
<line class="no" x1="110" y1="32" x2="144" y2="84"/>
<line class="no" x1="144" y1="32" x2="110" y2="84"/>""",
},
{
 'id': 'D1-16',
 'title': 'Programmatic enforcement vs prompt guidance',
 'concept': 'A sequence that must always hold is enforced in code with a hook or prerequisite gate that blocks the downstream tool until the prerequisite has returned, because prompt compliance is probabilistic.',
 'tested': "Production data shows the agent skipping `get_customer` and calling `lookup_order` on the customer's stated name, producing misidentified accounts and incorrect refunds, and the question asks the change that most effectively addresses it. The answer is a programmatic prerequisite that blocks `lookup_order` and `process_refund` until `get_customer` has returned a verified customer ID. Distractors strengthen the system prompt or add few-shot examples of the correct order, both of which rely on probabilistic compliance, or add a routing classifier, which changes which tools are available rather than the order they run in.",
 'remember': 'A sequence that must always hold goes in code: a hook or prerequisite gate. Stronger prompts and few-shot examples are the probabilistic distractors; tool availability is a different problem.',
 'alt': 'Verified id gate barring the pay tool; a bypass route crossed out',
 'analogy': 'The runway-lights interlock holds red until the previous aircraft has reported clear, so the clearance cannot be issued out of order. A standing instruction to the controller to check first is followed nearly every time; the wiring covers the rest.',
 "svg": """<rect class="tint" x="10" y="50" width="34" height="26" rx="3"/>
<text class="lbl" x="27" y="67" text-anchor="middle">id</text>
<path d="M44 63 h18 M56 59 l6 4 -6 4"/>
<path class="acc" d="M74 34 v72"/>
<circle class="accfill" cx="74" cy="63" r="5"/>
<path d="M82 63 h22 M98 59 l6 4 -6 4"/>
<rect class="tint" x="110" y="50" width="38" height="26" rx="3"/>
<text class="lbl" x="129" y="67" text-anchor="middle">pay</text>
<path class="dash" d="M30 48 q42 -32 84 0"/>
<line class="no" x1="66" y1="18" x2="82" y2="34"/>
<line class="no" x1="82" y1="18" x2="66" y2="34"/>""",
},
{
 'id': 'D1-17',
 'title': 'Structured handoff to a human',
 'concept': 'A mid-process escalation carries a structured summary — customer ID, root cause, refund amount, recommended action — because the human agent has no access to the conversation transcript.',
 'tested': "Human agents receiving escalations keep asking customers for details the agent already collected, and the question asks the root cause or the fix. The answer compiles a structured handoff summary: customer ID, root cause, amount, actions already taken, recommended action. Distractors hand the human the raw transcript, which they do not have by design, or have them re-run the agent's tools to rebuild the context.",
 'remember': 'Handoff payload: customer ID, root cause, amount, recommended action, actions taken. The summary is everything the human sees, so it has to stand alone.',
 'alt': 'Handover sheet of four fields passed to a person; transcript crossed out',
 'analogy': 'The controller coming on shift takes over from a written hand-over sheet: which aircraft, what state, what has been agreed, what to do next. They heard none of the transmissions, so anything left off the sheet is not available to them.',
 "svg": """<rect class="paper" x="14" y="18" width="62" height="84" rx="3"/>
<text class="lbl" x="22" y="38">id</text>
<line class="acc thin" x1="42" y1="34" x2="68" y2="34"/>
<text class="lbl" x="22" y="56">why</text>
<line class="acc thin" x1="48" y1="52" x2="68" y2="52"/>
<text class="lbl" x="22" y="74">amt</text>
<line class="acc thin" x1="48" y1="70" x2="68" y2="70"/>
<text class="lbl" x="22" y="92">next</text>
<line class="acc thin" x1="52" y1="88" x2="68" y2="88"/>
<path class="acc" d="M82 44 h16 M92 40 l6 4 -6 4"/>
<circle cx="122" cy="34" r="9"/>
<path d="M122 43 v18 M108 52 h28"/>
<rect class="dash thin" x="102" y="76" width="38" height="24" rx="2"/>
<line class="no" x1="108" y1="80" x2="134" y2="96"/>
<line class="no" x1="134" y1="80" x2="108" y2="96"/>""",
},
{
 'id': 'D1-18',
 'title': 'Multi-concern requests: split, investigate in parallel, synthesise',
 'concept': 'A message raising several issues is decomposed into distinct items, each investigated in parallel against shared context, then answered as one unified resolution.',
 'tested': 'A customer message carries three problems at once — a double charge, a discount that was not applied, an order to cancel — and the question asks how the agent should work it. The answer splits the message into items, investigates them in parallel on shared customer context, and returns one resolution. Distractors work the issues one after another, repeating the same lookups and raising the tool-call count, or answer each in its own reply and skip the synthesis.',
 'remember': 'Several concerns in one message: distinct items, parallel investigation, shared context, one answer. Sequential handling repeats lookups; a reply per issue drops the unified resolution.',
 'alt': 'One message split into three parallel items, merged into one answer',
 'analogy': 'A pilot calls with three things at once: a level change, a routing question and a fault report. The controller separates them, works all three against the same flight strip, and comes back with one instruction rather than three part-answers.',
 "svg": """<rect class="tint" x="10" y="44" width="26" height="32" rx="3"/>
<text class="lbl" x="23" y="64" text-anchor="middle">3?</text>
<rect class="dash thin" x="54" y="14" width="36" height="92" rx="3"/>
<path class="acc" d="M36 60 h10 v-32 h14"/>
<path class="acc" d="M36 60 h24"/>
<path class="acc" d="M36 60 h10 v32 h14"/>
<rect class="tint" x="60" y="20" width="24" height="16" rx="2"/>
<rect class="tint" x="60" y="52" width="24" height="16" rx="2"/>
<rect class="tint" x="60" y="84" width="24" height="16" rx="2"/>
<path class="acc" d="M84 28 h12 v32"/>
<path class="acc" d="M84 60 h12"/>
<path class="acc" d="M84 92 h12 v-32"/>
<path class="acc" d="M96 60 h14 M104 56 l6 4 -6 4"/>
<rect class="acc" x="114" y="46" width="32" height="28" rx="3"/>""",
},
{
 'id': 'D1-19',
 'title': 'Two-tool token binding vs a dry_run flag',
 'concept': 'A preview is guaranteed only when it is split into two tools: the preview tool returns a single-use confirmation token and the execute tool requires that token.',
 'tested': "A tool with a `dry_run` boolean is being called with `dry_run=false` directly, and the question asks the most reliable way to make every execution follow a preview the user confirmed. The answer replaces it with two tools, a preview tool returning a single-use confirmation token and an execute tool that requires the token. Distractors add instructions and few-shot examples to the tool description, or permit `dry_run=false` only when a matching `dry_run=true` call happened inside a time window. This card is about binding the preview into the tool contract; enforcing a required order between two tools is a prerequisite gate, which is the guide's own answer on that question (D1-16).",
 'remember': 'Mandatory preview: two tools bound by a token, so execution without a preview has no token to present. A flag the caller sets is a preview the caller can skip.',
 'alt': 'Preview issues a token the execute tool needs; bypass crossed out',
 'analogy': "The tower issues a numbered slip once the approach has been checked, and the runway controller accepts nothing but that slip. A tick-box on the pilot's own paperwork saying the check was done is filled in by whoever would otherwise have skipped it.",
 "svg": """<rect class="tint" x="10" y="16" width="44" height="28" rx="3"/>
<text class="lbl" x="32" y="34" text-anchor="middle">prev</text>
<path class="acc" d="M54 30 h20 M68 26 l6 4 -6 4"/>
<circle class="accfill" cx="86" cy="30" r="7"/>
<path class="acc" d="M86 37 v22 M82 53 l4 6 4 -6"/>
<rect class="tint" x="60" y="62" width="52" height="32" rx="3"/>
<circle class="acc thin" cx="86" cy="70" r="4"/>
<text class="lbl" x="86" y="88" text-anchor="middle">exec</text>
<path class="dash" d="M14 84 h46"/>
<line class="no" x1="25" y1="77" x2="39" y2="91"/>
<line class="no" x1="39" y1="77" x2="25" y2="91"/>""",
},
{
 'id': 'D1-20',
 'title': 'PostToolUse hooks normalise tool results',
 'concept': 'A `PostToolUse` hook intercepts tool results and normalises heterogeneous formats — Unix timestamps, ISO 8601, numeric status codes — from different MCP tools before the model processes them.',
 'tested': 'Several MCP tools return the same kind of value in different shapes and the agent compares or reads them wrongly, and the question asks where the conversion belongs. The answer is a `PostToolUse` hook that normalises each result before the model sees it. Distractors put the conversion in the prompt, where it has to be performed correctly on every result, or apply it after the model has already reasoned over the raw values.',
 'remember': 'Heterogeneous formats from several tools: a `PostToolUse` hook, applied before the model reads the result. Conversion asked for in the prompt is the probabilistic distractor.',
 'alt': 'Three formats passing through a hook into one uniform record',
 'analogy': "Heights arrive in feet from one aircraft and metres from another, times in local and in Zulu, so the tower's feed converts every report to one scale before it reaches the controller. The controller reads one set of units, and no conversion depends on someone remembering to do it.",
 "svg": """<rect class="tint" x="10" y="16" width="30" height="18" rx="2"/>
<text class="lbl" x="25" y="29" text-anchor="middle">1712</text>
<rect class="tint" x="10" y="50" width="30" height="18" rx="2"/>
<text class="lbl" x="25" y="63" text-anchor="middle">ISO</text>
<rect class="tint" x="10" y="84" width="30" height="18" rx="2"/>
<text class="lbl" x="25" y="97" text-anchor="middle">200</text>
<path class="thin" d="M40 25 h16 M50 21 l6 4 -6 4"/>
<path class="thin" d="M40 59 h16 M50 55 l6 4 -6 4"/>
<path class="thin" d="M40 93 h16 M50 89 l6 4 -6 4"/>
<rect class="acc" x="58" y="14" width="30" height="92" rx="4"/>
<text class="lbl" x="73" y="63" text-anchor="middle">hook</text>
<path class="acc" d="M88 59 h14 M96 55 l6 4 -6 4"/>
<rect class="paper" x="106" y="34" width="42" height="52" rx="3"/>
<line class="thin" x1="114" y1="48" x2="140" y2="48"/>
<line class="thin" x1="114" y1="60" x2="140" y2="60"/>
<line class="thin" x1="114" y1="72" x2="140" y2="72"/>""",
},
{
 'id': 'D1-21',
 'title': 'Intercept outgoing tool calls to block and redirect',
 'concept': 'A hook that intercepts outgoing tool calls blocks policy-violating actions, such as a refund above $500, and redirects them to an alternative workflow such as human escalation.',
 'tested': 'A business rule has to hold on every call, such as no refund above $500, and the question asks where to enforce it. The answer intercepts the outgoing tool call, blocks the violating one and redirects to human escalation. Distractors state the limit in the system prompt or the tool description, which holds most of the time, or check after the call has run, once the refund has already been issued.',
 'remember': 'Rule that must hold every time: intercept the outgoing call, block it, redirect. A limit stated in the prompt is probabilistic; a check after the call is too late.',
 'alt': 'Tool call stopped at a $500 barrier and redirected to a person',
 'analogy': "A clearance that would put two aircraft on one runway is refused by the tower's own system before it can be transmitted, and the go-around is offered instead. The refusal happens at the microphone, not after the readback.",
 "svg": """<rect class="tint" x="10" y="64" width="34" height="26" rx="3"/>
<text class="lbl" x="27" y="81" text-anchor="middle">call</text>
<path d="M44 77 h16 M54 73 l6 4 -6 4"/>
<path class="acc" d="M72 52 v46"/>
<text class="lbl" x="72" y="108" text-anchor="middle">$500</text>
<line class="no" x1="64" y1="70" x2="80" y2="84"/>
<line class="no" x1="80" y1="70" x2="64" y2="84"/>
<path class="acc" d="M62 72 q2 -38 30 -38 h16 M102 30 l6 4 -6 4"/>
<circle cx="126" cy="42" r="9"/>
<path d="M126 51 v20 M112 60 h28"/>""",
},
{
 'id': 'D1-22',
 'title': 'Prompt chaining vs adaptive decomposition',
 'concept': 'Prompt chaining runs passes fixed in advance and suits predictable multi-aspect work; dynamic adaptive decomposition generates each subtask from what the previous step discovered and suits open-ended investigation.',
 'tested': 'The stem names the workflow — a review that always follows the same template, or an open-ended task such as adding comprehensive tests to a legacy codebase — and asks which decomposition fits. Open-ended work maps the structure first, identifies high-impact areas, then builds a prioritised plan that adapts as dependencies are discovered. Distractors apply a fixed pipeline to a task whose scope is not known up front, apply dynamic decomposition to a predictable one, or put everything in a single pass.',
 'remember': "Scope known up front: prompt chaining, fixed passes. Scope discovered as you go: adaptive, so map, prioritise, adapt. The stem's phrase open-ended investigation is the tell.",
 'alt': 'A fixed three-step chain beside a plan that branches as it goes',
 'analogy': "The day's scheduled arrivals are worked from a sequence written before the shift began. A search flight is directed a leg at a time: the controller sends it where the last leg reported something, and the next instruction does not exist until that report comes in.",
 "svg": """<rect class="tint" x="12" y="18" width="34" height="18" rx="2"/>
<path class="thin" d="M29 36 v10 M25 42 l4 4 4 -4"/>
<rect class="tint" x="12" y="46" width="34" height="18" rx="2"/>
<path class="thin" d="M29 64 v10 M25 70 l4 4 4 -4"/>
<rect class="tint" x="12" y="74" width="34" height="18" rx="2"/>
<line class="dash thin" x1="58" y1="14" x2="58" y2="98"/>
<circle class="acc" cx="72" cy="92" r="6"/>
<path class="acc" d="M77 88 l16 -16"/>
<circle class="acc" cx="98" cy="67" r="6"/>
<path class="acc" d="M102 62 l14 -14"/>
<path class="acc" d="M94 62 l-6 -14"/>
<circle class="acc" cx="121" cy="43" r="6"/>
<circle class="acc" cx="86" cy="42" r="6"/>
<path class="acc dash" d="M125 38 l10 -12"/>
<path class="acc dash" d="M84 36 l-6 -12"/>
<text class="lbl" x="29" y="106" text-anchor="middle">fixed</text>
<text class="lbl" x="104" y="106" text-anchor="middle">adapt</text>""",
},
{
 'id': 'D1-23',
 'title': '--resume <session-name> continues a named session',
 'concept': '`--resume <session-name>` continues a specific named prior conversation with its saved context, so one investigation can be picked up across several work sessions.',
 'tested': 'A named investigation was left unfinished and the question asks how to carry it on in a later work session. The answer resumes that session by name with `--resume`. Distractors open a new conversation and re-describe the problem, or re-run the exploration from the beginning, both discarding context that is still valid.',
 'remember': '`--resume <session-name>` picks up that specific conversation with its context. Naming sessions is what keeps a multi-day investigation addressable; a new session starts empty.',
 'alt': 'A named flight strip pulled out of the rack of strips',
 'analogy': 'Each investigation has its own flight strip in the rack, filed under its number. The controller returning to it pulls that strip and has everything already agreed on it in front of them; a blank strip carries none of that history.',
 "svg": """<rect class="tint" x="10" y="18" width="74" height="88" rx="3"/>
<line class="thin" x1="84" y1="18" x2="84" y2="106"/>
<rect class="paper" x="16" y="24" width="62" height="16" rx="1"/>
<rect class="paper" x="16" y="68" width="62" height="16" rx="1"/>
<rect class="paper" x="16" y="88" width="62" height="14" rx="1"/>
<rect class="acc" x="16" y="46" width="128" height="16" rx="1"/>
<text class="lbl" x="112" y="58" text-anchor="middle">auth</text>""",
},
{
 'id': 'D1-24',
 'title': 'fork_session branches from a shared baseline',
 'concept': "`fork_session` creates independent branches from one shared analysis baseline, so two approaches can be explored without repeating the analysis and without either branch seeing the other's reasoning.",
 'tested': 'A team wants to compare two refactoring or testing strategies from one completed and expensive codebase analysis, and the question asks how to set that up. The answer is `fork_session` from the analysed session. Distractors run the two strategies one after another in the same session, where the first biases the second, or open two new sessions, each of which redoes the baseline analysis.',
 'remember': 'Compare approaches from one analysis: `fork_session`. Both branches inherit context up to the branch point, then diverge. Sequential in one session contaminates; two fresh sessions repeat the work.',
 'alt': 'One strip forking into two branches that exchange nothing',
 'analogy': "The strip for a flight already worked up is photocopied so two controllers can each run a what-if, one the northern routing and one the southern, from the same agreed picture. Neither sees the other's markings, and neither reads the flight plan again from the start.",
 "svg": """<rect class="tint" x="10" y="46" width="52" height="26" rx="2"/>
<line class="thin" x1="18" y1="56" x2="54" y2="56"/>
<line class="thin" x1="18" y1="64" x2="44" y2="64"/>
<path class="acc" d="M62 59 l14 -22 h10"/>
<path class="acc" d="M80 33 l6 4 -6 4"/>
<path class="acc" d="M62 59 l14 22 h10"/>
<path class="acc" d="M80 77 l6 4 -6 4"/>
<rect class="acc" x="88" y="20" width="52" height="26" rx="2"/>
<text class="lbl" x="114" y="37" text-anchor="middle">A</text>
<rect class="acc" x="88" y="72" width="52" height="26" rx="2"/>
<text class="lbl" x="114" y="89" text-anchor="middle">B</text>
<line class="dash thin" x1="114" y1="46" x2="114" y2="72"/>
<line class="no" x1="107" y1="52" x2="121" y2="66"/>
<line class="no" x1="121" y1="52" x2="107" y2="66"/>""",
},
{
 'id': 'D1-25',
 'title': 'Resume and name what changed, or start fresh',
 'concept': 'Resume when prior context is mostly valid, start a new session with a structured summary when prior tool results are stale, and on resume name the files that changed.',
 'tested': 'A session analysed the codebase and several files have since been refactored, and the question asks how to continue. The answer resumes the named session and states which files changed, so re-analysis is targeted. Distractors resume without mentioning the changes, leaving the agent reasoning over stale tool results, or re-explore the whole codebase when most of the context still holds.',
 'remember': 'Mostly valid: resume, and name the changed files. Stale: a new session with a structured summary, which carries the conclusions without the outdated evidence.',
 'alt': 'File list with two rows marked, feeding the tower for re-analysis',
 'analogy': 'A controller returning to a strip after a break is told which two aircraft have changed level, and re-checks those two. When the picture has moved on entirely, the strip is written out afresh from the current state rather than annotated.',
 "svg": """<rect class="paper" x="12" y="18" width="64" height="84" rx="3"/>
<line class="thin" x1="22" y1="32" x2="68" y2="32"/>
<line class="acc" x1="22" y1="48" x2="68" y2="48"/>
<circle class="accfill" cx="16" cy="48" r="3"/>
<line class="thin" x1="22" y1="64" x2="68" y2="64"/>
<line class="acc" x1="22" y1="80" x2="68" y2="80"/>
<circle class="accfill" cx="16" cy="80" r="3"/>
<line class="thin" x1="22" y1="96" x2="68" y2="96"/>
<path class="acc" d="M80 64 h16 M90 60 l6 4 -6 4"/>
<path class="tint" d="M116 104 L120 68 H130 L134 104 Z"/>
<rect class="tint" x="108" y="50" width="34" height="16" rx="3"/>
<path class="thin" d="M112 50 L115 40 H135 L138 50"/>""",
},
]
