"""Merge items_<part>.py halves into items_dN.py in inventory order. Usage: python merge_parts.py [d1 d2 d4 d5]"""
import importlib.util
import os
import pprint
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("inventory", os.path.join(HERE, "inventory.py"))
inv = importlib.util.module_from_spec(spec); spec.loader.exec_module(inv)

TITLE = {"D1": "Domain 1 — Agentic Architecture & Orchestration · building: the control tower",
         "D2": "Domain 2 — Tool Design & MCP Integration · building: the library",
         "D4": "Domain 4 — Prompt Engineering & Structured Output · building: the courthouse",
         "D5": "Domain 5 — Context Management & Reliability · building: the hospital ward"}


def load(name):
    p = os.path.join(HERE, name + ".py")
    if not os.path.exists(p): return None
    s = importlib.util.spec_from_file_location(name, p)
    m = importlib.util.module_from_spec(s); s.loader.exec_module(m); return m


for d in (sys.argv[1:] or ["d1", "d2", "d4", "d5"]):
    parts = [p for p in inv.PARTS if p.startswith(d)]
    pool = {}
    missing_parts = []
    for p in sorted(parts):
        m = load(f"items_{p}")
        if m is None:
            missing_parts.append(p); continue
        for it in m.ITEMS:
            pool[it["id"]] = it
    want = [c["id"] for c in inv.CARDS if c["id"].startswith(d.upper() + "-")]
    have = [i for i in want if i in pool]
    if missing_parts:
        print(f"{d}: parts missing {missing_parts} — merged {len(have)}/{len(want)} cards, not written"); continue
    if len(have) != len(want):
        print(f"{d}: MISSING ids {[i for i in want if i not in pool]} — not written"); continue
    out = [f"# {TITLE[d.upper()]}", "# Generated by merge_parts.py from the authoring halves — edit the halves, not this file.", "", "ITEMS = ["]
    for i in want:
        it = pool[i]
        out.append("{")
        for k in ["id", "title", "concept", "tested", "remember", "alt"]:
            out.append(f" {k!r}: {it[k]!r},")
        out.append(f" 'analogy': {it['analogy']!r},")
        svg = it["svg"]
        if '"""' in svg or svg.endswith('"') or svg.endswith("\\"):
            out.append(f" 'svg': {svg!r},")          # defensive: triple-quoting would break
        else:
            out.append(' "svg": """' + svg + '""",')
        out.append("},")
    out.append("]")
    open(os.path.join(HERE, f"items_{d}.py"), "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(f"{d}: wrote items_{d}.py with {len(have)} cards")
